/**
 * /portal/[firmId]/triage/[leadId]
 *
 * Single-lead brief view. Reads the screened_leads row and renders the
 * pre-rendered brief_html verbatim — the moment-in-time snapshot the screen
 * captured at submission. The wrapper around it adds the decision-timer
 * header and (Phase 2) the sticky Take/Pass action bar.
 *
 * Trust boundary: brief_html is generated by our own engine (buildReport in
 * the screen, captured from reportArea.innerHTML). It is not user-supplied
 * HTML. Direct dangerouslySetInnerHTML is acceptable here. If we ever start
 * accepting third-party brief renderers, sanitise at write time in
 * /api/intake-v2 before this surface gets it.
 */

import Link from "next/link";
import { notFound } from "next/navigation";
import { supabaseAdmin as supabase } from "@/lib/supabase-admin";
import { matterLabel, subtrackLabel } from "@/lib/screened-leads-labels";
import DecisionTimer from "@/components/portal/DecisionTimer";
import TriageActionBar from "@/components/portal/TriageActionBar";
import "./brief.css";

interface LeadRow {
  lead_id: string;
  firm_id: string;
  status: "triaging" | "taken" | "passed" | "declined";
  brief_html: string;
  brief_json: { matter_snapshot?: string } | null;
  band: "A" | "B" | "C" | null;
  matter_type: string;
  whale_nurture: boolean;
  band_c_subtrack: string | null;
  decision_deadline: string;
  submitted_at: string;
  contact_name: string | null;
}

export const dynamic = "force-dynamic";
export const revalidate = 0;

export default async function TriageLeadPage({
  params,
}: {
  params: Promise<{ firmId: string; leadId: string }>;
}) {
  const { firmId, leadId } = await params;

  const { data, error } = await supabase
    .from("screened_leads")
    .select(`
      lead_id, firm_id, status, brief_html, brief_json,
      band, matter_type, whale_nurture, band_c_subtrack,
      decision_deadline, submitted_at, contact_name
    `)
    .eq("lead_id", leadId)
    .maybeSingle();

  if (error) {
    return (
      <div className="bg-white border border-red-200 px-6 py-6">
        <p className="text-sm text-red-700">Could not load this brief: {error.message}</p>
      </div>
    );
  }
  // Hide cross-firm existence: 404 even when the row exists for another firm.
  if (!data || data.firm_id !== firmId) notFound();

  const row = data as LeadRow;
  const subtrack = subtrackLabel(row.band_c_subtrack);

  return (
    <div className="space-y-4 pb-32">
      <BackLink firmId={firmId} />
      <Header row={row} subtrack={subtrack} />
      {row.status !== "triaging" && <StatusBanner status={row.status} />}
      <BriefFrame html={row.brief_html} />
      <TriageActionBar
        firmId={firmId}
        leadId={row.lead_id}
        band={row.band}
        initialStatus={row.status}
      />
    </div>
  );
}

function BackLink({ firmId }: { firmId: string }) {
  return (
    <Link
      href={`/portal/${firmId}/triage`}
      className="inline-block text-xs uppercase tracking-wider font-semibold text-black/50 hover:text-navy"
    >
      ← Back to queue
    </Link>
  );
}

function Header({ row, subtrack }: { row: LeadRow; subtrack: string | null }) {
  return (
    <div className="bg-white border border-black/10 px-6 py-5">
      <div className="flex items-start justify-between gap-6 flex-wrap">
        <div className="min-w-0">
          <p className="text-xs uppercase tracking-wider font-semibold text-gold">Lawyer triage</p>
          <h1 className="text-2xl font-bold text-navy mt-1">{matterLabel(row.matter_type)}</h1>
          <div className="mt-1 flex items-center gap-2 text-xs text-black/50">
            <span className="font-mono">{row.lead_id}</span>
            {row.contact_name && (
              <>
                <span aria-hidden>·</span>
                <span>{row.contact_name}</span>
              </>
            )}
          </div>
          <div className="mt-2 flex items-center gap-2 flex-wrap">
            <BandBadge band={row.band} />
            {row.whale_nurture && (
              <span className="text-[10px] uppercase tracking-wider font-semibold bg-gold/20 text-navy px-2 py-0.5 border border-gold/40">
                Whale nurture · long-game cadence active
              </span>
            )}
            {subtrack && (
              <span className="text-[10px] uppercase tracking-wider font-semibold bg-parchment-2 text-black/70 px-2 py-0.5 border border-black/10">
                {subtrack}
              </span>
            )}
          </div>
        </div>
        <div className="shrink-0">
          <DecisionTimer
            deadlineIso={row.decision_deadline}
            submittedAtIso={row.submitted_at}
            variant="header"
          />
        </div>
      </div>
    </div>
  );
}

function BandBadge({ band }: { band: "A" | "B" | "C" | null }) {
  const colour =
    band === "A" ? "bg-emerald-100 text-emerald-900 border-emerald-300"
    : band === "B" ? "bg-amber-100 text-amber-900 border-amber-300"
    : band === "C" ? "bg-stone-100 text-stone-700 border-stone-300"
                   : "bg-stone-50 text-stone-500 border-stone-200";
  return (
    <span
      className={`inline-flex items-center justify-center font-mono font-bold text-sm h-7 px-2.5 border ${colour}`}
    >
      Band {band ?? "—"}
    </span>
  );
}

function StatusBanner({ status }: { status: LeadRow["status"] }) {
  const text =
    status === "taken"    ? "This lead has been taken. Cadence engaged."
    : status === "passed"  ? "This lead has been passed. Decline-with-grace fired."
    : status === "declined" ? "This lead was auto-declined."
                            : "";
  return (
    <div className="bg-parchment-2 border border-black/10 px-4 py-3 text-sm text-black/70">
      {text}
    </div>
  );
}

/**
 * The brief_html field is the screen's reportArea innerHTML at submit time —
 * a self-contained snapshot of the lawyer brief with all its sections,
 * provenance tags, and axis breakdowns. The screen's CSS lives in its own
 * bundle and does not load here, so the brief renders as semantic HTML
 * styled by inherited body fonts. That's intentional MVP behaviour: legible
 * but unstyled. A follow-up pass can either inline the brief CSS into the
 * captured HTML or import the screen's stylesheet.
 */
function BriefFrame({ html }: { html: string }) {
  // The brief HTML carries its own group panels, headers, and section
  // structure (see brief.css for the styling contract). The outer wrapper
  // adds only horizontal padding so the grouped panels breathe inside the
  // portal's max-w-5xl content column.
  return (
    <div
      className="brief-frame px-2 md:px-4"
      // eslint-disable-next-line react/no-danger
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}

