/**
 * event-slot-map.ts — Maps event extractor types to their canonical question bank entries.
 *
 * WHY THIS EXISTS
 * ───────────────
 * The event question system detects information gaps from the user's first message
 * (e.g. "When did the incident happen?" for slip_fall) and presents them as clickable
 * UI questions. Previously these were generated by event-question-generator.ts using
 * hand-coded text strings and a separate TIMING_OPTIONS constant.
 *
 * The question bank (default-question-modules.ts) already has correctly authored
 * timing questions for every practice area — with proper option labels, option values,
 * and scoring metadata. Duplicating them in the event question system created two
 * sources of truth that diverged silently.
 *
 * This file is the bridge: given an event type and a gap kind ("when"), return the
 * canonical question bank entry. The route reads from this map rather than calling
 * generateQuestion() + generateQuestionOptions(). For event types not yet mapped,
 * the route falls back to the generator.
 *
 * SINGLE SOURCE OF TRUTH CONTRACT
 * ─────────────────────────────────
 *   - Question text  → from bank question.text
 *   - Input options  → from bank question.options (label/value stripped of scoring fields)
 *   - allow_free_text → false when bank options exist, true otherwise
 *   - De-duplication → by question ID (exact match), not by text (fragile)
 *
 * ADDING A NEW EVENT TYPE
 * ────────────────────────
 * 1. Add a row to EVENT_TIMING_SLOT_MAP with the event type as key.
 * 2. Point to the practice area key and the timing question's ID in that area's bank.
 * 3. Done. No other files need to change.
 *
 * If the practice area bank does not yet have a timing question, leave the event type
 * out of this map. The route falls back to the generator for unmapped types.
 */

/**
 * Reference to a question within a practice-area question bank.
 */
export interface BankSlotRef {
  /** Key in firmConfig.question_sets (e.g. "pi", "emp", "civ"). */
  questionSetKey: string;
  /** Stable question ID within that bank (e.g. "pi_q16"). */
  questionId: string;
}

/**
 * Maps event extractor types to the bank question that covers the WHEN gap.
 *
 * Only event types where REQUIRES_TIME is true (limitation-period analysis requires
 * a date) appear here. Types where REQUIRES_TIME is false (unpaid_overtime,
 * real_estate_defect, marriage_to_citizen) don't have timing questions and are absent.
 *
 * Both slip_fall and mva map to pi_q16 — the PI bank uses a single timing question
 * for all personal injury sub-types.
 */
export const EVENT_TIMING_SLOT_MAP: Record<string, BankSlotRef> = {
  slip_fall:   { questionSetKey: "pi",  questionId: "pi_q16"  },
  mva:         { questionSetKey: "pi",  questionId: "pi_q16"  },
  termination: { questionSetKey: "emp", questionId: "emp_q16" },
  // debt_owed and deportation: no suitable timing question exists in their banks yet.
  // When added to the bank, add a mapping here.
};
