import type { ReconciliationStatus } from "@/lib/gta-prospect-records";

export type CanonicalRecord = { sourceRecordKey: string; firmName: string; normalizedFirmName: string; city: string; practiceAreas: string[]; legacyCrosswalk: string | null; legacyClusterLawyerCount: number | null; websiteUrl: string | null; officeCities: string[]; roster: { sourceUrl: string; observedOn: string; lawyerCount: number | null; qualifier: "exact" | "at_least" | "unknown"; display: string | null }; reconciliation: { status: ReconciliationStatus; basis: string }; evidence: { type: "roster" | "advertising" | "google_business_profile" | "website"; sourceUrl: string; observedOn: string; value: string | null }[] };
export type ValidationIssue = { sourceRecordKey: string; message: string };
export type GtaProspectImportPlan = { accepted: CanonicalRecord[]; rejected: { sourceRecordKey: string; issues: ValidationIssue[] }[]; sourceSha256: string };
const keys = new Set(["id","firmName","city","officeCities","websiteUrl","practiceAreas","observedLawyerCount","observedLawyerCountQualifier","observedLawyerCountDisplay","rosterSourceUrl","rosterCheckedAt","reconciliationStatus","legacyClusterLawyerCount","legacyCrosswalk","reconciliationNote","advertisingEvidence","advertisingSourceUrl","gbpEvidence","gbpSourceUrl"]);
const statuses = new Set<ReconciliationStatus>(["provisional_new","update_existing","new_pending_identity","duplicate","unresolved"]);
const object = (v: unknown): v is Record<string, unknown> => Boolean(v) && typeof v === "object" && !Array.isArray(v);
const text = (v: unknown): v is string => typeof v === "string" && v.trim().length > 0;
const norm = (v: string) => v.trim().toLocaleLowerCase().replace(/\s+/g, " ");
const stable = (v: unknown): string => Array.isArray(v) ? `[${v.map(stable).join(",")}]` : object(v) ? `{${Object.keys(v).sort().map(k => `${JSON.stringify(k)}:${stable(v[k])}`).join(",")}}` : JSON.stringify(v);
export async function sha256(v: unknown): Promise<string> { const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(stable(v))); return Array.from(new Uint8Array(digest), b => b.toString(16).padStart(2,"0")).join(""); }
const url = (v: unknown): v is string => { if (!text(v)) return false; try { const parsed = new URL(v); return parsed.protocol === "http:" || parsed.protocol === "https:"; } catch { return false; } };
const date = (v: unknown): v is string => { if(typeof v!=="string"||!/^\d{4}-\d{2}-\d{2}$/.test(v)) return false; const [y,m,d]=v.split("-").map(Number); const check=new Date(Date.UTC(y,m-1,d)); return check.getUTCFullYear()===y&&check.getUTCMonth()===m-1&&check.getUTCDate()===d; };

function project(input: unknown): { record: CanonicalRecord | null; issues: ValidationIssue[]; key: string } {
  const key = object(input) && typeof input.id === "string" ? input.id : "<missing-id>"; const issues: ValidationIssue[] = []; const fail = (m: string) => issues.push({ sourceRecordKey: key, message: m });
  if (!object(input)) { fail("record must be an object"); return { record: null, issues, key }; }
  const unknown = Object.keys(input).filter(k => !keys.has(k)); if (unknown.length) fail(`unrecognized fields are forbidden: ${unknown.join(", ")}`);
  if (!text(input.id) || !/^[a-z0-9][a-z0-9-]{1,159}$/.test(input.id)) fail("id must be a stable lowercase source key"); if (!text(input.firmName)) fail("firmName is required");
  if (!Array.isArray(input.officeCities) || input.officeCities.length === 0 || !input.officeCities.every(text)) fail("at least one office city is required"); if (input.websiteUrl !== null && input.websiteUrl !== undefined && !url(input.websiteUrl)) fail("websiteUrl must be an http(s) URL when supplied");
  if (!url(input.rosterSourceUrl)) fail("accepted records require a roster source URL"); if (!date(input.rosterCheckedAt)) fail("accepted records require a roster observation date"); if (!statuses.has(input.reconciliationStatus as ReconciliationStatus)) fail("reconciliationStatus is invalid");
  if(!text(input.city)||!Array.isArray(input.practiceAreas)||!input.practiceAreas.every(text)) fail("city and practiceAreas must be expected primitive values");
  for(const field of ["observedLawyerCountDisplay","reconciliationNote","legacyCrosswalk"] as const) if(input[field] !== null && typeof input[field] !== "string") fail(`${field} must be a nullable string`);
  if(input.legacyClusterLawyerCount !== null && (!Number.isInteger(input.legacyClusterLawyerCount)||Number(input.legacyClusterLawyerCount)<0)) fail("legacyClusterLawyerCount must be a nullable non-negative integer");
  const qualifier = input.observedLawyerCountQualifier; if (qualifier !== "exact" && qualifier !== "at_least" && qualifier !== "unknown") fail("observed lawyer count qualifier is invalid"); if (qualifier === "unknown" && input.observedLawyerCount !== null) fail("unknown count qualifier requires a null observed lawyer count"); if ((qualifier === "exact" || qualifier === "at_least") && (!Number.isInteger(input.observedLawyerCount) || Number(input.observedLawyerCount) < 0)) fail("exact and at_least counts require a non-negative integer");
  if (input.advertisingEvidence === "observed" && !url(input.advertisingSourceUrl)) fail("observed advertising requires its source URL"); if (input.gbpEvidence === "observed" && !url(input.gbpSourceUrl)) fail("observed Google Business Profile evidence requires its source URL");
  if (issues.length) return { record: null, issues, key }; const sourceUrl = input.rosterSourceUrl as string; const observedOn = input.rosterCheckedAt as string; const websiteUrl = (input.websiteUrl as string | null) ?? null; const firmName = input.firmName as string;
  return { key, issues, record: { sourceRecordKey: input.id as string, firmName, normalizedFirmName: norm(firmName), city: input.city as string, practiceAreas: [...input.practiceAreas as string[]], legacyCrosswalk: input.legacyCrosswalk as string|null, legacyClusterLawyerCount: input.legacyClusterLawyerCount as number|null, websiteUrl, officeCities: [...input.officeCities as string[]], roster: { sourceUrl, observedOn, lawyerCount: input.observedLawyerCount as number | null, qualifier: qualifier as "exact" | "at_least" | "unknown", display: input.observedLawyerCountDisplay as string | null }, reconciliation: { status: input.reconciliationStatus as ReconciliationStatus, basis: (input.reconciliationNote as string | null) ?? "Status supplied by the reviewed source-controlled record." }, evidence: [{ type: "roster", sourceUrl, observedOn, value: input.observedLawyerCountDisplay as string | null }, ...(websiteUrl ? [{ type: "website" as const, sourceUrl: websiteUrl, observedOn, value: websiteUrl }] : []), ...(input.advertisingEvidence === "observed" ? [{ type: "advertising" as const, sourceUrl: input.advertisingSourceUrl as string, observedOn, value: null }] : []), ...(input.gbpEvidence === "observed" ? [{ type: "google_business_profile" as const, sourceUrl: input.gbpSourceUrl as string, observedOn, value: null }] : [])] } };
}
export async function buildGtaProspectImportPlan(inputs: readonly unknown[]): Promise<GtaProspectImportPlan> { const seen = new Set<string>(), accepted: CanonicalRecord[] = [], rejected: GtaProspectImportPlan["rejected"] = []; for (const input of inputs) { const result = project(input); if (seen.has(result.key)) result.issues.push({ sourceRecordKey: result.key, message: "duplicate source record key within batch" }); seen.add(result.key); if (result.record && result.issues.length === 0) accepted.push(result.record); else rejected.push({ sourceRecordKey: result.key, issues: result.issues }); } return { accepted, rejected, sourceSha256: await sha256(accepted) }; }
export type GtaProspectImportWriter = { apply(plan: GtaProspectImportPlan): Promise<void> };
export async function executeGtaProspectImport({ plan, dryRun, operatorAuthorized, writer }: { plan: GtaProspectImportPlan; dryRun: boolean; operatorAuthorized: boolean; writer: GtaProspectImportWriter }) { if (dryRun) return { state: "dry_run" as const, plan }; if (!operatorAuthorized) return { state: "unauthorized" as const, plan }; if (plan.rejected.length) return { state: "rejected" as const, plan }; await writer.apply(plan); return { state: "applied" as const, plan }; }
