/**
 * intake-memo.ts  -  Shared memo + follow-up presentation helpers.
 *
 * Single source of truth for what the lawyer sees after intake completes,
 * across three surfaces:
 *   - Demo overlay (src/components/demo/LawyerViewPanel.tsx)
 *   - Admin CRM lead detail (src/app/leads/[id]/page.tsx)
 *   - Firm portal lead detail (src/app/portal/[firmId]/leads/[leadId]/page.tsx)
 *
 * Two things live here:
 *
 *   1. BAND_FOLLOWUP  -  numbered next-steps per CPI band. Pure presentation
 *      copy, identical across all surfaces.
 *
 *   2. buildDynamicMemo  -  fallback memo builder for the demo overlay, used
 *      when no scenario fixture is selected and no AI-generated memo is
 *      available. The real product consumes intake_sessions.memo_text
 *      directly (generated by src/lib/memo.ts after Round 3).
 *
 * No "use client" directive: this module exports only plain data and pure
 * functions (no hooks, no browser APIs), so it's safely importable from
 * both server components (admin/portal pages) and client components
 * (the demo overlay).
 */

// ─────────────────────────────────────────────
// Memo shape
// ─────────────────────────────────────────────

export interface MemoData {
  jurisdictionTimeline: string;
  evidenceHeading: string;
  evidenceItems: Array<{ checked: boolean; text: string }>;
  adverseParties: string;
  pathwayAssessment?: string;
  gaps: string[];
}

// ─────────────────────────────────────────────
// Follow-up protocol (lawyer next actions by band)
// ─────────────────────────────────────────────

export const BAND_FOLLOWUP: Record<string, string[]> = {
  A: [
    "Senior lawyer calls within 30 minutes of intake.",
    "Initial consultation confirms fit and legal theory.",
    "Retainer released on the call if both parties proceed.",
  ],
  B: [
    "Lawyer outreach within 4 hours, call or email.",
    "15-20 minute intake call to scope the matter.",
    "Retainer sent post-call if the file proceeds.",
  ],
  C: [
    "Intake coordinator reviews within 24 hours.",
    "If the file fits practice areas, consultation is scheduled.",
    "If not, client is pointed to an appropriate resource.",
  ],
  D: [
    "No immediate lawyer time committed.",
    "6-month educational nurture runs in the background.",
    "Lead re-scored if circumstances change.",
  ],
  E: [
    "No CRM entry created.",
    "Client redirected to LSO Law Society referral service.",
    "No further outreach from the firm.",
  ],
};

export function getFollowupSteps(band: string | null | undefined): string[] {
  const key = (band ?? "E").toUpperCase();
  return BAND_FOLLOWUP[key] ?? BAND_FOLLOWUP["E"];
}

// ─────────────────────────────────────────────
// Practice-area default gap probes (demo fallback)
// ─────────────────────────────────────────────

export const PRACTICE_AREA_GAPS: Record<string, string[]> = {
  pi: [
    "Full medical records and ongoing treatment plan",
    "Police or collision report status",
    "Employment income loss documentation",
    "Any statements given to insurers",
    "Opposing party insurance information",
  ],
  emp: [
    "Written employment contract and signed agreements",
    "Termination letter and stated reasons",
    "Severance offered versus statutory minimums",
    "Non-compete or non-solicitation clauses",
    "Current job search and mitigation status",
  ],
  fam: [
    "Marriage or cohabitation start date and current status",
    "Financial disclosure: income, assets, debts",
    "Children's custody arrangements and school details",
    "Any existing agreements (prenup, separation)",
    "Urgency factors: safety, relocation, support",
  ],
  imm: [
    "Current immigration status and permit expiry date",
    "Prior applications, refusals, or removal orders",
    "Criminal or inadmissibility history",
    "Relationship documentation, if sponsorship",
    "Language test scores and credential assessments",
  ],
  real: [
    "Agreement of Purchase and Sale (APS) status",
    "Closing date and financing conditions",
    "Property inspection results and deficiencies",
    "Title search and any liens",
    "Deposit status and escrow arrangements",
  ],
  llt: [
    "Lease agreement terms and start date",
    "Notice documents served (N4, N12, L1, etc.)",
    "Rent payment and arrears history",
    "Maintenance requests and landlord responses",
    "Any existing Landlord and Tenant Board filings",
  ],
  crim: [
    "Exact charges and court appearance dates",
    "Prior criminal record, if any",
    "Disclosure package status",
    "Bail or release conditions",
    "Co-accused and potential witnesses",
  ],
  wills: [
    "Current marital status and dependents",
    "Assets inventory and estimated values",
    "Existing wills or powers of attorney",
    "Preferred executor and guardian nominations",
    "Specific bequests and charitable intentions",
  ],
  corp: [
    "Corporate structure and jurisdiction of incorporation",
    "Shareholder agreements and capitalization",
    "Revenue figures and employee count",
    "Pending litigation or regulatory disputes",
    "Industry-specific licensing requirements",
  ],
  sc: [
    "Amount in dispute and documentation",
    "Correspondence with opposing party",
    "Any contracts or agreements at issue",
    "Witness statements or supporting evidence",
    "Limitation period considerations",
  ],
  small_claims: [
    "Amount in dispute and documentation",
    "Correspondence with opposing party",
    "Any contracts or agreements at issue",
    "Witness statements or supporting evidence",
    "Limitation period considerations",
  ],
};

export const DEFAULT_GAPS = [
  "Relevant jurisdiction and limitation periods",
  "Full documentary evidence",
  "Any prior legal advice or retainers on this matter",
  "Status of opposing party or counsel",
  "Client's desired outcome and preferred timeline",
];

// ─────────────────────────────────────────────
// Dynamic memo construction (demo fallback)
// ─────────────────────────────────────────────

// Demo overlay fallback. When the demo has no scenarioId fixture and no AI
// memo_text is available, produce a memo from the raw session shape so every
// A/B/C case still renders something coherent. Real product does NOT use this:
// it reads intake_sessions.memo_text directly.
export function buildDynamicMemo(params: {
  situationSummary: string | null;
  practiceArea: string | null;
  intakeTrail?: Array<{ question: string; answer: string }>;
}): MemoData {
  const { situationSummary, practiceArea, intakeTrail } = params;
  const paKey = practiceArea?.toLowerCase() ?? "";
  const gaps = PRACTICE_AREA_GAPS[paKey] ?? DEFAULT_GAPS;

  const trailItems = (intakeTrail ?? []).slice(0, 6).map(item => {
    const q = item.question.replace(/[?:.]+\s*$/, "").trim();
    const shortQ = q.length > 48 ? q.slice(0, 45) + "..." : q;
    const shortA = item.answer.length > 90 ? item.answer.slice(0, 87) + "..." : item.answer;
    return { checked: true, text: `${shortQ}: ${shortA}` };
  });

  const evidenceItems: MemoData["evidenceItems"] = [];
  if (situationSummary) {
    const short = situationSummary.length > 200
      ? situationSummary.slice(0, 197) + "..."
      : situationSummary;
    evidenceItems.push({ checked: true, text: `Client account: ${short}` });
  }
  evidenceItems.push(...trailItems);

  return {
    jurisdictionTimeline: "Ontario. Exact dates and limitation period to be confirmed with client on initial call.",
    evidenceHeading: "Intake Summary",
    evidenceItems,
    adverseParties: "To be confirmed with client on initial call. Conflict check pending.",
    gaps,
  };
}
