/**
 * Publication Operator, Workstream 3: publication adapter contract.
 *
 * A shared interface every destination (Website, LinkedIn, Google Business
 * Profile) implements the same way, so the orchestration layer (Workstream
 * 4) never special-cases a destination beyond picking the right adapter.
 *
 * This release ships DRY-RUN ONLY. `execute` is structurally disabled: no
 * code path in this file, or in any adapter it returns, ever performs a
 * network write to LinkedIn, Google Business Profile, or a website deploy
 * target. There is nothing to flag or gate around, because no live-call
 * implementation exists yet for any destination (see WS0 discovery: no
 * LinkedIn/GBP API credentials, OAuth client, or website-deploy integration
 * exists anywhere in this codebase). `isLiveExecutionEnabled` below
 * describes the FUTURE gate shape the release ladder calls for (an env
 * flag AND per-destination credentials, both required) purely so a later
 * release has a named place to wire a real check; it always evaluates to
 * false in this release regardless of its inputs, and `execute` does not
 * consult it to decide whether to call anything -- it has nothing to call.
 *
 * `reconcile` and `normalizeReceipt` reuse the existing, tested Workstream
 * 5/6 evidence system (publication-receipts.ts, channel-validation.ts)
 * rather than re-implementing verification. `preflight` reuses
 * publication-preflight-status.ts (Workstream 2 of this brief). Nothing
 * here duplicates prior work; this module is the thin, uniform seam over
 * all of it.
 */

import type { PlacementDestination, PublicationReceipt, PublicationArtifactType } from "@/lib/types";
import type { PublicationExecutionManifest } from "@/lib/publication-execution-manifest";
import {
  evaluatePublicationPreflightStatus,
  type PublicationPreflightStatus,
} from "@/lib/publication-preflight-status";
import {
  validateReceiptForDestination,
  isManuallyVerifiableDestination,
  type ChannelValidationResult,
} from "@/lib/channel-validation";

export interface AdapterConfigurationResult {
  configured: boolean;
  /** Human-readable, secret-free reasons (e.g. "no LinkedIn account or API integration is configured"). Never includes credential values. */
  issues: string[];
  /** Env var / config NAMES this destination would need, for operator visibility. Never their values. */
  requiredConfigNames: string[];
}

export interface DryRunAction {
  method: string;
  /** Redacted endpoint/action shape -- e.g. "POST https://api.linkedin.com/v2/ugcPosts (no live client exists; illustrative shape only)" or "manual: operator deploys drg-law-website and records a receipt". */
  endpoint: string;
  summary: string;
  /** Redacted payload preview: real field NAMES and non-secret facts (title length, locale, tracked URL), never raw personal data beyond what the manifest already carries as approved content, never any credential. */
  payloadPreview: Record<string, unknown>;
  requiresManualAction: boolean;
}

export interface ExecuteResult {
  ok: false;
  error: string;
}

export interface NormalizedReceiptInput {
  destination: PlacementDestination;
  publicUrl: string | null;
  externalPostId: string | null;
  publishedAt: string;
}

/** Raw evidence an operator supplies after a manual publish action (never generated by this system). */
export interface RawPublishEvidence {
  publicUrl?: string | null;
  externalPostId?: string | null;
  publishedAt?: string | null;
}

export interface PublicationAdapter {
  destinations: readonly PlacementDestination[];
  validateConfiguration(manifest: PublicationExecutionManifest): AdapterConfigurationResult;
  preflight(manifest: PublicationExecutionManifest): PublicationPreflightStatus;
  renderDryRun(manifest: PublicationExecutionManifest): DryRunAction;
  execute(manifest: PublicationExecutionManifest): Promise<ExecuteResult>;
  reconcile(
    receipt: PublicationReceipt,
    opts?: { expectedHost?: string | null; expectedSha256?: string | null; requiredArtifactType?: PublicationArtifactType | null },
  ): Promise<ChannelValidationResult>;
  normalizeReceipt(evidence: RawPublishEvidence, manifest: PublicationExecutionManifest): NormalizedReceiptInput;
}

const LIVE_EXECUTION_ENV_FLAG = "PUBLICATION_OPERATOR_ENABLE_LIVE_EXECUTE";
const CREDENTIAL_ENV_VAR_BY_DESTINATION: Partial<Record<PlacementDestination, string>> = {
  // No destination has a defined credential env var yet -- none of these
  // integrations exist. Left empty deliberately rather than naming a var
  // that nothing reads, so a future release adds both the name and the
  // real check together.
};

/**
 * Always false in this release. See module docstring: this does not gate a
 * live-call implementation because none exists to gate. Exported so a test
 * can assert it stays false under every input, including a forged env var.
 */
export function isLiveExecutionEnabled(destination: PlacementDestination): boolean {
  const flagSet = process.env[LIVE_EXECUTION_ENV_FLAG] === "true";
  const credentialVar = CREDENTIAL_ENV_VAR_BY_DESTINATION[destination];
  const credentialPresent = Boolean(credentialVar && process.env[credentialVar]);
  void flagSet;
  void credentialPresent;
  return false;
}

async function structurallyDisabledExecute(manifest: PublicationExecutionManifest): Promise<ExecuteResult> {
  void isLiveExecutionEnabled(manifest.destination);
  return {
    ok: false,
    error:
      "execute is structurally disabled in this release: no live-execution code path exists for any destination (website deploy, LinkedIn, or Google Business Profile)",
  };
}

function defaultNormalizeReceipt(
  evidence: RawPublishEvidence,
  manifest: PublicationExecutionManifest,
): NormalizedReceiptInput {
  return {
    destination: manifest.destination,
    publicUrl: evidence.publicUrl ?? null,
    externalPostId: evidence.externalPostId ?? null,
    publishedAt: evidence.publishedAt ?? new Date().toISOString(),
  };
}

function defaultReconcile(
  destination: PlacementDestination,
  receipt: PublicationReceipt,
  opts?: { expectedHost?: string | null; expectedSha256?: string | null; requiredArtifactType?: PublicationArtifactType | null },
) {
  return validateReceiptForDestination(destination, receipt, opts);
}

function redactedPayloadPreview(manifest: PublicationExecutionManifest): Record<string, unknown> {
  return {
    titleLength: manifest.title?.length ?? 0,
    bodyLength: manifest.destinationMetadata.bodyLength ?? null,
    locale: manifest.locale,
    hasCta: Boolean(manifest.ctaTargetPath),
    assetCount: manifest.assets.length,
    trackedUrl: manifest.trackedUrl,
    idempotencyKey: manifest.idempotencyKey,
  };
}

// ─── Website ────────────────────────────────────────────────────────────

const websiteAdapter: PublicationAdapter = {
  destinations: ["firm_website"],
  validateConfiguration(manifest) {
    if (manifest.destinationAccount.configured) {
      return { configured: true, issues: [], requiredConfigNames: [] };
    }
    return {
      configured: false,
      issues: [manifest.destinationAccount.note],
      requiredConfigNames: [],
    };
  },
  preflight(manifest) {
    return evaluatePublicationPreflightStatus(manifest);
  },
  renderDryRun(manifest) {
    return {
      method: "MANUAL",
      endpoint: "manual: operator deploys the firm's own website repository (e.g. `vercel --prod`) and records a receipt",
      summary: `Would publish "${manifest.title ?? "(untitled)"}" to ${manifest.canonicalUrl ?? "(no canonical URL resolved)"}. No automated deploy integration exists; this is always an operator action outside this system.`,
      payloadPreview: { ...redactedPayloadPreview(manifest), canonicalUrl: manifest.canonicalUrl },
      requiresManualAction: true,
    };
  },
  execute: structurallyDisabledExecute,
  reconcile: (receipt, opts) => defaultReconcile("firm_website", receipt, opts),
  normalizeReceipt: defaultNormalizeReceipt,
};

// ─── LinkedIn ───────────────────────────────────────────────────────────

function linkedInEndpointLabel(destination: PlacementDestination): string {
  if (destination === "linkedin_article") return "LinkedIn Articles (Pulse long-form)";
  if (destination === "linkedin_company_page") return "LinkedIn Company Page feed post";
  return "LinkedIn personal feed post";
}

const linkedInAdapter: PublicationAdapter = {
  destinations: ["linkedin_article", "linkedin_post", "linkedin_company_page"],
  validateConfiguration() {
    return {
      configured: false,
      issues: ["no LinkedIn account, company page, or API integration is configured anywhere in this system"],
      requiredConfigNames: ["LINKEDIN_CLIENT_ID", "LINKEDIN_CLIENT_SECRET", "LINKEDIN_ACCESS_TOKEN"],
    };
  },
  preflight(manifest) {
    return evaluatePublicationPreflightStatus(manifest);
  },
  renderDryRun(manifest) {
    return {
      method: "POST",
      endpoint: `illustrative only, no live client exists: POST https://api.linkedin.com/rest/posts (${linkedInEndpointLabel(manifest.destination)})`,
      summary: `Would post to ${linkedInEndpointLabel(manifest.destination)}. No authorized LinkedIn integration exists; posting is always manual (operator copies the approved copy into LinkedIn) and this system only records the resulting receipt.`,
      payloadPreview: redactedPayloadPreview(manifest),
      requiresManualAction: true,
    };
  },
  execute: structurallyDisabledExecute,
  reconcile: (receipt, opts) => defaultReconcile(
    receipt.destination === "linkedin_article" || receipt.destination === "linkedin_post" || receipt.destination === "linkedin_company_page"
      ? receipt.destination
      : "linkedin_post",
    receipt,
    opts,
  ),
  normalizeReceipt: defaultNormalizeReceipt,
};

// ─── Google Business Profile ───────────────────────────────────────────

const gbpAdapter: PublicationAdapter = {
  destinations: ["google_business_profile"],
  validateConfiguration() {
    return {
      configured: false,
      issues: ["no Google Business Profile location or API integration is configured anywhere in this system"],
      requiredConfigNames: ["GOOGLE_BUSINESS_PROFILE_CLIENT_ID", "GOOGLE_BUSINESS_PROFILE_CLIENT_SECRET", "GOOGLE_BUSINESS_PROFILE_LOCATION_ID"],
    };
  },
  preflight(manifest) {
    return evaluatePublicationPreflightStatus(manifest);
  },
  renderDryRun(manifest) {
    return {
      method: "POST",
      endpoint: "illustrative only, no live client exists: POST https://mybusiness.googleapis.com/v4/accounts/{accountId}/locations/{locationId}/localPosts",
      summary: `Would post to the firm's Google Business Profile location. No authorized GBP integration exists; posting is always manual and this system only records the resulting receipt.`,
      payloadPreview: redactedPayloadPreview(manifest),
      requiresManualAction: true,
    };
  },
  execute: structurallyDisabledExecute,
  reconcile: (receipt, opts) => defaultReconcile("google_business_profile", receipt, opts),
  normalizeReceipt: defaultNormalizeReceipt,
};

// ─── Email delivery ─────────────────────────────────────────────────────

const emailAdapter: PublicationAdapter = {
  destinations: ["email_delivery"],
  validateConfiguration() {
    return {
      configured: false,
      issues: ["no email delivery destination configuration exists for placements in this system"],
      requiredConfigNames: [],
    };
  },
  preflight(manifest) {
    return evaluatePublicationPreflightStatus(manifest);
  },
  renderDryRun(manifest) {
    return {
      method: "MANUAL",
      endpoint: "manual: operator sends the approved content via the firm's own email channel",
      summary: "Would send as an email delivery. No automated send integration exists for this destination.",
      payloadPreview: redactedPayloadPreview(manifest),
      requiresManualAction: true,
    };
  },
  execute: structurallyDisabledExecute,
  reconcile: (receipt, opts) => defaultReconcile("email_delivery", receipt, opts),
  normalizeReceipt: defaultNormalizeReceipt,
};

const ADAPTERS: readonly PublicationAdapter[] = [websiteAdapter, linkedInAdapter, gbpAdapter, emailAdapter];

export function getPublicationAdapter(destination: PlacementDestination): PublicationAdapter {
  const adapter = ADAPTERS.find((a) => a.destinations.includes(destination));
  if (!adapter) throw new Error(`no publication adapter registered for destination: ${destination}`);
  return adapter;
}

export { isManuallyVerifiableDestination };
