-- CaseLoad Select — Locked Schema
-- Last updated: 2026-05-05 (Screen 2.0 persistence: screened_leads table)
--
-- This file is the authoritative schema reference. It documents the current
-- state of the Supabase database. All future schema changes must:
--   1. Add a dated migration file to supabase/migrations/
--   2. Update this file to reflect the new state
--   3. Be applied manually via Supabase SQL Editor
--
-- Do NOT run this file against a live database — it will fail on existing tables.
-- It is a reference document, not an executable migration.

-- ─────────────────────────────────────────────────────────────────────────────
-- law_firm_clients
-- ─────────────────────────────────────────────────────────────────────────────
-- id            uuid PRIMARY KEY DEFAULT gen_random_uuid()
-- name          text NOT NULL
-- location      text
-- status        text DEFAULT 'active'
-- contact_email text
-- created_at    timestamptz DEFAULT now()

-- ─────────────────────────────────────────────────────────────────────────────
-- leads
-- ─────────────────────────────────────────────────────────────────────────────
-- id                     uuid PRIMARY KEY DEFAULT gen_random_uuid()
-- law_firm_id            uuid REFERENCES law_firm_clients(id)
-- name                   text
-- email                  text
-- phone                  text
-- case_type              text
-- estimated_value        numeric
-- language               text
-- description            text
-- stage                  text DEFAULT 'new_lead'
-- score                  integer
-- fit_score              integer
-- value_score            integer
-- cpi_score              integer
-- band                   text
-- referral_source        text
-- urgency                text
-- timeline               text
-- city                   text
-- location               text
-- lead_state             text
-- source                 text
-- referral               text
-- multi_practice         boolean
-- geo_score              integer
-- contactability_score   integer
-- legitimacy_score       integer
-- complexity_score       integer
-- urgency_score          integer
-- strategic_score        integer
-- fee_score              integer
-- priority_index         integer
-- priority_band          text
-- persistence_step         integer
-- persistence_started_at   timestamptz
-- persistence_last_action_at timestamptz
-- persistence_status       text
-- persistence_exit_reason  text
-- no_show_step             integer
-- no_show_started_at       timestamptz
-- no_show_last_action_at   timestamptz
-- no_show_status           text
-- stalled_step             integer
-- stalled_started_at       timestamptz
-- stalled_last_action_at   timestamptz
-- stalled_status           text
-- created_at             timestamptz DEFAULT now()
-- updated_at             timestamptz DEFAULT now()

-- ─────────────────────────────────────────────────────────────────────────────
-- intake_firms
-- ─────────────────────────────────────────────────────────────────────────────
-- id                  uuid PRIMARY KEY DEFAULT gen_random_uuid()
-- name                text NOT NULL
-- practice_areas      jsonb        -- array of { id, label, tier }
-- question_sets       jsonb        -- map of practice_area_id -> { questions[] }
-- geographic_config   jsonb        -- { primary_region, secondary_regions, excluded }
-- branding            jsonb        -- { logo_url, primary_color, firm_name }
-- ghl_webhook_url     text
-- ghl_api_key         text
-- resend_sender       text
-- custom_instructions text
-- created_at          timestamptz DEFAULT now()
-- updated_at          timestamptz DEFAULT now()

-- ─────────────────────────────────────────────────────────────────────────────
-- intake_sessions
-- ─────────────────────────────────────────────────────────────────────────────
-- id                  uuid PRIMARY KEY DEFAULT gen_random_uuid()
-- firm_id             uuid REFERENCES intake_firms(id)
-- channel             text         -- 'widget' | 'whatsapp' | 'chat' | 'email' | 'phone'
-- status              text         -- 'in_progress' | 'complete' | 'expired'
-- conversation        jsonb        -- array of { role, content } GPT message history
-- scoring             jsonb        -- CpiBreakdown + _confirmed sub-key for confirmed answers
--                                  -- scoring._confirmed = { [questionId]: value } (S7 design)
-- contact             jsonb        -- { first_name, last_name, email, phone }
-- extracted_entities  jsonb        -- GPT-inferred key-value pairs (scoring inference only)
-- practice_area       text
-- band                text         -- 'A' | 'B' | 'C' | 'D' | 'E'
-- otp_code            text
-- otp_expires_at      timestamptz
-- otp_verified        boolean DEFAULT false
-- crm_synced          boolean DEFAULT false
-- situation_summary   text
-- created_at          timestamptz DEFAULT now()
-- updated_at          timestamptz DEFAULT now()

-- ─────────────────────────────────────────────────────────────────────────────
-- sequence_templates
-- ─────────────────────────────────────────────────────────────────────────────
-- id            uuid PRIMARY KEY DEFAULT gen_random_uuid()
-- name          text NOT NULL
-- trigger_event text         -- new_lead | no_engagement | client_won | no_show | stalled_retainer
--                            -- incomplete_intake | spoke_no_book | consulted_no_sign
--                            -- retainer_awaiting | consultation_scheduled | review_request
--                            -- matter_active | re_engagement | relationship_milestone | long_term_nurture
-- description   text
-- is_active     boolean DEFAULT true
-- created_at    timestamptz DEFAULT now()
-- updated_at    timestamptz DEFAULT now()

-- ─────────────────────────────────────────────────────────────────────────────
-- sequence_steps
-- ─────────────────────────────────────────────────────────────────────────────
-- id              uuid PRIMARY KEY DEFAULT gen_random_uuid()
-- sequence_id     uuid REFERENCES sequence_templates(id)
-- step_number     integer
-- delay_hours     integer
-- channels        jsonb   -- array of channel config objects
-- is_active       boolean DEFAULT true
-- created_at      timestamptz DEFAULT now()
-- updated_at      timestamptz DEFAULT now()

-- ─────────────────────────────────────────────────────────────────────────────
-- email_sequences
-- ─────────────────────────────────────────────────────────────────────────────
-- id               uuid PRIMARY KEY DEFAULT gen_random_uuid()
-- lead_id          uuid REFERENCES leads(id)
-- sequence_step_id uuid REFERENCES sequence_steps(id)
-- step_number      integer
-- status           text   -- 'pending' | 'sent' | 'failed' | 'skipped'
-- scheduled_at     timestamptz
-- sent_at          timestamptz

-- ─────────────────────────────────────────────────────────────────────────────
-- review_requests
-- ─────────────────────────────────────────────────────────────────────────────
-- id           uuid PRIMARY KEY DEFAULT gen_random_uuid()
-- lead_id      uuid REFERENCES leads(id)
-- law_firm_id  uuid REFERENCES law_firm_clients(id)
-- status       text   -- 'pending' | 'sent' | 'opened' | 'completed'
-- created_at   timestamptz DEFAULT now()
-- sent_at      timestamptz

-- ─────────────────────────────────────────────────────────────────────────────
-- intake_firms (additions from S8, S9)
-- ─────────────────────────────────────────────────────────────────────────────
-- clio_config   jsonb   -- { access_token, refresh_token, expires_at } (migration: 20260414_portal_clio.sql)
-- custom_domain text UNIQUE  -- e.g. intake.sakurabalaw.ca   (migration: 20260414_custom_domain.sql)
-- firm_name     text    -- canonical name used in portal + sequence interpolation
-- geo_config    jsonb   -- geographic boundaries (primary_region, secondary, excluded)
-- scoring_weights jsonb -- custom CPI weight overrides per firm

-- ─────────────────────────────────────────────────────────────────────────────
-- conflict_register                             (migration: 20260414_conflict_check.sql)
-- ─────────────────────────────────────────────────────────────────────────────
-- id              uuid PRIMARY KEY DEFAULT gen_random_uuid()
-- law_firm_id     uuid REFERENCES law_firm_clients(id) ON DELETE CASCADE
-- client_name     text NOT NULL
-- opposing_party  text
-- matter_type     text
-- email           text
-- phone           text
-- source          text   -- 'caseload_select' | 'csv_import' | 'clio_sync'
-- clio_matter_id  text
-- created_at      timestamptz DEFAULT now()
-- INDEX: (law_firm_id), (law_firm_id, email), (law_firm_id, phone)

-- ─────────────────────────────────────────────────────────────────────────────
-- conflict_checks                               (migration: 20260414_conflict_check.sql)
-- ─────────────────────────────────────────────────────────────────────────────
-- id              uuid PRIMARY KEY DEFAULT gen_random_uuid()
-- lead_id         uuid REFERENCES leads(id) ON DELETE CASCADE
-- law_firm_id     uuid REFERENCES law_firm_clients(id) ON DELETE CASCADE
-- result          text   -- 'clear' | 'potential_conflict' | 'confirmed_conflict'
-- matches         jsonb  -- array of ConflictMatch objects
-- checked_via     text   -- 'clio' | 'register' | 'none'
-- checked_at      timestamptz DEFAULT now()
-- override_reason text   -- set when potential_conflict is manually overridden
-- reviewed_by     text
-- INDEX: (lead_id, checked_at DESC)

-- ─────────────────────────────────────────────────────────────────────────────
-- matter_routing                                (migration: 20260418_matter_routing.sql)
-- ─────────────────────────────────────────────────────────────────────────────
-- Per-firm mapping of practice sub-type → GHL pipeline/stage + staff assignment.
-- Applied at finalize time in /api/screen when sendToGHL() is called.
-- id                   uuid PRIMARY KEY DEFAULT gen_random_uuid()
-- firm_id              uuid REFERENCES intake_firms(id) ON DELETE CASCADE
-- sub_type             text NOT NULL               -- e.g. "emp_dismissal", "pi_slip_fall"
-- ghl_pipeline_id      text                        -- overrides default pipeline
-- ghl_stage            text                        -- overrides default stage
-- assigned_staff_id    text                        -- GHL user ID
-- assigned_staff_email text                        -- fallback staff routing
-- created_at           timestamptz DEFAULT now()
-- updated_at           timestamptz DEFAULT now()   -- maintained by trigger
-- UNIQUE (firm_id, sub_type)
-- INDEX: (firm_id)

-- ─────────────────────────────────────────────────────────────────────────────
-- intake-attachments Storage Bucket             (migration: 20260418_storage_intake_attachments.sql)
-- ─────────────────────────────────────────────────────────────────────────────
-- Supabase Storage bucket for Round 3 file upload answers.
-- Bucket: intake-attachments  (public = true, 10 MB limit)
-- Allowed MIME: image/jpeg, image/png, image/webp, image/gif, application/pdf, text/plain
-- Path convention: {firmId}/{sessionId}/{timestamp}-{sanitizedFilename}
-- RLS policies:
--   intake_attachments_anon_insert — anon role can INSERT (server-side OTP gate enforces auth)
--   intake_attachments_public_read — anyone can SELECT (public bucket for getPublicUrl())

-- ─────────────────────────────────────────────────────────────────────────────
-- intake_sessions additions                    (migrations: 20260417_round3_memo.sql)
-- ─────────────────────────────────────────────────────────────────────────────
-- practice_sub_type    text        -- matched sub-type (e.g. "emp_dismissal")
-- round3_answers       jsonb       -- { [questionId]: value } Round 3 answers incl. file URLs
-- round3_started_at    timestamptz
-- round3_completed_at  timestamptz
-- memo_text            text        -- AI-generated case memo
-- memo_generated_at    timestamptz
-- scoring._quality     jsonb key   -- IntakeQualityReport persisted inside scoring JSONB on memo gen

-- ─────────────────────────────────────────────────────────────────────────────
-- sequence_steps.channels additions
-- ─────────────────────────────────────────────────────────────────────────────
-- channels.condition   jsonb (optional) -- StepCondition: { operator: "and"|"or", rules: ConditionRule[] }
--   ConditionRule: { slot_id: string, op: "eq"|"neq"|"in"|"nin"|"exists"|"not_exists", value?: string|string[] }
--   Evaluated at send time against merged (extracted_entities + scoring._confirmed) from intake_sessions.
--   Step is skipped when condition evaluates to false.

-- ─────────────────────────────────────────────────────────────────────────────
-- ─────────────────────────────────────────────────────────────────────────────
-- Custom domain routing — S9                  (src/middleware.ts)
-- ─────────────────────────────────────────────────────────────────────────────
-- intake_firms.custom_domain (text UNIQUE) maps a hostname to a firm.
-- Edge middleware (src/middleware.ts) intercepts every request:
--   Non-app hostname → Supabase REST lookup → firmId resolved
--   Rewrites:  /               → /widget/[firmId]
--              /portal/*       → /portal/[firmId]/*
--              /portal/login   → /portal/login  (pass-through)
--              /api/*          → /api/*          (pass-through)
-- Vercel domain registration: /api/admin/domain  (POST/DELETE)
-- Admin UI: /domains page in operator app
-- Env vars required: VERCEL_API_TOKEN, VERCEL_PROJECT_ID, VERCEL_TEAM_ID (optional)

-- leads additions                              (migration: 20260415_leads_intake_session_id.sql)
-- ─────────────────────────────────────────────────────────────────────────────
-- intake_session_id    uuid REFERENCES intake_sessions(id)  -- link to originating intake session
--   Populated by promoteToLead() in /api/otp/verify when lead is created from intake session.

-- ─────────────────────────────────────────────────────────────────────────────
-- screened_leads                               (migration: 20260505_screened_leads.sql)
-- ─────────────────────────────────────────────────────────────────────────────
-- CaseLoad Screen 2.0 persistence target. NEW table, not an extension of leads
-- (rationale in the migration header). Populated by /api/intake-v2 when the
-- Vite-based screen at https://caseload-screen-v2.vercel.app submits.
-- The lawyer portal queue and brief view read from this table.
--
-- id                  uuid PRIMARY KEY DEFAULT gen_random_uuid()
-- lead_id             text UNIQUE NOT NULL                    -- L-YYYY-MM-DD-XXX
-- firm_id             uuid REFERENCES intake_firms(id) ON DELETE CASCADE
-- screen_version      integer NOT NULL DEFAULT 2
-- status              text NOT NULL DEFAULT 'triaging'        -- triaging | taken | passed | declined
-- status_changed_at   timestamptz NOT NULL DEFAULT now()
-- status_changed_by   text                                    -- lawyer email | 'system' | 'system:backstop'
-- status_note         text                                    -- optional Pass note from lawyer
-- brief_json          jsonb NOT NULL                          -- LawyerReport object
-- brief_html          text NOT NULL                           -- pre-rendered moment-in-time snapshot
-- slot_answers        jsonb NOT NULL                          -- raw EngineState slots/meta/evidence
-- band                text                                    -- 'A' | 'B' | 'C' | NULL
-- matter_type         text NOT NULL                           -- one of 16 in-scope or 'out_of_scope'
-- practice_area       text NOT NULL
-- value_score         integer (0-10)
-- complexity_score    integer (0-10)                          -- engine-internal, displayed as Simplicity (10 - complexity)
-- urgency_score       integer (0-10)
-- readiness_score     integer (0-10)
-- readiness_answered  boolean NOT NULL DEFAULT false
-- whale_nurture       boolean NOT NULL DEFAULT false          -- value_score >= 7 AND readiness_score <= 4
-- band_c_subtrack     text                                    -- fast_transaction | window_shopper | wrong_fit | NULL
-- decision_deadline   timestamptz NOT NULL                    -- 48h / 24h (urgency >= 6) / 12h (urgency >= 8)
-- contact_name        text
-- contact_email       text
-- contact_phone       text
-- submitted_at        timestamptz NOT NULL DEFAULT now()
-- created_at          timestamptz NOT NULL DEFAULT now()
-- updated_at          timestamptz NOT NULL DEFAULT now()
--
-- Indexes (queue + audit, from base migration):
--   idx_screened_leads_queue           (firm_id, status, band, decision_deadline)
--   idx_screened_leads_lead_id         (lead_id)
--   idx_screened_leads_status_changed  (firm_id, status_changed_at DESC)
--   idx_screened_leads_deadline_active (decision_deadline) WHERE status = 'triaging'
--
-- Indexes (v5 dashboard, from 20260505_screened_leads_dashboard_indexes.sql):
--   idx_screened_leads_created         (created_at DESC)             -- cross-firm time windows
--   idx_screened_leads_firm_created    (firm_id, created_at DESC)    -- per-firm time windows
--   idx_screened_leads_status_band     (status, band)                -- cross-firm rollups

-- ─────────────────────────────────────────────────────────────────────────────
-- firm_decline_templates                       (migration: 20260505_firm_decline_templates.sql)
-- ─────────────────────────────────────────────────────────────────────────────
-- Three-layer decline copy storage for the lawyer triage Pass action and the
-- two auto-decline paths (OOS at intake, backstop on deadline expiry).
-- The per-lead override (layer 1) lives on screened_leads.status_note;
-- this table holds layers 2 and 3 (per-PA variant and firm default).
--
-- id              uuid PRIMARY KEY DEFAULT gen_random_uuid()
-- firm_id         uuid NOT NULL REFERENCES intake_firms(id) ON DELETE CASCADE
-- practice_area   text                        -- NULL = firm default; non-null = per-area variant
-- subject         text                        -- email subject; falls back to "Re: your inquiry"
-- body            text NOT NULL               -- email body (plain or simple inline HTML)
-- created_at      timestamptz NOT NULL DEFAULT now()
-- updated_at      timestamptz NOT NULL DEFAULT now()
--
-- Unique:
--   uniq_firm_decline_templates_pair (firm_id, practice_area) NULLS NOT DISTINCT
--     — enforces one default per firm and one variant per (firm, area) pair
--
-- Resolution at decline time (lib/decline-resolver.ts):
--   1. screened_leads.status_note (per-lead override)
--   2. firm_decline_templates where firm_id + practice_area
--   3. firm_decline_templates where firm_id + practice_area IS NULL
--   4. hard-coded system fallback in lib/decline-resolver.ts
--
-- RLS forced; service_role only.
--
-- RLS: enabled and forced. service_role only (no anon, no authenticated path).

-- ─────────────────────────────────────────────────────────────────────────────
-- retainer_agreements                          (migration: 20260414_retainer_agreements.sql)
-- ─────────────────────────────────────────────────────────────────────────────
-- Triggered automatically for Band A/B leads after Round 3 completion.
-- DocuGenerate fills PDF template; DocuSeal delivers for e-signature.
-- id                         uuid PRIMARY KEY DEFAULT gen_random_uuid()
-- session_id                 uuid REFERENCES intake_sessions(id) ON DELETE SET NULL  (FK: 20260418_retainer_fks.sql)
-- firm_id                    uuid REFERENCES intake_firms(id) ON DELETE CASCADE      (FK: 20260418_retainer_fks.sql)
-- contact_name               text
-- contact_email              text
-- contact_phone              text
-- docugenerate_document_id   text
-- docugenerate_document_url  text
-- docuseal_submission_id     text UNIQUE
-- docuseal_signing_url       text
-- status                     text  -- 'pending' | 'generated' | 'sent' | 'viewed' | 'signed' | 'voided'
-- generated_at / sent_at / viewed_at / signed_at / voided_at  timestamptz
-- created_at / updated_at    timestamptz
-- Env vars required: DOCUGENERATE_API_KEY, DOCUGENERATE_TEMPLATE_ID,
--                    DOCUSEAL_API_KEY, DOCUSEAL_TEMPLATE_ID, DOCUSEAL_WEBHOOK_SECRET
