export const WELCOME_COPY = {
  heading: "Define your desired client",
  description: "A firm can have a full calendar and still be building the wrong practice. This guided exercise helps you choose the client situation and matter you would want more of, explain why it suits your firm, and set a direction you can use in marketing.",
  time: "Plan for about 10 minutes for a first draft. Comparing two types of work or adding detail will take longer.",
  process: "Six guided sections take you from the practice you want to build to the client situation, matter, value, fit signals, opportunity and measure of success. Choose from examples, write your own answer, or mark something as not yet known.",
  preparation: "Think about work you would gladly handle again, what the team put into it, and what made it worthwhile. Records are not required. You can share estimates or leave figures unknown.",
  outcome: "A Desired Client Blueprint that defines the client, specific legal work and practical benefit; explains why the firm wants the work; keeps constraints and evidence gaps visible; and gives a separate progress measure, target and review period. Review and correct the draft before using it in marketing.",
  supporting: "One type of work at a time. No account or email required.",
  privacy: "Describe patterns of work, not individual clients. Do not enter names, identifying details or confidential information.",
  aiDisclosure: "AI can turn your answers into a Desired Client Blueprint. If AI is unavailable, you can continue with a clearly labelled structured draft, and your answers remain saved.",
  legacyBriefReplaced: "Your answers are saved. Review them below to create your Desired Client Blueprint.",
  draftNotice: "Your draft is saved in this browser for seven days after your last change. You can clear it at any time.",
  startButton: "Define my desired client",
} as const;
export const STORAGE_COPY = {
  migrated: "Your saved answers are here. Review the new sections and complete any required choices before creating an updated blueprint.",
  unavailable: "This browser could not save your progress. You can still finish and download your answers.",
  expired: "Your saved draft expired after seven days without changes. Start a new draft to continue.",
  invalid: "Your saved draft could not be restored. Start a new draft to continue.",
  briefNeedsRefresh: "A previous blueprint could not be reopened after a version update. Your answers are still saved. Create a new blueprint from them, then review it before use.",
  resume: "Continue my saved draft",
  new: "Start a new draft",
  clearSaved: "Clear saved draft",
  replaceConfirm: "Replace the draft saved in this browser?",
  clearConfirm: "Clear the draft and brief saved in this browser?",
  keep: "Keep draft",
  replace: "Replace draft",
  clear: "Clear draft",
  downloadBeforeReplace: "Download your answers before replacing the saved draft.",
} as const;
export const COMMON_COPY = {
  back: "Back",
  continue: "Continue",
  requiredSingle: "Choose an answer, including “Not sure yet,” to continue.",
  requiredMulti: "Choose an answer, including “Not sure yet,” to continue.",
  maxSelection: (max: number) => `Choose up to ${max}.`,
  edit: "Change",
  comparisonAction: "Compare two types of work",
  previewLabel: "Your profile so far",
  previewBadge: "Draft to refine",
  previewRouteNew: "This is a direction the firm is building toward.",
  previewRouteTest: "This is a direction to test.",
  previewWorkMissing: "Type of work still to specify",
  previewRoleMissing: "Client role still to specify",
  previewGoalMissing: "Client outcome still to establish",
  aiUnavailable: "AI could not create the blueprint just now. Your answers are still here. Retry or continue with a clearly labelled structured draft.",
  aiInvalid: "AI did not return a usable blueprint. Your answers are still here. Retry or continue with a clearly labelled structured draft.",
  structuredInvalid: "The structured blueprint could not be assembled from these answers. Your answers are still here. Review the matter details and try again.",
  briefChanged: "Your answers changed. Create the blueprint again so it reflects the updated direction.",
  workChanged: "Your selected work changed. Review the client situation, value, fit, opportunity and repeatability sections again.",
} as const;
export const REVIEW_COPY = {
  heading: "Review your direction",
  note: "Check the six parts of your profile. “Not sure yet” is a valid answer; the blueprint will identify what still needs evidence.",
  prepareAI: "Create my Desired Client Blueprint",
  creatingAI: "Connecting your answers into a client-and-matter profile…",
  tryAgain: "Try again",
  loadingNote: "The tool is checking how your choices fit together and where the evidence is still open.",
  answerDownload: "Download my answers",
  answerDownloadAgain: "Download my answers",
  draftFooter: "Use this profile to guide marketing priorities. A lawyer reviews each enquiry and decides whether to accept an individual matter.",
  separateDrafts: "Drafts may be separate in the embedded tool and its own window.",
} as const;
export const BRIEF_COPY = {
  title: "Desired Client Blueprint",
  profileTitle: "Desired Client Blueprint",
  summaryTitle: "Answers and sources",
  reviewed: "I have reviewed this wording and the proposed inquiry checks.",
  reviewedStatus: "Wording reviewed",
  unreviewedExport: "Working draft, not yet reviewed",
  reviewedExport: "Wording reviewed",
  editAnswers: "Change answers",
  copy: "Copy profile",
  copied: "Profile copied",
  copyFailure: "The profile could not be copied automatically.",
  selectAndCopy: "Select and copy the profile",
  download: "Download HTML",
  pdf: "Print profile",
  print: "Print profile",
  another: "Create another profile",
  clear: "Clear this draft",
  why: "Why this is here",
  preparedAI: "AI-assisted working draft",
  preparedStructured: "Basic structured draft from your answers",
  unresolved: "Still to check",
} as const;
export const STAGE_SUMMARY_LABELS = [
  "Practice", "Client and matter", "Value", "Fit", "Opportunity", "Repeatability",
] as const;
export const PRIVACY_FIELD_COPY = "Describe patterns of work, not individual clients. Do not enter names, identifying details or confidential information.";
