export const WELCOME_COPY = {
  heading: "Define the clients and matters you want more of",
  description: "This guided tool helps you describe one kind of legal work your firm wants to attract, the clients who seek it, and the conditions that make it a good fit. It turns your answers into a working Desired Client Brief for your marketing.",
  time: "Allow about 10 minutes. You can pause and return to this browser draft.",
  process: "Work through six short sections. Choose the answers that fit, or write your own. You can review and change everything before creating the brief.",
  preparation: "Have one type of work in mind. It helps to know when clients seek help, what they hope to achieve, why the work suits your firm, and whether your team can take on more. Estimates and unknowns are fine.",
  outcome: "Your brief summarizes the client and matter pattern, reasons to pursue it, delivery limits, open questions, and a marketing starting point. You can copy, download, or print it.",
  supporting: "One type of work at a time. No account or email required.",
  privacy: "Describe patterns of work, not individual clients. Do not enter names, identifying details or confidential information.",
  aiDisclosure: "With AI assistance, your answers, including any optional commercial ranges, are sent to Google Gemini when you ask it to prepare your brief. Without AI, a structured brief is created in this browser.",
  draftNotice: "Your draft is saved in this browser for seven days after your last change. You can clear it at any time.",
  aiButton: "Begin with AI assistance",
  structuredButton: "Begin without AI",
} as const;
export const STORAGE_COPY = {
  unavailable: "This browser could not save your progress. You can still finish and download your brief.",
  expired: "Your saved draft expired after seven days without changes. Start a new draft to continue.",
  invalid: "Your saved draft could not be restored. Start a new draft to continue.",
  resumeAI: "Resume with AI assistance",
  resumeStructured: "Resume without AI",
  new: "Start a new draft",
  clearSaved: "Clear saved draft",
  replaceConfirm: "Replace the draft saved in this browser?",
  clearConfirm: "Clear the draft and brief saved in this browser?",
  keep: "Keep draft",
  replace: "Replace draft",
  clear: "Clear draft",
  downloadBeforeReplace: "Download this brief before replacing the saved draft.",
} as const;
export const COMMON_COPY = {
  back: "Back",
  continue: "Continue",
  requiredSingle: "Choose an answer to continue.",
  requiredMulti: "Choose at least one answer to continue.",
  maxSelection: (max: number) => `Choose up to ${max}.`,
  edit: "Change",
  comparisonAction: "Help me compare two",
  previewLabel: "Your starting point",
  previewBadge: "Draft to refine",
  previewRouteNew: "This is a direction you are building toward.",
  previewRouteTest: "This is a direction to test.",
  previewWorkMissing: "Type of work still to specify",
  previewRoleMissing: "Client role still to specify",
  previewGoalMissing: "Client goal still to establish",
  aiUnavailable: "AI assistance is unavailable. Your structured brief is ready.",
  briefChanged: "Your answers changed. Update the brief to include them.",
} as const;
export const REVIEW_COPY = {
  heading: "Does this describe the work you want more of?",
  note: "Check your answers together before creating the brief. You can change any section so the final wording reflects the work you actually want to pursue.",
  prepareAI: "Prepare my brief with AI",
  createStructured: "Create my brief",
  useAI: "Use AI assistance",
  agreePrepare: "Agree and prepare with AI",
  createWithoutAI: "Create without AI",
  draftFooter: "A working definition based on your answers. It guides marketing priorities; a lawyer decides whether to accept an individual matter.",
  separateDrafts: "Drafts may be separate in the embedded tool and its own window.",
} as const;
export const BRIEF_COPY = {
  title: "Your Desired Client Brief",
  reviewed: "I have reviewed this wording",
  reviewedStatus: "Wording reviewed by you",
  unreviewedExport: "Working draft, not yet reviewed",
  reviewedExport: "Working draft, wording reviewed by you",
  editAnswers: "Edit my answers",
  copy: "Copy brief",
  copied: "Brief copied",
  copyFailure: "The brief could not be copied automatically.",
  selectAndCopy: "Select and copy the brief",
  download: "Download Markdown",
  print: "Print / save PDF",
  another: "Create another profile",
  clear: "Clear this draft",
  why: "Why this is here",
  preparedAI: "Prepared with AI assistance from your answers.",
  preparedStructured: "Structured summary of your answers.",
  unresolved: "Still to check",
} as const;
export const STAGE_SUMMARY_LABELS = [
  "Client and situation", "Client's goal", "Why the work appeals", "Delivery and capacity", "Direction and evidence",
] as const;
export const PRIVACY_FIELD_COPY = "Describe patterns of work, not individual clients. Do not enter names, identifying details or confidential information.";
