import { buildBlueprintViewModel } from "./blueprint";
import { getSourceDetails } from "./sources";
import type { AnswerReferencePath, DesiredClientAnswers, SavedBrief } from "./types";

const stamp=(d:Date)=>d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0");
function view(saved:SavedBrief,a:DesiredClientAnswers){return buildBlueprintViewModel(saved.brief,a,{mode:saved.mode,generatedAt:saved.generatedAt,wordingReviewed:saved.wordingReviewed,openClarificationCode:saved.openClarificationCode});}
function profile(saved:SavedBrief,a:DesiredClientAnswers){
 const m=view(saved,a),b=m.brief;
 return [m.title,m.status+(m.provisional?" · Provisional direction":""),m.modeLabel+" · "+m.date,"","DESIRED CLIENT PORTRAIT",b.portrait.text,"","CLIENT CONTEXT","Client: "+m.context.client,"Starting point: "+m.context.startingPoint,"Work to attract: "+m.context.work,"","CLIENT NEED",b.client_need.text,"","FIRM VALUE",b.firm_value.text,"","MARKETING DIRECTION",b.marketing.message.text,b.marketing.content.text,b.marketing.next_step.text,"","STILL TO CONFIRM",...(m.stillToConfirm.length?m.stillToConfirm.map(n=>"- "+n):["- No unresolved questions identified."]),"","Evidence: "+(m.evidence.length?m.evidence.join("; "):"No client evidence selected")+". Based on information supplied by the firm.","Based on your answers. Marketing direction and proposed inquiry checks; a lawyer decides whether to accept an individual matter."].join("\n");
}
export function formatBriefText(saved:SavedBrief,a:DesiredClientAnswers):string{return profile(saved,a);}
export function formatBriefMarkdown(saved:SavedBrief,a:DesiredClientAnswers):string{
 const m=view(saved,a),b=m.brief;
 const rows=m.screens.rows.flatMap(row=>["### "+row.label,"",...row.questions.map(q=>"- **"+q.question+"**"+(q.desired_condition?" Desired condition: "+q.desired_condition:"")+" ("+q.target_status+"; human review)"),"- **Use:** "+row.use_summary,""]);
 const detail=m.sourceDetails.flatMap(slot=>["### "+slot.slot,"","- **"+slot.statement.kind+":** "+slot.statement.text,...slot.answers.map(x=>"- Source: "+x.question+": "+(x.answer??"Not supplied")),""]);
 const all=m.allAnswers.map(x=>"- **"+x.question+"**: "+x.answer);
 return ["# "+m.title,"","_"+m.status+(m.provisional?" · Provisional direction":"")+"_","","**"+m.modeLabel+"** · "+m.date,"","## Desired client portrait","",b.portrait.text,"","## Client context","","- Client: "+m.context.client,"- Starting point: "+m.context.startingPoint,"- Work to attract: "+m.context.work,"","## Client need","",b.client_need.text,"","## Firm value","",b.firm_value.text,"","## Marketing direction","","- **Message:** "+b.marketing.message.text,"- **Content:** "+b.marketing.content.text,"- **Next step:** "+b.marketing.next_step.text,"","## Proposed Screen questions","",...rows,"Missing information calls for clarification. These proposed checks do not activate scoring or decide whether to accept a matter.","","## Still to confirm","",...(m.allNotes.length?m.allNotes.map(n=>"- "+n):["- No unresolved questions identified."]),"","## Evidence","",...(m.evidence.length?m.evidence.map(e=>"- "+e):["- No client evidence selected."]),"Based on information supplied by the firm.","","## Answers and sources","",...all,"",...detail,"Based on your answers. Marketing direction and proposed inquiry checks; a lawyer decides whether to accept an individual matter.",""].join("\n");
}
export function createMarkdownDownload(saved:SavedBrief,a:DesiredClientAnswers,now=new Date()){return {filename:"desired-client-blueprint-supporting-detail-"+stamp(now)+".md",content:formatBriefMarkdown(saved,a),mimeType:"text/markdown;charset=utf-8"};}
export function createProfileDownload(saved:SavedBrief,a:DesiredClientAnswers,now=new Date()){return {filename:"desired-client-blueprint-"+stamp(now)+".txt",content:profile(saved,a),mimeType:"text/plain;charset=utf-8"};}
export function createAnswersDownload(answers:DesiredClientAnswers,now=new Date()){
 const paths:AnswerReferencePath[]=["focus.area","focus.work","focus.work_other","focus.service_area","focus.route","situation.trigger","write_ins.trigger","situation.timing","write_ins.timing","situation.role","situation.role_other","situation.contact","write_ins.contact","client.goals","write_ins.goals","client.concerns","write_ins.concerns","client.decision_needs","write_ins.decision_needs","value.reasons","write_ins.reasons","value.fee_effort","write_ins.fee_effort","value.collected_fee","value.team_hours","value.payment","delivery.conditions","write_ins.conditions","delivery.capacity","write_ins.capacity","delivery.limit","write_ins.limit","delivery.fit_signals","write_ins.fit_signals","direction.aim","write_ins.aim","direction.evidence","write_ins.evidence","direction.less","direction.less_note"];
 const rows=paths.flatMap(path=>{const source=getSourceDetails(path,answers);return source.answer===null?[]:["- **"+source.question+"**: "+source.answer];});
 return {filename:"desired-client-discovery-answers-"+stamp(now)+".md",mimeType:"text/markdown;charset=utf-8",content:["# Desired Client Discovery Answers","","_Answer record only. A Desired Client Blueprint has not been generated._","","Exported: "+stamp(now),"",...rows,"","This document records your answers. A Desired Client Blueprint has not been generated.",""].join("\n")};
}
