import type { SlotDefinition } from './types';

export const SLOT_REGISTRY: SlotDefinition[] = [

  // ─── CONTACT ──────────────────────────────────────────────────────────────

  {
    id: 'client_name',
    question: 'What is your name?',
    input_type: 'free_text',
    applies_to: ['business_setup_advisory', 'shareholder_dispute', 'unpaid_invoice', 'contract_dispute', 'vendor_supplier_dispute', 'corporate_money_control', 'corporate_general'],
    tier: 'contact',
    question_group: 'contact',
    resolves: 'contact',
    decision_value: 1,
    abstraction_level: 'concrete',
    required: true,
    priority: 100,
  },
  {
    id: 'client_phone',
    question: 'What is the best phone number to reach you?',
    input_type: 'free_text',
    applies_to: ['business_setup_advisory', 'shareholder_dispute', 'unpaid_invoice', 'contract_dispute', 'vendor_supplier_dispute', 'corporate_money_control', 'corporate_general'],
    tier: 'contact',
    question_group: 'contact',
    resolves: 'contact',
    decision_value: 1,
    abstraction_level: 'concrete',
    required: true,
    priority: 101,
  },
  {
    id: 'client_email',
    question: 'What email address should the firm use to follow up?',
    input_type: 'free_text',
    applies_to: ['business_setup_advisory', 'shareholder_dispute', 'unpaid_invoice', 'contract_dispute', 'vendor_supplier_dispute', 'corporate_money_control', 'corporate_general'],
    tier: 'contact',
    question_group: 'contact',
    resolves: 'contact',
    decision_value: 1,
    abstraction_level: 'concrete',
    required: true,
    priority: 102,
  },

  // ─── CORPORATE GENERAL (intermediate routing lane) ────────────────────────

  {
    id: 'corporate_problem_type',
    question: 'What best describes the problem you are facing?',
    input_type: 'single_select',
    options: [
      { value: 'Someone owes my company money', label: 'Someone owes my company money' },
      { value: 'I have a dispute with a business partner or co-owner', label: 'I have a dispute with a business partner or co-owner' },
      { value: 'A vendor or supplier has billed us incorrectly', label: 'A vendor or supplier has billed us incorrectly' },
      { value: 'I am concerned about financial irregularities in the company', label: 'I am concerned about financial irregularities in the company' },
      { value: 'A contract or agreement was not honoured', label: 'A contract or agreement was not honoured' },
      { value: 'Something else', label: 'Something else' },
    ],
    applies_to: ['corporate_general'],
    tier: 'core',
    question_group: 'routing',
    resolves: 'dispute_subtype',
    decision_value: 15,
    abstraction_level: 'concrete',
    required: true,
    priority: 1,
  },
  {
    id: 'company_involvement',
    question: 'What is your relationship to the company involved?',
    input_type: 'single_select',
    options: [
      { value: 'I own or co-own the company', label: 'I own or co-own the company' },
      { value: 'I am a director or officer', label: 'I am a director or officer' },
      { value: 'I am a customer or client of the company', label: 'I am a customer or client of the company' },
      { value: 'I work for the company', label: 'I work for the company' },
      { value: 'I am a vendor or supplier', label: 'I am a vendor or supplier' },
      { value: 'Other', label: 'Other' },
    ],
    applies_to: ['corporate_general'],
    tier: 'core',
    question_group: 'routing',
    resolves: 'company_role',
    decision_value: 10,
    abstraction_level: 'concrete',
    required: false,
    priority: 2,
    evidence_patterns: {
      'I own or co-own the company': [
        'i own', 'co-owner', 'co owner', 'shareholder', 'partner in the company', 'i started',
      ],
      'I am a director or officer': [
        'director', 'officer', 'president', 'vice president',
      ],
      'I work for the company': [
        'i work for', 'as an employee', 'as the accountant', 'as a bookkeeper',
      ],
      'I am a vendor or supplier': [
        'vendor', 'supplier', 'service provider',
      ],
    },
  },

  // ─── BUSINESS SETUP ADVISORY ──────────────────────────────────────────────

  {
    id: 'advisory_path',
    question: 'Are you starting something new, or buying into an existing business?',
    input_type: 'single_select',
    options: [
      { value: 'Starting a new business', label: 'Starting a new business' },
      { value: 'Buying into an existing business', label: 'Buying into an existing business' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['business_setup_advisory'],
    tier: 'core',
    question_group: 'advisory',
    resolves: 'advisory_path',
    decision_value: 10,
    abstraction_level: 'concrete',
    required: true,
    priority: 10,
    evidence_patterns: {
      'Starting a new business': [
        'start a business', 'starting a business', 'start a company', 'starting a company',
        'open a company', 'opening a company', 'set up a company', 'setting up a company',
        'incorporate', 'incorporating', 'business idea', 'company together', 'business together',
        'with a friend', 'with a partner', 'bring someone in', 'bring in a partner',
        'do it properly', 'protect myself', 'structure it properly', 'split ownership',
        'new company', 'new business',
      ],
      'Buying into an existing business': [
        'buying into', 'buy into', 'joining a company', 'joining an existing', 'buying in',
        'buy in', 'investment in a company', 'invest in a business',
        'review the documents', 'check the documents before signing',
        'shareholder agreement before starting',
      ],
    },
  },
  {
    id: 'co_owner_count',
    question: 'Will anyone else own or run the business with you?',
    input_type: 'single_select',
    options: [
      { value: 'Just me', label: 'Just me' },
      { value: 'One partner', label: 'One partner' },
      { value: 'Multiple partners', label: 'Multiple partners' },
      { value: 'Not sure yet', label: 'Not sure yet' },
    ],
    applies_to: ['business_setup_advisory'],
    applies_to_subtrack: ['solo_setup', 'partner_setup', 'unknown'],
    tier: 'core',
    question_group: 'advisory',
    resolves: 'co_owner_count',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: true,
    priority: 11,
    evidence_patterns: {
      'Just me': [
        'just me', 'by myself', 'on my own', 'alone', 'solo', 'just myself',
        'incorporate by myself', 'start it alone', 'only me',
      ],
      'One partner': [
        'with a friend', 'with a partner', 'my friend and i', 'my partner and i',
        'one partner', 'a friend', 'one other person', 'with one person',
        'cofounder', 'co-founder', 'two of us',
        'company together', 'business together', 'opening a company together',
        'starting a company together', 'do it together',
      ],
      'Multiple partners': [
        'multiple partners', 'a few of us', 'three of us', 'four of us',
        'several partners', 'group of us',
      ],
      'Not sure yet': [
        'might bring someone in', 'might bring in', 'thinking about bringing',
        'maybe a partner', 'not sure yet', 'possibly',
      ],
    },
  },
  {
    id: 'advisory_concern',
    question: 'What are you most concerned about right now?',
    input_type: 'single_select',
    options: [
      { value: 'Knowing what kind of company to set up', label: 'Knowing what kind of company to set up' },
      { value: 'Deciding who owns what', label: 'Deciding who owns what' },
      { value: 'Avoiding problems with a partner later', label: 'Avoiding problems with a partner later' },
      { value: 'Reviewing documents before signing', label: 'Reviewing documents before signing' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['business_setup_advisory'],
    applies_to_subtrack: ['partner_setup', 'buy_in_or_joining', 'unknown'],
    tier: 'core',
    question_group: 'advisory',
    resolves: 'advisory_concern',
    decision_value: 8,
    abstraction_level: 'medium',
    required: false,
    priority: 12,
    evidence_patterns: {
      'Knowing what kind of company to set up': [
        'what kind of company', 'what type of company', 'what structure', 'how to structure',
        'best structure', 'do it properly', 'set it up properly', 'structure it properly',
        'properly', 'right way',
      ],
      'Deciding who owns what': [
        'who owns what', 'split ownership', 'ownership split', 'decide ownership',
        'share split', 'equity split',
      ],
      'Avoiding problems with a partner later': [
        'protect myself', 'avoid problems', 'protect myself from', 'protection',
        'problems later', 'issues later', 'disputes later', 'fallout',
      ],
      'Reviewing documents before signing': [
        'review the documents', 'check the documents', 'documents before signing',
        'review before signing', 'look over', 'review agreement',
      ],
    },
  },
  {
    id: 'signed_anything',
    question: 'Have you already signed or agreed to anything?',
    input_type: 'single_select',
    options: [
      { value: 'Yes', label: 'Yes' },
      { value: 'No', label: 'No' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['business_setup_advisory'],
    tier: 'proof',
    question_group: 'agreement_proof',
    resolves: 'agreement_proof',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: false,
    priority: 13,
    evidence_patterns: {
      'Yes': [
        'i signed', 'we signed', 'already signed', 'signed something',
        'signed an agreement', 'signed documents', 'signed a contract',
      ],
      'No': [
        "haven't signed", 'have not signed', 'nothing signed', 'no documents signed',
        "didn't sign", 'did not sign', 'not signed', 'no signature',
      ],
    },
  },
  {
    id: 'documents_exist',
    question: 'Do you already have documents you want a lawyer to review?',
    input_type: 'single_select',
    options: [
      { value: 'Yes', label: 'Yes' },
      { value: 'No', label: 'No' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['business_setup_advisory'],
    applies_to_subtrack: ['buy_in_or_joining'],
    tier: 'proof',
    question_group: 'agreement_proof',
    resolves: 'agreement_proof',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: false,
    priority: 14,
    evidence_patterns: {
      'Yes': [
        'have documents', 'have the documents', 'documents to review', 'sent me documents',
        'received documents', 'got documents', 'they sent', 'review the documents',
        'check the documents',
      ],
      'No': [
        'no documents', 'no papers', 'nothing yet', 'not received anything',
      ],
    },
  },
  {
    id: 'advisory_actionability',
    question: 'Are you planning to move forward soon, or just exploring at this stage?',
    input_type: 'single_select',
    options: [
      { value: 'Just exploring', label: 'Just exploring' },
      { value: 'Planning soon', label: 'Planning soon' },
      { value: 'Ready to move forward', label: 'Ready to move forward' },
      { value: 'Need review now', label: 'Need review now' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['business_setup_advisory'],
    tier: 'qualification',
    question_group: 'advisory',
    resolves: 'advisory_actionability',
    decision_value: 6,
    abstraction_level: 'medium',
    required: false,
    priority: 22,
    evidence_patterns: {
      'Just exploring': [
        'just exploring', 'just looking', 'just thinking', 'thinking about it',
        'early stage', 'early days', 'not ready yet', 'just an idea', 'research',
      ],
      'Planning soon': [
        'planning soon', 'in the next few months', 'next few months', 'planning to',
        'want to start', 'thinking of starting',
      ],
      'Ready to move forward': [
        'ready to move', 'want to move forward', 'ready to start', 'want to start now',
        'asap', 'as soon as possible',
      ],
      'Need review now': [
        'need review now', 'need it reviewed', 'urgent review', 'review this week',
        'review asap', 'review now',
      ],
    },
  },
  {
    id: 'advisory_specific_task',
    question: 'What would you want a lawyer to help with first?',
    input_type: 'single_select',
    options: [
      { value: 'Choosing the right structure', label: 'Choosing the right structure' },
      { value: 'Reviewing documents', label: 'Reviewing documents' },
      { value: 'Splitting ownership', label: 'Splitting ownership' },
      { value: 'Protecting against future problems', label: 'Protecting against future problems' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['business_setup_advisory'],
    tier: 'qualification',
    question_group: 'advisory',
    resolves: 'advisory_specific_task',
    decision_value: 5,
    abstraction_level: 'medium',
    required: false,
    priority: 25,
  },
  {
    id: 'advisory_timing',
    question: 'When do you need help?',
    input_type: 'single_select',
    options: [
      { value: 'No rush', label: 'No rush' },
      { value: 'In the next 1-3 months', label: 'In the next 1-3 months' },
      { value: 'This month', label: 'This month' },
      { value: 'This week', label: 'This week' },
      { value: 'Urgent', label: 'Urgent' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['business_setup_advisory'],
    applies_to_subtrack: ['buy_in_or_joining'],
    tier: 'qualification',
    question_group: 'advisory',
    resolves: 'advisory_timing',
    decision_value: 7,
    abstraction_level: 'medium',
    required: false,
    priority: 16,
    evidence_patterns: {
      'Urgent': [
        'this week', 'urgent', 'urgently', 'asap', 'as soon as possible',
        'right away', 'immediately', 'right now', 'today',
      ],
      'This month': [
        'this month', 'end of month', 'before the end of the month',
      ],
      'In the next 1-3 months': [
        'next few months', 'in a few months', '1-3 months', 'couple of months',
      ],
      'No rush': [
        'no rush', 'no hurry', 'whenever', 'not urgent', 'at my convenience',
      ],
    },
  },
  {
    id: 'business_activity_type',
    question: 'What kind of business are you planning to start?',
    input_type: 'single_select',
    options: [
      { value: 'Professional services', label: 'Professional services' },
      { value: 'Online business', label: 'Online business' },
      { value: 'Retail or storefront', label: 'Retail or storefront' },
      { value: 'Trades or construction', label: 'Trades or construction' },
      { value: 'Holding company or investment', label: 'Holding company or investment' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['business_setup_advisory'],
    applies_to_subtrack: ['solo_setup', 'partner_setup'],
    tier: 'qualification',
    question_group: 'advisory',
    resolves: 'business_activity_type',
    decision_value: 4,
    abstraction_level: 'concrete',
    required: false,
    priority: 17,
  },
  {
    id: 'business_stage',
    question: 'How far along are you?',
    input_type: 'single_select',
    options: [
      { value: 'Just researching', label: 'Just researching' },
      { value: 'Planning to start soon', label: 'Planning to start soon' },
      { value: 'Already operating', label: 'Already operating' },
      { value: 'Need to incorporate before launching', label: 'Need to incorporate before launching' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['business_setup_advisory'],
    applies_to_subtrack: ['solo_setup', 'partner_setup'],
    tier: 'qualification',
    question_group: 'advisory',
    resolves: 'business_stage',
    decision_value: 5,
    abstraction_level: 'medium',
    required: false,
    priority: 18,
    evidence_patterns: {
      'Just researching': [
        'just researching', 'just looking into', 'exploring', 'early research', 'not decided yet',
      ],
      'Already operating': [
        'already operating', 'already running', 'already started', 'currently running',
        'already in business',
      ],
      'Need to incorporate before launching': [
        'need to incorporate', 'incorporate before', 'before i launch', 'before launching',
        'need to register before',
      ],
    },
  },
  {
    id: 'setup_needs',
    question: 'What do you need help with most?',
    input_type: 'single_select',
    options: [
      { value: 'Incorporating the company', label: 'Incorporating the company' },
      { value: 'Choosing the right business structure', label: 'Choosing the right business structure' },
      { value: 'Reviewing documents', label: 'Reviewing documents' },
      { value: 'Taxes or accounting setup', label: 'Taxes or accounting setup' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['business_setup_advisory'],
    applies_to_subtrack: ['solo_setup'],
    tier: 'qualification',
    question_group: 'advisory',
    resolves: 'setup_needs',
    decision_value: 5,
    abstraction_level: 'medium',
    required: false,
    priority: 19,
    evidence_patterns: {
      'Incorporating the company': [
        'incorporate', 'incorporation', 'register the company', 'registration',
        'basic guidance', 'just need guidance',
      ],
      'Reviewing documents': [
        'review documents', 'review the documents', 'check documents',
      ],
    },
  },
  {
    id: 'ownership_split_discussed',
    question: 'Have you discussed how ownership, responsibilities, or profits would be split?',
    input_type: 'single_select',
    options: [
      { value: 'Yes', label: 'Yes' },
      { value: 'No', label: 'No' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['business_setup_advisory'],
    applies_to_subtrack: ['partner_setup'],
    tier: 'qualification',
    question_group: 'advisory',
    resolves: 'ownership',
    decision_value: 6,
    abstraction_level: 'medium',
    required: false,
    priority: 20,
    evidence_patterns: {
      'Yes': [
        'discussed ownership', 'talked about ownership', 'agreed on split',
        'split ownership', 'ownership split', '50/50', '60/40',
      ],
      'No': [
        "haven't discussed", 'not discussed', 'not talked about', "haven't talked about",
      ],
    },
  },
  {
    id: 'business_location',
    question: 'Which city or region will the business be based in?',
    input_type: 'free_text',
    applies_to: ['business_setup_advisory'],
    tier: 'qualification',
    question_group: 'advisory',
    resolves: 'business_location',
    decision_value: 3,
    abstraction_level: 'concrete',
    required: false,
    priority: 23,
  },
  {
    id: 'revenue_expectation',
    question: 'What kind of revenue do you expect in the first year?',
    input_type: 'single_select',
    options: [
      { value: 'Under $30,000 (small or part-time)', label: 'Under $30,000 (small or part-time)' },
      { value: '$30,000–$100,000 (full-time, sole operator)', label: '$30,000–$100,000 (full-time, sole operator)' },
      { value: '$100,000–$500,000 (small team or busy practice)', label: '$100,000–$500,000 (small team or busy practice)' },
      { value: 'Over $500,000 (early-stage business with momentum)', label: 'Over $500,000 (early-stage business with momentum)' },
      { value: 'Not sure yet', label: 'Not sure yet' },
    ],
    applies_to: ['business_setup_advisory'],
    tier: 'core',
    question_group: 'advisory',
    resolves: 'revenue_expectation',
    decision_value: 8,
    abstraction_level: 'concrete',
    required: true,
    priority: 24,
  },
  {
    id: 'employees_planned',
    question: 'Are you planning to hire anyone in the first year?',
    input_type: 'single_select',
    options: [
      { value: 'No, just me', label: 'No, just me' },
      { value: 'Maybe one or two contractors', label: 'Maybe one or two contractors' },
      { value: 'Yes, one or two employees', label: 'Yes, one or two employees' },
      { value: 'Yes, three or more employees', label: 'Yes, three or more employees' },
      { value: 'Not sure yet', label: 'Not sure yet' },
    ],
    applies_to: ['business_setup_advisory'],
    tier: 'core',
    question_group: 'advisory',
    resolves: 'employees_planned',
    decision_value: 7,
    abstraction_level: 'concrete',
    required: true,
    priority: 25,
  },
  {
    id: 'regulated_industry',
    question: 'Is your industry regulated?',
    input_type: 'single_select',
    options: [
      { value: 'No, general services or products', label: 'No, general services or products' },
      { value: 'Yes, health or medical', label: 'Yes, health or medical' },
      { value: 'Yes, financial or investment', label: 'Yes, financial or investment' },
      { value: 'Yes, food or alcohol', label: 'Yes, food or alcohol' },
      { value: 'Yes, legal or professional licensing', label: 'Yes, legal or professional licensing' },
      { value: 'Yes, other regulated area', label: 'Yes, other regulated area' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['business_setup_advisory'],
    tier: 'core',
    question_group: 'advisory',
    resolves: 'regulated_industry',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: true,
    priority: 26,
  },
  {
    id: 'cross_border_work',
    question: 'Will you sell to or work with clients outside Canada?',
    input_type: 'single_select',
    options: [
      { value: 'No, Canada only', label: 'No, Canada only' },
      { value: 'Mostly US clients', label: 'Mostly US clients' },
      { value: 'Mostly other international', label: 'Mostly other international' },
      { value: 'Mixed Canadian and foreign', label: 'Mixed Canadian and foreign' },
      { value: 'Not sure yet', label: 'Not sure yet' },
    ],
    applies_to: ['business_setup_advisory'],
    tier: 'core',
    question_group: 'advisory',
    resolves: 'cross_border_work',
    decision_value: 8,
    abstraction_level: 'concrete',
    required: true,
    priority: 27,
  },
  {
    id: 'ip_planned',
    question: 'Do you have brand, software, or other intellectual property to protect?',
    input_type: 'single_select',
    options: [
      { value: 'No, services only', label: 'No, services only' },
      { value: 'Yes, a brand name or logo to protect', label: 'Yes, a brand name or logo to protect' },
      { value: 'Yes, software, code, or formulas', label: 'Yes, software, code, or formulas' },
      { value: 'Yes, multiple types of IP', label: 'Yes, multiple types of IP' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['business_setup_advisory'],
    tier: 'core',
    question_group: 'advisory',
    resolves: 'ip_planned',
    decision_value: 6,
    abstraction_level: 'concrete',
    required: false,
    priority: 28,
  },
  // ─── SHAREHOLDER DISPUTE ──────────────────────────────────────────────────

  {
    id: 'client_role',
    question: 'Which best describes you in this situation?',
    input_type: 'single_select',
    options: [
      { value: 'Shareholder', label: 'Shareholder' },
      { value: 'Director/officer', label: 'Director/officer' },
      { value: 'Business partner', label: 'Business partner' },
      { value: 'Employee', label: 'Employee' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['shareholder_dispute'],
    tier: 'core',
    question_group: 'standing',
    resolves: 'ownership',
    decision_value: 5,
    abstraction_level: 'concrete',
    required: false,
    priority: 30,
    evidence_patterns: {
      'Shareholder': ['shareholder', 'share holder', 'own shares', 'owns shares', 'have shares'],
      'Business partner': ['business partner', 'partner', 'cofounder', 'co-founder', 'co owner', 'co-owner'],
      'Director/officer': ['director', 'officer', 'president', 'secretary', 'treasurer'],
    },
  },
  {
    id: 'counterparty_type',
    question: 'Who is the issue with?',
    input_type: 'single_select',
    options: [
      { value: 'Business partner', label: 'Business partner' },
      { value: 'Cofounder', label: 'Cofounder' },
      { value: 'Other shareholder', label: 'Other shareholder' },
      { value: 'Company management', label: 'Company management' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['shareholder_dispute'],
    tier: 'core',
    question_group: 'standing',
    resolves: 'ownership',
    decision_value: 4,
    abstraction_level: 'concrete',
    required: false,
    priority: 31,
  },
  {
    id: 'ownership_percentage',
    question: 'What percentage of the company do you own, if you know?',
    input_type: 'free_text',
    applies_to: ['shareholder_dispute'],
    tier: 'core',
    question_group: 'standing',
    resolves: 'ownership',
    decision_value: 8,
    abstraction_level: 'concrete',
    required: false,
    priority: 32,
    evidence_patterns: {
      'known': ['%', 'percent', 'half', '50', '33', '25', '40', '60', 'equal shares'],
    },
  },
  {
    id: 'proof_of_ownership',
    question: 'Do you have any documents, emails, or messages showing your ownership or decision-making role in the company?',
    input_type: 'single_select',
    options: [
      { value: 'Yes', label: 'Yes' },
      { value: 'No', label: 'No' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['shareholder_dispute'],
    tier: 'proof',
    question_group: 'ownership_proof',
    resolves: 'ownership_proof',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: false,
    priority: 33,
    evidence_patterns: {
      'Yes': [
        'have documents', 'have emails', 'have messages', 'have records',
        'shareholder agreement', 'share certificate', 'ownership documents',
        'i have proof', 'i have evidence',
      ],
      'No': ['no documents', 'nothing in writing', 'no proof', 'no evidence', 'no records'],
    },
  },
  {
    id: 'shareholder_agreement',
    question: 'Do you have a shareholder agreement or any ownership documents?',
    input_type: 'single_select',
    options: [
      { value: 'Yes', label: 'Yes' },
      { value: 'No', label: 'No' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['shareholder_dispute'],
    tier: 'proof',
    question_group: 'ownership_proof',
    resolves: 'ownership_proof',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: false,
    priority: 34,
    evidence_patterns: {
      'Yes': [
        'shareholder agreement', 'shareholders agreement', 'share certificate',
        'certificate of shares', 'ownership agreement', 'ownership documents',
        'have an agreement', 'signed agreement',
      ],
      'No': ['no agreement', 'no shareholder agreement', 'no documents', 'nothing signed', 'handshake deal', 'verbal agreement'],
    },
  },
  {
    id: 'corporate_records_available',
    question: "Do you have access to the company's financial records or bank accounts?",
    input_type: 'single_select',
    options: [
      { value: 'Yes', label: 'Yes' },
      { value: 'No', label: 'No' },
      { value: 'Partial access', label: 'Partial access' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['shareholder_dispute'],
    tier: 'core',
    question_group: 'access_proof',
    resolves: 'access',
    decision_value: 10,
    abstraction_level: 'concrete',
    required: false,
    priority: 28,
    evidence_patterns: {
      'No': [
        "can't access", 'cannot access', 'locked out', 'no access', 'blocked',
        "can't see", 'cannot see', "won't show me", 'not showing me',
        "can't access the bank", 'locked out of the bank', 'changed bank access',
        'bank account access', 'removed from bank', 'taken off',
        "won't show records", "won't show me anything",
      ],
      'Partial access': ['partial access', 'some access', 'limited access'],
      'Yes': ['have access', 'can access', 'can see the records', 'access to records'],
    },
  },
  {
    id: 'management_exclusion',
    question: 'Has your partner restricted your access to company decisions, records, or accounts?',
    input_type: 'single_select',
    options: [
      { value: 'Yes', label: 'Yes' },
      { value: 'No', label: 'No' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['shareholder_dispute'],
    tier: 'core',
    question_group: 'control',
    resolves: 'access',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: false,
    priority: 29,
    evidence_patterns: {
      'Yes': [
        'making decisions without me', 'left out', 'excluding me', 'excluded',
        'without telling me', 'not telling me', 'keeping me out', 'being pushed out',
        'locked out', 'restricted access', 'changed passwords',
      ],
    },
  },
  {
    id: 'dividend_or_money_issue',
    question: "Is company money being taken or used in a way you don't agree with?",
    input_type: 'single_select',
    options: [
      { value: 'Yes', label: 'Yes' },
      { value: 'No', label: 'No' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['shareholder_dispute'],
    tier: 'core',
    question_group: 'control',
    resolves: 'money_misuse',
    decision_value: 10,
    abstraction_level: 'concrete',
    required: false,
    priority: 27,
    evidence_patterns: {
      'Yes': [
        'taking money', 'took money', 'hiding money', 'money missing', 'company money',
        'siphoning', 'draining the company', 'unauthorized withdrawals',
        'money being taken', 'misusing funds', 'personal use',
        'i think money is being taken', 'money is being taken out',
      ],
    },
  },
  {
    id: 'company_profitable',
    question: 'Is the company profitable or holding meaningful assets?',
    input_type: 'single_select',
    options: [
      { value: 'Yes', label: 'Yes' },
      { value: 'No', label: 'No' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['shareholder_dispute'],
    tier: 'strategic',
    question_group: 'value',
    resolves: 'value',
    decision_value: 8,
    abstraction_level: 'medium',
    required: false,
    priority: 35,
    evidence_patterns: {
      'Yes': ['profitable', 'making money', 'generating revenue', 'has assets', 'has value', 'real business', 'active business', 'significant assets'],
      'No': ['not profitable', 'losing money', 'no revenue', 'no assets', 'broke', 'not making money'],
    },
  },
  {
    id: 'deadlock_status',
    question: 'Is the business deadlocked or unable to make decisions?',
    input_type: 'single_select',
    options: [
      { value: 'Yes', label: 'Yes' },
      { value: 'No', label: 'No' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['shareholder_dispute'],
    tier: 'strategic',
    question_group: 'risk',
    resolves: 'risk',
    decision_value: 7,
    abstraction_level: 'medium',
    required: false,
    priority: 36,
  },
  {
    id: 'desired_outcome_shareholder_dispute',
    question: 'What would be the best outcome for you?',
    input_type: 'single_select',
    options: [
      { value: 'Recover money taken from the company', label: 'Recover money taken from the company' },
      { value: 'Regain access to records or accounts', label: 'Regain access to records or accounts' },
      { value: 'Stop unauthorized decisions', label: 'Stop unauthorized decisions' },
      { value: 'Negotiate a buyout or exit', label: 'Negotiate a buyout or exit' },
      { value: 'Resolve ownership/control dispute', label: 'Resolve ownership/control dispute' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['shareholder_dispute'],
    tier: 'qualification',
    question_group: 'status',
    resolves: 'none',
    decision_value: 3,
    abstraction_level: 'medium',
    required: false,
    priority: 40,
  },

  // ─── UNPAID INVOICE ───────────────────────────────────────────────────────

  {
    id: 'amount_at_stake',
    question: 'About how much money is involved?',
    input_type: 'single_select',
    options: [
      { value: 'Under $5,000', label: 'Under $5,000' },
      { value: '$5,000–$25,000', label: '$5,000–$25,000' },
      { value: '$25,000–$100,000', label: '$25,000–$100,000' },
      { value: 'Over $100,000', label: 'Over $100,000' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['unpaid_invoice', 'contract_dispute', 'vendor_supplier_dispute'],
    tier: 'core',
    question_group: 'value',
    resolves: 'value',
    decision_value: 10,
    abstraction_level: 'concrete',
    required: false,
    priority: 50,
    evidence_patterns: {
      'Under $5,000': ['under $5,000', 'under 5000', 'less than $5,000', 'small amount', 'a few hundred', 'under five thousand'],
      '$5,000–$25,000': ['$10,000', '$15,000', '$20,000', 'ten thousand', 'fifteen thousand', 'twenty thousand', '5000', '10000', '15000', '20000'],
      '$25,000–$100,000': ['$50,000', '$75,000', '$30,000', 'fifty thousand', 'thirty thousand'],
      'Over $100,000': ['over $100,000', 'over 100,000', 'six figures', 'hundred thousand', '$200,000', '$500,000'],
    },
  },
  {
    id: 'invoice_exists',
    question: 'Do you have an invoice, bill, or statement showing what is owed?',
    input_type: 'single_select',
    options: [
      { value: 'Yes', label: 'Yes' },
      { value: 'No', label: 'No' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['unpaid_invoice'],
    tier: 'proof',
    question_group: 'payment_proof',
    resolves: 'payment',
    decision_value: 8,
    abstraction_level: 'concrete',
    required: false,
    priority: 51,
    evidence_patterns: {
      'Yes': ['invoice', 'sent an invoice', 'have an invoice', 'bill', 'statement', 'billing statement'],
      'No': ['no invoice', 'no bill', 'verbal', 'no documentation'],
    },
  },
  {
    id: 'payment_status',
    question: 'Has any of the amount been paid?',
    input_type: 'single_select',
    options: [
      { value: 'Nothing paid', label: 'Nothing paid' },
      { value: 'Partially paid', label: 'Partially paid' },
      { value: 'Disputed — claims they paid', label: 'Disputed — claims they paid' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['unpaid_invoice'],
    tier: 'proof',
    question_group: 'payment_proof',
    resolves: 'payment',
    decision_value: 7,
    abstraction_level: 'concrete',
    required: false,
    priority: 52,
    evidence_patterns: {
      'Nothing paid': [
        'not paying', "hasn't paid", "haven't paid", 'not paid', 'owes me',
        'owes us', 'outstanding', 'unpaid', 'zero payment', 'no payment',
      ],
      'Partially paid': ['partially paid', 'partial payment', 'some payment', 'paid some', 'paid part', 'partial'],
      'Disputed — claims they paid': ['says they paid', 'claims they paid', 'says it was paid', 'disputes the amount', 'denies the debt'],
    },
  },
  {
    id: 'proof_of_performance',
    question: 'Do you have anything showing the work, goods, or services were delivered?',
    input_type: 'single_select',
    options: [
      { value: 'Yes', label: 'Yes' },
      { value: 'No', label: 'No' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['unpaid_invoice'],
    tier: 'proof',
    question_group: 'delivery_proof',
    resolves: 'delivery_proof',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: false,
    priority: 53,
    evidence_patterns: {
      'Yes': [
        'delivery confirmation', 'signed off', 'proof of delivery', 'receipt',
        'completion certificate', 'they accepted', 'they approved', 'evidence of delivery',
        'can show the work was done', 'have records',
      ],
      'No': ['no proof', 'no delivery confirmation', 'no receipt', 'no records'],
    },
  },
  {
    id: 'dispute_reason',
    question: 'What is the other side saying about why they are not paying?',
    input_type: 'single_select',
    options: [
      { value: 'Says work was not done properly', label: 'Says work was not done properly' },
      { value: 'Says there was no agreement', label: 'Says there was no agreement' },
      { value: 'Says they already paid', label: 'Says they already paid' },
      { value: 'No clear reason', label: 'No clear reason' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['unpaid_invoice', 'contract_dispute'],
    tier: 'core',
    question_group: 'risk',
    resolves: 'risk',
    decision_value: 8,
    abstraction_level: 'concrete',
    required: false,
    priority: 54,
    evidence_patterns: {
      'Says work was not done properly': [
        'says the work was bad', 'quality issue', 'not done properly', 'bad work',
        'defective', 'incomplete work', 'work was not done right', "wasn't done right",
        'work not done', "claims it wasn't done",
      ],
      'Says there was no agreement': [
        'says there was no agreement', 'denies the agreement', 'denies everything',
        'deny everything', 'denying everything', 'no agreement', 'says no contract',
      ],
      'Says they already paid': ['says they already paid', 'claims they paid', 'insists they paid'],
      'No clear reason': ['no reason', 'not explaining', 'silent', 'just delaying', 'ignoring', 'giving excuses', 'keeps delaying'],
    },
  },
  {
    id: 'desired_outcome_unpaid_invoice',
    question: 'What would be the best outcome for you?',
    input_type: 'single_select',
    options: [
      { value: 'Get paid', label: 'Get paid' },
      { value: 'Negotiate payment', label: 'Negotiate payment' },
      { value: 'Send demand letter', label: 'Send demand letter' },
      { value: 'Start claim', label: 'Start claim' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['unpaid_invoice'],
    tier: 'qualification',
    question_group: 'status',
    resolves: 'none',
    decision_value: 3,
    abstraction_level: 'medium',
    required: false,
    priority: 60,
  },

  // ─── CONTRACT DISPUTE ─────────────────────────────────────────────────────

  {
    id: 'written_terms',
    question: 'Do you have anything in writing that shows what was agreed — like emails or messages?',
    input_type: 'single_select',
    options: [
      { value: 'Yes', label: 'Yes' },
      { value: 'No', label: 'No' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['contract_dispute'],
    tier: 'proof',
    question_group: 'agreement_proof',
    resolves: 'agreement_proof',
    decision_value: 10,
    abstraction_level: 'concrete',
    required: false,
    priority: 70,
    evidence_patterns: {
      'Yes': [
        'over email', 'by email', 'email agreement', 'agreed by email', 'by text',
        'by message', 'messages', 'in writing', 'written agreement', 'contract',
        'signed', 'have emails', 'have messages', 'have a contract',
        'we agreed over email', 'agreed via email',
      ],
      'No': ['verbal', 'handshake', 'word of mouth', 'nothing in writing', 'no contract', 'no written agreement', 'oral agreement'],
    },
  },
  {
    id: 'contract_exists',
    question: 'Is there a signed contract or written agreement?',
    input_type: 'single_select',
    options: [
      { value: 'Yes', label: 'Yes' },
      { value: 'No', label: 'No' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['contract_dispute'],
    tier: 'proof',
    question_group: 'agreement_proof',
    resolves: 'agreement_proof',
    decision_value: 10,
    abstraction_level: 'concrete',
    required: false,
    priority: 71,
    evidence_patterns: {
      'Yes': ['signed contract', 'formal contract', 'have a contract', 'agreement in place', 'we have a contract', 'signed agreement'],
      'No': ['no contract', 'no formal contract', 'nothing signed', 'just emails'],
    },
  },
  {
    id: 'communications_exist',
    question: 'Do you have any written communication about what was agreed?',
    input_type: 'single_select',
    options: [
      { value: 'Yes', label: 'Yes' },
      { value: 'No', label: 'No' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['contract_dispute'],
    tier: 'proof',
    question_group: 'agreement_proof',
    resolves: 'agreement_proof',
    decision_value: 4,
    abstraction_level: 'abstract',
    required: false,
    priority: 90,
  },
  {
    id: 'desired_outcome_contract',
    question: 'What would be the best outcome for you?',
    input_type: 'single_select',
    options: [
      { value: 'Enforce agreement', label: 'Enforce agreement' },
      { value: 'Recover damages', label: 'Recover damages' },
      { value: 'Stop the other side from breaching', label: 'Stop the other side from breaching' },
      { value: 'Negotiate settlement', label: 'Negotiate settlement' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['contract_dispute'],
    tier: 'qualification',
    question_group: 'status',
    resolves: 'none',
    decision_value: 3,
    abstraction_level: 'medium',
    required: false,
    priority: 80,
  },

  // ─── VENDOR / SUPPLIER DISPUTE ────────────────────────────────────────────

  {
    id: 'vendor_type',
    question: 'Who is the billing dispute with?',
    input_type: 'single_select',
    options: [
      { value: 'A supplier of goods', label: 'A supplier of goods' },
      { value: 'A service provider', label: 'A service provider' },
      { value: 'A software or subscription vendor', label: 'A software or subscription vendor' },
      { value: 'A contractor or subcontractor', label: 'A contractor or subcontractor' },
      { value: 'Another type of vendor', label: 'Another type of vendor' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['vendor_supplier_dispute'],
    tier: 'core',
    question_group: 'vendor',
    resolves: 'vendor_billing',
    decision_value: 8,
    abstraction_level: 'concrete',
    required: false,
    priority: 55,
    evidence_patterns: {
      'A supplier of goods': ['supplier', 'supplier of goods', 'goods supplier', 'product supplier'],
      'A service provider': ['service provider', 'professional services'],
      'A software or subscription vendor': ['software', 'saas', 'subscription', 'software vendor', 'platform'],
      'A contractor or subcontractor': ['contractor', 'subcontractor', 'consultant'],
    },
  },
  {
    id: 'billing_dispute_reason',
    question: 'What is the billing dispute about?',
    input_type: 'single_select',
    options: [
      { value: 'Overcharged for services or goods received', label: 'Overcharged for services or goods received' },
      { value: 'Charged for something we did not receive', label: 'Charged for something we did not receive' },
      { value: 'Dispute over contract terms or pricing', label: 'Dispute over contract terms or pricing' },
      { value: 'Unauthorized or unexpected charges', label: 'Unauthorized or unexpected charges' },
      { value: 'Subscription or renewal dispute', label: 'Subscription or renewal dispute' },
      { value: 'Other', label: 'Other' },
    ],
    applies_to: ['vendor_supplier_dispute'],
    tier: 'core',
    question_group: 'risk',
    resolves: 'risk',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: false,
    priority: 56,
    evidence_patterns: {
      'Overcharged for services or goods received': ['overcharged', 'overbilled', 'charged too much', 'wrong amount', 'billed incorrectly', 'vendor billed wrong'],
      'Charged for something we did not receive': ['charged for something we didn\'t receive', 'not received', 'never delivered', 'did not receive', 'billed for undelivered'],
      'Unauthorized or unexpected charges': ['unauthorized charge', 'unexpected charge', 'charged without approval', 'charged without consent'],
      'Subscription or renewal dispute': ['subscription dispute', 'renewal dispute', 'auto-renewal', 'cancelled subscription', 'did not renew'],
    },
  },
  {
    id: 'vendor_contract_exists',
    question: 'Do you have a contract, agreement, or terms of service with this vendor?',
    input_type: 'single_select',
    options: [
      { value: 'Yes, a signed contract', label: 'Yes, a signed contract' },
      { value: 'Yes, terms of service or a purchase order', label: 'Yes, terms of service or a purchase order' },
      { value: 'No formal agreement', label: 'No formal agreement' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['vendor_supplier_dispute'],
    tier: 'proof',
    question_group: 'agreement_proof',
    resolves: 'agreement_proof',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: false,
    priority: 57,
    evidence_patterns: {
      'Yes, a signed contract': ['signed contract with vendor', 'vendor contract', 'have a contract with them'],
      'Yes, terms of service or a purchase order': ['terms of service', 'purchase order', 'po', 'click-through agreement'],
      'No formal agreement': ['no contract', 'verbal agreement with vendor', 'no written agreement'],
    },
  },
  {
    id: 'vendor_services_received',
    question: 'Were the goods or services you are disputing actually delivered or performed?',
    input_type: 'single_select',
    options: [
      { value: 'Yes, fully delivered', label: 'Yes, fully delivered' },
      { value: 'Partially delivered', label: 'Partially delivered' },
      { value: 'Not delivered', label: 'Not delivered' },
      { value: 'Disputed', label: 'Disputed' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['vendor_supplier_dispute'],
    tier: 'proof',
    question_group: 'delivery_proof',
    resolves: 'delivery_proof',
    decision_value: 8,
    abstraction_level: 'concrete',
    required: false,
    priority: 58,
    evidence_patterns: {
      'Not delivered': ['not delivered', 'never received', 'not received', 'did not deliver'],
      'Partially delivered': ['partially delivered', 'partial delivery', 'some delivered', 'incomplete delivery'],
      'Yes, fully delivered': ['fully delivered', 'was delivered', 'received everything', 'goods received'],
    },
  },
  {
    id: 'desired_outcome_vendor',
    question: 'What would be the best outcome for you?',
    input_type: 'single_select',
    options: [
      { value: 'Refund or credit', label: 'Refund or credit' },
      { value: 'Correct invoice and pay proper amount', label: 'Correct invoice and pay proper amount' },
      { value: 'Terminate the vendor relationship', label: 'Terminate the vendor relationship' },
      { value: 'Damages for losses caused', label: 'Damages for losses caused' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['vendor_supplier_dispute'],
    tier: 'qualification',
    question_group: 'status',
    resolves: 'none',
    decision_value: 3,
    abstraction_level: 'medium',
    required: false,
    priority: 65,
  },

  // ─── CORPORATE MONEY / CONTROL ────────────────────────────────────────────

  {
    id: 'reporter_role_money',
    question: 'What is your role in the company?',
    input_type: 'single_select',
    options: [
      { value: 'Owner or shareholder', label: 'Owner or shareholder' },
      { value: 'Director or officer', label: 'Director or officer' },
      { value: 'Employee or manager', label: 'Employee or manager' },
      { value: 'Accountant or bookkeeper', label: 'Accountant or bookkeeper' },
      { value: 'Other', label: 'Other' },
    ],
    applies_to: ['corporate_money_control'],
    tier: 'core',
    question_group: 'company_role_group',
    resolves: 'company_role',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: false,
    priority: 41,
    evidence_patterns: {
      'Owner or shareholder': ['owner', 'shareholder', 'co-owner', 'partner'],
      'Director or officer': ['director', 'officer', 'president'],
      'Employee or manager': ['employee', 'i work for', 'staff member', 'manager'],
      'Accountant or bookkeeper': ['accountant', 'bookkeeper', 'cpa', 'comptroller', 'as the accountant', 'as a bookkeeper'],
    },
  },
  {
    id: 'irregularity_type',
    question: 'What type of financial concern do you have?',
    input_type: 'single_select',
    options: [
      { value: 'Money appears to be missing or unaccounted for', label: 'Money appears to be missing or unaccounted for' },
      { value: 'Unauthorized payments or transfers', label: 'Unauthorized payments or transfers' },
      { value: 'Fraudulent or inflated invoices', label: 'Fraudulent or inflated invoices' },
      { value: 'Someone is misusing company accounts or cards', label: 'Someone is misusing company accounts or cards' },
      { value: 'Other', label: 'Other' },
    ],
    applies_to: ['corporate_money_control'],
    tier: 'core',
    question_group: 'irregularity',
    resolves: 'financial_irregularity',
    decision_value: 10,
    abstraction_level: 'concrete',
    required: false,
    priority: 42,
    evidence_patterns: {
      'Money appears to be missing or unaccounted for': ['money missing', 'unaccounted', 'funds missing', 'missing from accounts', 'cannot account for'],
      'Unauthorized payments or transfers': ['unauthorized payment', 'unauthorized transfer', 'unauthorized wire', 'transfer without approval'],
      'Fraudulent or inflated invoices': ['fraudulent invoice', 'fake invoice', 'inflated invoice', 'embezzlement', 'embezzled'],
      'Someone is misusing company accounts or cards': ['misusing company card', 'personal use of company', 'using company money personally'],
    },
  },
  {
    id: 'irregularity_amount',
    question: 'Do you have an estimate of how much money may be involved?',
    input_type: 'single_select',
    options: [
      { value: 'Under $10,000', label: 'Under $10,000' },
      { value: '$10,000–$50,000', label: '$10,000–$50,000' },
      { value: '$50,000–$200,000', label: '$50,000–$200,000' },
      { value: 'Over $200,000', label: 'Over $200,000' },
      { value: 'Unknown', label: 'Unknown' },
    ],
    applies_to: ['corporate_money_control'],
    tier: 'core',
    question_group: 'value',
    resolves: 'value',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: false,
    priority: 43,
  },
  {
    id: 'evidence_of_irregularity',
    question: 'Do you have any records, statements, or documents showing the irregularity?',
    input_type: 'single_select',
    options: [
      { value: 'Yes', label: 'Yes' },
      { value: 'No', label: 'No' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['corporate_money_control'],
    tier: 'proof',
    question_group: 'irregularity',
    resolves: 'irregularity_evidence',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: false,
    priority: 44,
    evidence_patterns: {
      'Yes': ['have records', 'have statements', 'bank statements', 'have evidence', 'have documents', 'have proof'],
      'No': ['no records', 'no evidence', 'nothing documented'],
    },
  },
  {
    id: 'reported_to_anyone',
    question: 'Has this been reported to anyone — police, accountant, other directors, or your board?',
    input_type: 'single_select',
    options: [
      { value: 'Yes, reported', label: 'Yes, reported' },
      { value: 'No, not yet', label: 'No, not yet' },
      { value: 'In progress', label: 'In progress' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['corporate_money_control'],
    tier: 'strategic',
    question_group: 'risk',
    resolves: 'risk',
    decision_value: 7,
    abstraction_level: 'medium',
    required: false,
    priority: 45,
  },
  {
    id: 'desired_outcome_money_control',
    question: 'What outcome are you looking for?',
    input_type: 'single_select',
    options: [
      { value: 'Recover the missing money', label: 'Recover the missing money' },
      { value: 'Stop the misuse', label: 'Stop the misuse' },
      { value: 'Internal investigation', label: 'Internal investigation' },
      { value: 'Report to authorities', label: 'Report to authorities' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['corporate_money_control'],
    tier: 'qualification',
    question_group: 'status',
    resolves: 'none',
    decision_value: 3,
    abstraction_level: 'medium',
    required: false,
    priority: 49,
  },

  // ─── REAL ESTATE GENERAL (intermediate routing lane) ─────────────────────

  {
    id: 'real_estate_problem_type',
    question: 'What best describes what you need help with?',
    input_type: 'single_select',
    options: [
      { value: 'Buying or selling commercial property', label: 'Buying or selling commercial property' },
      { value: 'Buying or selling a home or condo', label: 'Buying or selling a home or condo' },
      { value: 'A real estate deal that has gone wrong (deposit, closing, misrepresentation)', label: 'A real estate deal that has gone wrong (deposit, closing, misrepresentation)' },
      { value: 'A landlord or tenant dispute', label: 'A landlord or tenant dispute' },
      { value: 'Unpaid construction or renovation work', label: 'Unpaid construction or renovation work' },
      { value: 'A pre-construction condo or new build issue', label: 'A pre-construction condo or new build issue' },
      { value: 'A mortgage or power-of-sale issue', label: 'A mortgage or power-of-sale issue' },
      { value: 'Something else', label: 'Something else' },
    ],
    applies_to: ['real_estate_general'],
    tier: 'core',
    question_group: 'routing',
    resolves: 'real_estate_subtype',
    decision_value: 15,
    abstraction_level: 'concrete',
    required: true,
    priority: 1,
  },

  // ─── COMMERCIAL REAL ESTATE ──────────────────────────────────────────────

  {
    id: 'commercial_re_role',
    question: 'Are you the buyer, seller, landlord, or tenant?',
    input_type: 'single_select',
    options: [
      { value: 'Buyer', label: 'Buyer' },
      { value: 'Seller', label: 'Seller' },
      { value: 'Landlord', label: 'Landlord' },
      { value: 'Tenant', label: 'Tenant' },
      { value: 'Investor', label: 'Investor' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['commercial_real_estate'],
    tier: 'core',
    question_group: 'parties',
    resolves: 'party_role',
    decision_value: 12,
    abstraction_level: 'concrete',
    required: true,
    priority: 2,
    evidence_patterns: {
      'Buyer': ['buying', 'we are buying', 'i am buying', 'on the buying side'],
      'Seller': ['selling', 'we are selling', 'i am selling', 'on the selling side'],
      'Landlord': ['as landlord', 'leasing out', 'leasing to'],
      'Tenant': ['leasing from', 'as tenant', 'taking a lease'],
      'Investor': ['investment property', 'investor'],
    },
  },
  {
    id: 'commercial_property_type',
    question: 'What type of commercial property is involved?',
    input_type: 'single_select',
    options: [
      { value: 'Office', label: 'Office' },
      { value: 'Retail / storefront', label: 'Retail / storefront' },
      { value: 'Industrial / warehouse', label: 'Industrial / warehouse' },
      { value: 'Mixed-use', label: 'Mixed-use' },
      { value: 'Multi-residential / apartment building', label: 'Multi-residential / apartment building' },
      { value: 'Land / development site', label: 'Land / development site' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['commercial_real_estate'],
    tier: 'core',
    question_group: 'property',
    resolves: 'property_type',
    decision_value: 10,
    abstraction_level: 'concrete',
    required: true,
    priority: 4,
    evidence_patterns: {
      'Office': ['office space', 'office building'],
      'Retail / storefront': ['retail space', 'storefront', 'plaza unit', 'shop space'],
      'Industrial / warehouse': ['industrial', 'warehouse'],
      'Mixed-use': ['mixed use', 'mixed-use'],
      'Multi-residential / apartment building': ['apartment building', 'multi residential', 'multi-residential'],
      'Land / development site': ['vacant land', 'development site', 'land for development'],
    },
  },
  {
    id: 'commercial_re_amount',
    question: 'What is the approximate transaction or lease value?',
    input_type: 'single_select',
    options: [
      { value: 'Under $500,000', label: 'Under $500,000' },
      { value: '$500,000–$2M', label: '$500,000–$2M' },
      { value: '$2M–$10M', label: '$2M–$10M' },
      { value: 'Over $10M', label: 'Over $10M' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['commercial_real_estate'],
    tier: 'core',
    question_group: 'value',
    resolves: 'value',
    decision_value: 14,
    abstraction_level: 'concrete',
    required: true,
    priority: 3,
  },
  {
    id: 'commercial_re_stage',
    question: 'Where are you in the deal?',
    input_type: 'single_select',
    options: [
      { value: 'Just exploring', label: 'Just exploring' },
      { value: 'Talking with the other side', label: 'Talking with the other side' },
      { value: 'Signed an offer or letter of intent', label: 'Signed an offer or letter of intent' },
      { value: 'Conditions still to clear', label: 'Conditions still to clear' },
      { value: 'Closing date set', label: 'Closing date set' },
      { value: 'Already closed', label: 'Already closed' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['commercial_real_estate'],
    tier: 'core',
    question_group: 'transaction_stage',
    resolves: 'transaction_stage',
    decision_value: 11,
    abstraction_level: 'concrete',
    required: true,
    priority: 5,
    evidence_patterns: {
      'Signed an offer or letter of intent': ['signed an aps', 'signed the aps', 'loi signed', 'letter of intent', 'signed an offer'],
      'Closing date set': ['closing date', 'set to close', 'closing in', 'closing next'],
      'Already closed': ['already closed', 'we closed', 'closing completed'],
    },
  },
  {
    id: 'commercial_re_concerns',
    question: 'What concern brought you to a lawyer?',
    input_type: 'single_select',
    options: [
      { value: 'Reviewing the agreement', label: 'Reviewing the agreement' },
      { value: 'Title or zoning concern', label: 'Title or zoning concern' },
      { value: 'Environmental concern', label: 'Environmental concern' },
      { value: 'Financing or mortgage', label: 'Financing or mortgage' },
      { value: 'Tenant or lease structure', label: 'Tenant or lease structure' },
      { value: 'Not sure yet', label: 'Not sure yet' },
    ],
    applies_to: ['commercial_real_estate'],
    tier: 'strategic',
    question_group: 'risk',
    resolves: 'risk',
    decision_value: 7,
    abstraction_level: 'medium',
    required: false,
    priority: 18,
  },

  // ─── RESIDENTIAL PURCHASE / SALE ─────────────────────────────────────────

  {
    id: 'residential_role',
    question: 'Are you buying or selling?',
    input_type: 'single_select',
    options: [
      { value: 'Buying', label: 'Buying' },
      { value: 'Selling', label: 'Selling' },
      { value: 'Both (buying and selling)', label: 'Both (buying and selling)' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['residential_purchase_sale'],
    tier: 'core',
    question_group: 'parties',
    resolves: 'party_role',
    decision_value: 10,
    abstraction_level: 'concrete',
    required: true,
    priority: 2,
    evidence_patterns: {
      'Buying': ['buying a house', 'buying a home', 'buying a condo', 'buying my first', 'about to buy'],
      'Selling': ['selling my house', 'selling my home', 'selling my condo', 'about to sell', 'listing my'],
    },
  },
  {
    id: 'residential_property_type',
    question: 'What type of property?',
    input_type: 'single_select',
    options: [
      { value: 'Detached / semi-detached', label: 'Detached / semi-detached' },
      { value: 'Townhouse', label: 'Townhouse' },
      { value: 'Condo', label: 'Condo' },
      { value: 'Pre-construction unit', label: 'Pre-construction unit' },
      { value: 'Vacant land', label: 'Vacant land' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['residential_purchase_sale'],
    tier: 'core',
    question_group: 'property',
    resolves: 'property_type',
    decision_value: 8,
    abstraction_level: 'concrete',
    required: true,
    priority: 5,
  },
  {
    id: 'residential_re_amount',
    question: 'What is the approximate property value?',
    input_type: 'single_select',
    options: [
      { value: 'Under $500,000', label: 'Under $500,000' },
      { value: '$500,000–$1M', label: '$500,000–$1M' },
      { value: '$1M–$2M', label: '$1M–$2M' },
      { value: 'Over $2M', label: 'Over $2M' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['residential_purchase_sale'],
    tier: 'core',
    question_group: 'value',
    resolves: 'value',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: true,
    priority: 3,
  },
  {
    id: 'residential_re_stage',
    question: 'Where are you in the process?',
    input_type: 'single_select',
    options: [
      { value: 'Just exploring', label: 'Just exploring' },
      { value: 'Offer not yet made', label: 'Offer not yet made' },
      { value: 'Offer accepted, still working through conditions', label: 'Offer accepted, still working through conditions' },
      { value: 'Deal is locked, closing soon', label: 'Deal is locked, closing soon' },
      { value: 'Closing this week, urgent', label: 'Closing this week, urgent' },
      { value: 'Already closed', label: 'Already closed' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['residential_purchase_sale'],
    tier: 'core',
    question_group: 'transaction_stage',
    resolves: 'transaction_stage',
    decision_value: 10,
    abstraction_level: 'concrete',
    required: true,
    priority: 4,
  },
  {
    id: 'residential_re_concern',
    question: 'What do you need help with most?',
    input_type: 'single_select',
    options: [
      { value: 'Reviewing the contract before signing', label: 'Reviewing the contract before signing' },
      { value: 'Title and closing paperwork', label: 'Title and closing paperwork' },
      { value: 'Mortgage and financing', label: 'Mortgage and financing' },
      { value: 'Conditions or guarantees', label: 'Conditions or guarantees' },
      { value: 'Something has gone wrong at closing', label: 'Something has gone wrong at closing' },
      { value: 'Not sure yet', label: 'Not sure yet' },
    ],
    applies_to: ['residential_purchase_sale'],
    tier: 'core',
    question_group: 'risk',
    resolves: 'risk',
    decision_value: 5,
    abstraction_level: 'medium',
    required: true,
    priority: 20,
  },
  {
    id: 'residential_closing_timeline',
    question: 'When is the closing?',
    input_type: 'single_select',
    options: [
      { value: 'No firm date yet', label: 'No firm date yet' },
      { value: 'More than 60 days away', label: 'More than 60 days away' },
      { value: '30 to 60 days away', label: '30 to 60 days away' },
      { value: 'Less than 30 days away', label: 'Less than 30 days away' },
      { value: 'This week', label: 'This week' },
      { value: 'Already passed (closing was missed)', label: 'Already passed (closing was missed)' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['residential_purchase_sale'],
    tier: 'core',
    question_group: 'transaction_stage',
    resolves: 'closing_timeline',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: true,
    priority: 21,
  },
  {
    id: 'residential_mortgage_situation',
    question: 'Where are you with financing?',
    input_type: 'single_select',
    options: [
      { value: 'Pre-approved', label: 'Pre-approved' },
      { value: 'Approved with conditions still open', label: 'Approved with conditions still open' },
      { value: 'Application submitted, no answer yet', label: 'Application submitted, no answer yet' },
      { value: 'Cash purchase, no financing', label: 'Cash purchase, no financing' },
      { value: 'Private or alternative lender', label: 'Private or alternative lender' },
      { value: 'Not started', label: 'Not started' },
    ],
    applies_to: ['residential_purchase_sale'],
    tier: 'core',
    question_group: 'transaction_stage',
    resolves: 'mortgage_situation',
    decision_value: 8,
    abstraction_level: 'concrete',
    required: true,
    priority: 22,
  },
  {
    id: 'residential_representation',
    question: 'Do you have a real estate agent involved?',
    input_type: 'single_select',
    options: [
      { value: 'Yes, I have an agent', label: 'Yes, I have an agent' },
      { value: 'No, dealing with the other side directly', label: 'No, dealing with the other side directly' },
      { value: 'No, the seller has an agent and I do not', label: 'No, the seller has an agent and I do not' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['residential_purchase_sale'],
    tier: 'qualification',
    question_group: 'parties',
    resolves: 'representation_status',
    decision_value: 4,
    abstraction_level: 'concrete',
    required: false,
    priority: 23,
  },

  // ─── REAL ESTATE LITIGATION ──────────────────────────────────────────────

  {
    id: 'litigation_subject',
    question: 'What is the dispute about?',
    input_type: 'single_select',
    options: [
      { value: 'The other side did not close the deal', label: 'The other side did not close the deal' },
      { value: 'Deposit was lost or is being kept', label: 'Deposit was lost or is being kept' },
      { value: 'Seller hid problems or misrepresented the property', label: 'Seller hid problems or misrepresented the property' },
      { value: 'Title or boundary problem', label: 'Title or boundary problem' },
      { value: 'Disagreement over use of land (easement)', label: 'Disagreement over use of land (easement)' },
      { value: 'Real estate fraud', label: 'Real estate fraud' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['real_estate_litigation'],
    tier: 'core',
    question_group: 'status',
    resolves: 'litigation_subject',
    decision_value: 14,
    abstraction_level: 'concrete',
    required: true,
    priority: 2,
    evidence_patterns: {
      'The other side did not close the deal': ['failed to close', 'walked away', 'failed closing'],
      'Deposit was lost or is being kept': ['lost deposit', 'deposit dispute', 'deposit refund'],
      'Seller hid problems or misrepresented the property': ['misrepresentation', 'undisclosed defect', 'hidden defect', 'latent defect'],
      'Title or boundary problem': ['title dispute', 'boundary dispute', 'title problem'],
      'Disagreement over use of land (easement)': ['easement dispute', 'easement issue'],
      'Real estate fraud': ['real estate fraud', 'title fraud'],
    },
  },
  {
    id: 'litigation_role',
    question: 'What is your role in the dispute?',
    input_type: 'single_select',
    options: [
      { value: 'Buyer', label: 'Buyer' },
      { value: 'Seller', label: 'Seller' },
      { value: 'Property owner', label: 'Property owner' },
      { value: 'Neighbour', label: 'Neighbour' },
      { value: 'Investor', label: 'Investor' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['real_estate_litigation'],
    tier: 'core',
    question_group: 'parties',
    resolves: 'party_role',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: true,
    priority: 4,
  },
  {
    id: 'litigation_amount',
    question: 'What is roughly at stake?',
    input_type: 'single_select',
    options: [
      { value: 'Under $25,000', label: 'Under $25,000' },
      { value: '$25,000–$100,000', label: '$25,000–$100,000' },
      { value: '$100,000–$500,000', label: '$100,000–$500,000' },
      { value: 'Over $500,000', label: 'Over $500,000' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['real_estate_litigation'],
    tier: 'core',
    question_group: 'value',
    resolves: 'value',
    decision_value: 13,
    abstraction_level: 'concrete',
    required: true,
    priority: 3,
  },
  {
    id: 'litigation_documents',
    question: 'Do you have the agreement of purchase and sale or other written contract?',
    input_type: 'single_select',
    options: [
      { value: 'Yes', label: 'Yes' },
      { value: 'No', label: 'No' },
      { value: 'Some, but only drafts or partial', label: 'Some, but only drafts or partial' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['real_estate_litigation'],
    tier: 'proof',
    question_group: 'agreement_proof',
    resolves: 'agreement_proof',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: true,
    priority: 6,
  },
  {
    id: 'litigation_stage',
    question: 'Has anything been filed in court yet?',
    input_type: 'single_select',
    options: [
      { value: 'No, not yet', label: 'No, not yet' },
      { value: "A lawyer's letter has been sent", label: "A lawyer's letter has been sent" },
      { value: 'Already in court (we filed)', label: 'Already in court (we filed)' },
      { value: 'Already in court (we were served)', label: 'Already in court (we were served)' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['real_estate_litigation'],
    tier: 'core',
    question_group: 'status',
    resolves: 'risk',
    decision_value: 7,
    abstraction_level: 'concrete',
    required: true,
    priority: 16,
  },
  {
    id: 'litigation_when_event',
    question: 'When did the issue happen or come to light?',
    input_type: 'single_select',
    options: [
      { value: 'In the last 30 days', label: 'In the last 30 days' },
      { value: 'Within the last 6 months', label: 'Within the last 6 months' },
      { value: '6 months to 2 years ago', label: '6 months to 2 years ago' },
      { value: 'Over 2 years ago', label: 'Over 2 years ago' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['real_estate_litigation'],
    tier: 'core',
    question_group: 'status',
    resolves: 'limitation_concern',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: true,
    priority: 17,
  },
  {
    id: 'litigation_settlement_attempted',
    question: 'Has there been any attempt to settle so far?',
    input_type: 'single_select',
    options: [
      { value: 'No contact yet', label: 'No contact yet' },
      { value: 'Informal conversations only', label: 'Informal conversations only' },
      { value: 'Demand letters exchanged', label: 'Demand letters exchanged' },
      { value: 'Mediation attempted, did not resolve', label: 'Mediation attempted, did not resolve' },
      { value: 'Settlement offer on the table', label: 'Settlement offer on the table' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['real_estate_litigation'],
    tier: 'core',
    question_group: 'status',
    resolves: 'settlement_attempted',
    decision_value: 7,
    abstraction_level: 'concrete',
    required: true,
    priority: 18,
  },

  // ─── LANDLORD / TENANT ───────────────────────────────────────────────────

  {
    id: 'tenancy_party',
    question: 'Are you the landlord or the tenant?',
    input_type: 'single_select',
    options: [
      { value: 'Landlord', label: 'Landlord' },
      { value: 'Tenant', label: 'Tenant' },
      { value: 'Property manager', label: 'Property manager' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['landlord_tenant'],
    tier: 'core',
    question_group: 'parties',
    resolves: 'party_role',
    decision_value: 12,
    abstraction_level: 'concrete',
    required: true,
    priority: 2,
    evidence_patterns: {
      'Landlord': ['as landlord', 'i am the landlord', 'we are the landlord', 'my tenant'],
      'Tenant': ['as tenant', 'i am the tenant', 'my landlord'],
      'Property manager': ['property manager', 'managing the building'],
    },
  },
  {
    id: 'tenancy_type',
    question: 'Is this a residential or commercial tenancy?',
    input_type: 'single_select',
    options: [
      { value: 'Residential (house, condo, apartment)', label: 'Residential (house, condo, apartment)' },
      { value: 'Commercial (office, retail, industrial)', label: 'Commercial (office, retail, industrial)' },
      { value: 'Mixed', label: 'Mixed' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['landlord_tenant'],
    tier: 'core',
    question_group: 'tenancy_terms',
    resolves: 'tenancy_type',
    decision_value: 12,
    abstraction_level: 'concrete',
    required: true,
    priority: 3,
    evidence_patterns: {
      'Residential (house, condo, apartment)': ['residential lease', 'residential tenant', 'apartment'],
      'Commercial (office, retail, industrial)': ['commercial lease', 'commercial tenant', 'office lease', 'retail lease'],
    },
  },
  {
    id: 'tenancy_issue',
    question: 'What is the dispute about?',
    input_type: 'single_select',
    options: [
      { value: 'Unpaid rent', label: 'Unpaid rent' },
      { value: 'Eviction or possession', label: 'Eviction or possession' },
      { value: 'Lease terms or breach', label: 'Lease terms or breach' },
      { value: 'Damage or repairs', label: 'Damage or repairs' },
      { value: 'Illegal use / nuisance', label: 'Illegal use / nuisance' },
      { value: 'Other', label: 'Other' },
    ],
    applies_to: ['landlord_tenant'],
    tier: 'core',
    question_group: 'tenancy_dispute',
    resolves: 'tenancy_issue',
    decision_value: 10,
    abstraction_level: 'concrete',
    required: true,
    priority: 4,
    evidence_patterns: {
      'Unpaid rent': ['unpaid rent', 'tenant won\'t pay', 'tenant not paying', 'rent arrears'],
      'Eviction or possession': ['eviction', 'evict', 'evicted', 'won\'t leave', 'overhold'],
      'Lease terms or breach': ['breach of lease', 'lease dispute', 'breaking the lease'],
      'Damage or repairs': ['damage to the property', 'damage to my unit', 'repairs not done'],
    },
  },
  {
    id: 'tenancy_amount',
    question: 'How much rent or damages are involved?',
    input_type: 'single_select',
    options: [
      { value: 'Under $5,000', label: 'Under $5,000' },
      { value: '$5,000–$25,000', label: '$5,000–$25,000' },
      { value: '$25,000–$100,000', label: '$25,000–$100,000' },
      { value: 'Over $100,000', label: 'Over $100,000' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['landlord_tenant'],
    tier: 'core',
    question_group: 'value',
    resolves: 'value',
    decision_value: 8,
    abstraction_level: 'concrete',
    required: true,
    priority: 5,
  },
  {
    id: 'tenancy_lease_exists',
    question: 'Is there a written lease?',
    input_type: 'single_select',
    options: [
      { value: 'Yes', label: 'Yes' },
      { value: 'No', label: 'No' },
      { value: 'Verbal only', label: 'Verbal only' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['landlord_tenant'],
    tier: 'proof',
    question_group: 'agreement_proof',
    resolves: 'lease_proof',
    decision_value: 7,
    abstraction_level: 'concrete',
    required: true,
    priority: 7,
  },
  {
    id: 'tenancy_notice_status',
    question: 'Has formal notice been given or any application started?',
    input_type: 'single_select',
    options: [
      { value: 'No, nothing started', label: 'No, nothing started' },
      { value: 'Formal notice given to the other side', label: 'Formal notice given to the other side' },
      { value: 'Application filed at the Landlord and Tenant Board', label: 'Application filed at the Landlord and Tenant Board' },
      { value: 'Court action started (commercial)', label: 'Court action started (commercial)' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['landlord_tenant'],
    tier: 'strategic',
    question_group: 'status',
    resolves: 'risk',
    decision_value: 6,
    abstraction_level: 'medium',
    required: false,
    priority: 14,
  },

  // ─── CONSTRUCTION LIEN ───────────────────────────────────────────────────

  {
    id: 'lien_role',
    question: 'What is your role on the project?',
    input_type: 'single_select',
    options: [
      { value: 'Property owner', label: 'Property owner' },
      { value: 'General contractor', label: 'General contractor' },
      { value: 'Subcontractor or trade', label: 'Subcontractor or trade' },
      { value: 'Supplier of materials', label: 'Supplier of materials' },
      { value: 'Architect or consultant', label: 'Architect or consultant' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['construction_lien'],
    tier: 'core',
    question_group: 'parties',
    resolves: 'party_role',
    decision_value: 12,
    abstraction_level: 'concrete',
    required: true,
    priority: 2,
  },
  {
    id: 'lien_amount',
    question: 'How much is owed?',
    input_type: 'single_select',
    options: [
      { value: 'Under $25,000', label: 'Under $25,000' },
      { value: '$25,000–$100,000', label: '$25,000–$100,000' },
      { value: '$100,000–$500,000', label: '$100,000–$500,000' },
      { value: 'Over $500,000', label: 'Over $500,000' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['construction_lien'],
    tier: 'core',
    question_group: 'value',
    resolves: 'value',
    decision_value: 14,
    abstraction_level: 'concrete',
    required: true,
    priority: 3,
  },
  {
    id: 'lien_last_supply',
    question: 'When did you last supply work or materials to the project?',
    input_type: 'single_select',
    options: [
      { value: 'Within the last 60 days', label: 'Within the last 60 days' },
      { value: '60–90 days ago', label: '60–90 days ago' },
      { value: 'More than 90 days ago', label: 'More than 90 days ago' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['construction_lien'],
    tier: 'core',
    question_group: 'lien',
    resolves: 'lien_timing',
    decision_value: 15,
    abstraction_level: 'concrete',
    required: true,
    priority: 4,
  },
  {
    id: 'lien_preserved',
    question: 'Has a claim against the property been registered yet?',
    input_type: 'single_select',
    options: [
      { value: 'Yes, a claim was registered', label: 'Yes, a claim was registered' },
      { value: 'Yes, registered and a court action started', label: 'Yes, registered and a court action started' },
      { value: 'No, nothing registered yet', label: 'No, nothing registered yet' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['construction_lien'],
    tier: 'proof',
    question_group: 'lien',
    resolves: 'lien_evidence',
    decision_value: 12,
    abstraction_level: 'concrete',
    required: true,
    priority: 6,
  },
  {
    id: 'lien_documents',
    question: 'Do you have the contract, invoices, and proof of work?',
    input_type: 'single_select',
    options: [
      { value: 'Yes, all three', label: 'Yes, all three' },
      { value: 'Some paperwork, not all', label: 'Some paperwork, not all' },
      { value: 'It was a verbal agreement', label: 'It was a verbal agreement' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['construction_lien'],
    tier: 'proof',
    question_group: 'agreement_proof',
    resolves: 'agreement_proof',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: true,
    priority: 8,
  },

  // ─── PRECONSTRUCTION CONDO ───────────────────────────────────────────────

  {
    id: 'precon_role',
    question: 'What is your role?',
    input_type: 'single_select',
    options: [
      { value: 'I am the original buyer', label: 'I am the original buyer' },
      { value: 'I am taking over a unit from someone else', label: 'I am taking over a unit from someone else' },
      { value: 'I am selling my unit before closing', label: 'I am selling my unit before closing' },
      { value: 'I bought multiple units (investor)', label: 'I bought multiple units (investor)' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['preconstruction_condo'],
    tier: 'core',
    question_group: 'parties',
    resolves: 'party_role',
    decision_value: 10,
    abstraction_level: 'concrete',
    required: true,
    priority: 2,
    evidence_patterns: {
      'Assignee (taking over a unit)': ['taking over a unit', 'buying an assignment', 'assignee'],
      'Assignor (selling my unit)': ['assigning my unit', 'selling my preconstruction', 'assignor'],
    },
  },
  {
    id: 'precon_issue',
    question: 'What is the issue?',
    input_type: 'single_select',
    options: [
      { value: 'Builder keeps delaying closing', label: 'Builder keeps delaying closing' },
      { value: 'Worried about my deposit', label: 'Worried about my deposit' },
      { value: 'Trouble selling my unit before closing', label: 'Trouble selling my unit before closing' },
      { value: 'New-home warranty issue (Tarion)', label: 'New-home warranty issue (Tarion)' },
      { value: 'Reviewing the contract before signing', label: 'Reviewing the contract before signing' },
      { value: 'Builder hid problems or misrepresented the unit', label: 'Builder hid problems or misrepresented the unit' },
      { value: 'Other', label: 'Other' },
    ],
    applies_to: ['preconstruction_condo'],
    tier: 'core',
    question_group: 'preconstruction',
    resolves: 'litigation_subject',
    decision_value: 13,
    abstraction_level: 'concrete',
    required: true,
    priority: 3,
    evidence_patterns: {
      'Delayed closing or occupancy': ['delayed closing', 'occupancy delay', 'extended closing'],
      'Deposit at risk': ['condo deposit', 'deposit at risk', 'deposit dispute'],
      'Assignment dispute or fee': ['assignment fee', 'assignment dispute'],
      'Tarion warranty issue': ['tarion'],
    },
  },
  {
    id: 'precon_developer_status',
    question: 'How is the developer responding?',
    input_type: 'single_select',
    options: [
      { value: 'Refusing or stalling', label: 'Refusing or stalling' },
      { value: 'Offering a settlement', label: 'Offering a settlement' },
      { value: 'No response', label: 'No response' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['preconstruction_condo'],
    tier: 'core',
    question_group: 'status',
    resolves: 'developer_status',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: true,
    priority: 6,
  },
  {
    id: 'precon_amount',
    question: 'How much is at stake?',
    input_type: 'single_select',
    options: [
      { value: 'Under $50,000', label: 'Under $50,000' },
      { value: '$50,000–$200,000', label: '$50,000–$200,000' },
      { value: 'Over $200,000', label: 'Over $200,000' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['preconstruction_condo'],
    tier: 'core',
    question_group: 'value',
    resolves: 'value',
    decision_value: 11,
    abstraction_level: 'concrete',
    required: true,
    priority: 5,
  },
  {
    id: 'precon_documents',
    question: 'Do you have the agreement of purchase and sale with the builder?',
    input_type: 'single_select',
    options: [
      { value: 'Yes', label: 'Yes' },
      { value: 'No', label: 'No' },
      { value: 'Partial', label: 'Partial' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['preconstruction_condo'],
    tier: 'proof',
    question_group: 'agreement_proof',
    resolves: 'agreement_proof',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: true,
    priority: 7,
  },

  // ─── MORTGAGE DISPUTE ────────────────────────────────────────────────────

  {
    id: 'mortgage_role',
    question: 'What is your position in this matter?',
    input_type: 'single_select',
    options: [
      { value: 'I am the borrower (property owner)', label: 'I am the borrower (property owner)' },
      { value: 'I am the lender', label: 'I am the lender' },
      { value: 'I co-signed or guaranteed the loan', label: 'I co-signed or guaranteed the loan' },
      { value: 'I am another involved party', label: 'I am another involved party' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['mortgage_dispute'],
    tier: 'core',
    question_group: 'parties',
    resolves: 'party_role',
    decision_value: 11,
    abstraction_level: 'concrete',
    required: true,
    priority: 2,
  },
  {
    id: 'mortgage_status',
    question: 'What is happening right now?',
    input_type: 'single_select',
    options: [
      { value: 'Lender is threatening to call the mortgage', label: 'Lender is threatening to call the mortgage' },
      { value: 'I received a Notice of Sale', label: 'I received a Notice of Sale' },
      { value: 'The lender has started the power-of-sale process', label: 'The lender has started the power-of-sale process' },
      { value: 'Disagreement over refinancing', label: 'Disagreement over refinancing' },
      { value: 'Issue with paying off or discharging the mortgage', label: 'Issue with paying off or discharging the mortgage' },
      { value: 'Other', label: 'Other' },
    ],
    applies_to: ['mortgage_dispute'],
    tier: 'core',
    question_group: 'status',
    resolves: 'mortgage_status',
    decision_value: 14,
    abstraction_level: 'concrete',
    required: true,
    priority: 3,
    evidence_patterns: {
      'Lender threatening default': ['lender threatening', 'mortgage arrears', 'default notice'],
      'Notice of Sale received': ['notice of sale'],
      'Power-of-sale process started': ['power of sale'],
    },
  },
  {
    id: 'mortgage_amount',
    question: 'What is the approximate mortgage balance or amount in dispute?',
    input_type: 'single_select',
    options: [
      { value: 'Under $250,000', label: 'Under $250,000' },
      { value: '$250,000–$1M', label: '$250,000–$1M' },
      { value: '$1M–$5M', label: '$1M–$5M' },
      { value: 'Over $5M', label: 'Over $5M' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['mortgage_dispute'],
    tier: 'core',
    question_group: 'value',
    resolves: 'value',
    decision_value: 11,
    abstraction_level: 'concrete',
    required: true,
    priority: 4,
  },
  {
    id: 'mortgage_lender_type',
    question: 'What kind of lender?',
    input_type: 'single_select',
    options: [
      { value: 'A bank or major institution', label: 'A bank or major institution' },
      { value: 'A private lender', label: 'A private lender' },
      { value: 'A credit union', label: 'A credit union' },
      { value: 'A mortgage investment company', label: 'A mortgage investment company' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['mortgage_dispute'],
    tier: 'strategic',
    question_group: 'parties',
    resolves: 'risk',
    decision_value: 6,
    abstraction_level: 'medium',
    required: false,
    priority: 12,
  },
  {
    id: 'mortgage_documents',
    question: 'Do you have the mortgage documents and any notices received?',
    input_type: 'single_select',
    options: [
      { value: 'Yes', label: 'Yes' },
      { value: 'Some', label: 'Some' },
      { value: 'No', label: 'No' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: ['mortgage_dispute'],
    tier: 'proof',
    question_group: 'agreement_proof',
    resolves: 'agreement_proof',
    decision_value: 8,
    abstraction_level: 'concrete',
    required: true,
    priority: 8,
  },

  // ─── UNIVERSAL READINESS (asked at the end of every matter chain) ────────

  {
    id: 'hiring_timeline',
    question: 'When are you hoping to have a lawyer working on this?',
    input_type: 'single_select',
    options: [
      { value: 'Now (this week)', label: 'Now (this week)' },
      { value: 'Within the next 30 days', label: 'Within the next 30 days' },
      { value: 'Within the next few months', label: 'Within the next few months' },
      { value: 'Just exploring, no timeline yet', label: 'Just exploring, no timeline yet' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: [
      'business_setup_advisory',
      'shareholder_dispute',
      'unpaid_invoice',
      'contract_dispute',
      'vendor_supplier_dispute',
      'corporate_money_control',
      'corporate_general',
      'commercial_real_estate',
      'residential_purchase_sale',
      'real_estate_litigation',
      'landlord_tenant',
      'construction_lien',
      'preconstruction_condo',
      'mortgage_dispute',
      'real_estate_general',
    ],
    tier: 'core',
    question_group: 'readiness',
    resolves: 'hiring_timeline',
    decision_value: 8,
    abstraction_level: 'concrete',
    required: true,
    priority: 95,
  },
  {
    id: 'other_counsel',
    question: 'Have you spoken to another lawyer about this matter?',
    input_type: 'single_select',
    options: [
      { value: 'No, you are the first', label: 'No, you are the first' },
      { value: 'Yes, I am comparing options', label: 'Yes, I am comparing options' },
      { value: 'Yes, switching from a previous lawyer', label: 'Yes, switching from a previous lawyer' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: [
      'business_setup_advisory',
      'shareholder_dispute',
      'unpaid_invoice',
      'contract_dispute',
      'vendor_supplier_dispute',
      'corporate_money_control',
      'corporate_general',
      'commercial_real_estate',
      'residential_purchase_sale',
      'real_estate_litigation',
      'landlord_tenant',
      'construction_lien',
      'preconstruction_condo',
      'mortgage_dispute',
      'real_estate_general',
    ],
    tier: 'core',
    question_group: 'readiness',
    resolves: 'other_counsel',
    decision_value: 6,
    abstraction_level: 'concrete',
    required: true,
    priority: 96,
  },
  {
    id: 'decision_authority',
    question: 'Who decides whether to hire a lawyer for this?',
    input_type: 'single_select',
    options: [
      { value: 'Just me', label: 'Just me' },
      { value: 'Me with a partner or family member', label: 'Me with a partner or family member' },
      { value: 'Multiple owners or directors', label: 'Multiple owners or directors' },
      { value: 'Someone else decides', label: 'Someone else decides' },
      { value: 'Not sure', label: 'Not sure' },
    ],
    applies_to: [
      'business_setup_advisory',
      'shareholder_dispute',
      'unpaid_invoice',
      'contract_dispute',
      'vendor_supplier_dispute',
      'corporate_money_control',
      'corporate_general',
      'commercial_real_estate',
      'residential_purchase_sale',
      'real_estate_litigation',
      'landlord_tenant',
      'construction_lien',
      'preconstruction_condo',
      'mortgage_dispute',
      'real_estate_general',
    ],
    tier: 'core',
    question_group: 'readiness',
    resolves: 'decision_authority',
    decision_value: 5,
    abstraction_level: 'concrete',
    required: true,
    priority: 97,
  },
];

export function getSlotById(id: string): SlotDefinition | undefined {
  return SLOT_REGISTRY.find(s => s.id === id);
}

export function getSlotsForMatter(matterType: string): SlotDefinition[] {
  return SLOT_REGISTRY.filter(s => s.applies_to.includes(matterType as never));
}
