import type { SlotDefinition } from './types';

export const SLOT_REGISTRY: SlotDefinition[] = [

  // ─── CONTACT ──────────────────────────────────────────────────────────────

  {
    id: 'client_name',
    question: 'What is your name?',
    input_type: 'free_text',
    applies_to: ['business_setup_advisory', 'shareholder_dispute', 'unpaid_invoice', 'contract_dispute', 'vendor_supplier_dispute', 'corporate_money_control', 'corporate_general'],
    tier: 'contact',
    question_group: 'contact',
    resolves: 'contact',
    decision_value: 1,
    abstraction_level: 'concrete',
    required: true,
    priority: 100,
  },
  {
    id: 'client_phone',
    question: 'What is the best phone number to reach you?',
    input_type: 'free_text',
    applies_to: ['business_setup_advisory', 'shareholder_dispute', 'unpaid_invoice', 'contract_dispute', 'vendor_supplier_dispute', 'corporate_money_control', 'corporate_general'],
    tier: 'contact',
    question_group: 'contact',
    resolves: 'contact',
    decision_value: 1,
    abstraction_level: 'concrete',
    required: true,
    priority: 101,
  },
  {
    id: 'client_email',
    question: 'What email address should the firm use to follow up?',
    input_type: 'free_text',
    applies_to: ['business_setup_advisory', 'shareholder_dispute', 'unpaid_invoice', 'contract_dispute', 'vendor_supplier_dispute', 'corporate_money_control', 'corporate_general'],
    tier: 'contact',
    question_group: 'contact',
    resolves: 'contact',
    decision_value: 1,
    abstraction_level: 'concrete',
    required: true,
    priority: 102,
  },

  // ─── CORPORATE GENERAL (intermediate routing lane) ────────────────────────

  {
    id: 'corporate_problem_type',
    question: 'What best describes the problem you are facing?',
    input_type: 'single_select',
    options: [
      'Someone owes my company money',
      'I have a dispute with a business partner or co-owner',
      'A vendor or supplier has billed us incorrectly',
      'I am concerned about financial irregularities in the company',
      'A contract or agreement was not honoured',
      'Something else',
    ],
    applies_to: ['corporate_general'],
    tier: 'core',
    question_group: 'routing',
    resolves: 'dispute_subtype',
    decision_value: 15,
    abstraction_level: 'concrete',
    required: true,
    priority: 1,
  },
  {
    id: 'company_involvement',
    question: 'What is your relationship to the company involved?',
    input_type: 'single_select',
    options: [
      'I own or co-own the company',
      'I am a director or officer',
      'I am a customer or client of the company',
      'I work for the company',
      'I am a vendor or supplier',
      'Other',
    ],
    applies_to: ['corporate_general'],
    tier: 'core',
    question_group: 'routing',
    resolves: 'company_role',
    decision_value: 10,
    abstraction_level: 'concrete',
    required: false,
    priority: 2,
    evidence_patterns: {
      'I own or co-own the company': [
        'i own', 'co-owner', 'co owner', 'shareholder', 'partner in the company', 'i started',
      ],
      'I am a director or officer': [
        'director', 'officer', 'president', 'vice president',
      ],
      'I work for the company': [
        'i work for', 'as an employee', 'as the accountant', 'as a bookkeeper',
      ],
      'I am a vendor or supplier': [
        'vendor', 'supplier', 'service provider',
      ],
    },
  },

  // ─── BUSINESS SETUP ADVISORY ──────────────────────────────────────────────

  {
    id: 'advisory_path',
    question: 'Are you starting something new, or buying into an existing business?',
    input_type: 'single_select',
    options: ['Starting a new business', 'Buying into an existing business', 'Not sure'],
    applies_to: ['business_setup_advisory'],
    tier: 'core',
    question_group: 'advisory',
    resolves: 'advisory_path',
    decision_value: 10,
    abstraction_level: 'concrete',
    required: true,
    priority: 10,
    evidence_patterns: {
      'Starting a new business': [
        'start a business', 'starting a business', 'start a company', 'starting a company',
        'open a company', 'opening a company', 'set up a company', 'setting up a company',
        'incorporate', 'incorporating', 'business idea', 'company together', 'business together',
        'with a friend', 'with a partner', 'bring someone in', 'bring in a partner',
        'do it properly', 'protect myself', 'structure it properly', 'split ownership',
        'new company', 'new business',
      ],
      'Buying into an existing business': [
        'buying into', 'buy into', 'joining a company', 'joining an existing', 'buying in',
        'buy in', 'investment in a company', 'invest in a business',
        'review the documents', 'check the documents before signing',
        'shareholder agreement before starting',
      ],
    },
  },
  {
    id: 'co_owner_count',
    question: 'Will anyone else own or run the business with you?',
    input_type: 'single_select',
    options: ['Just me', 'One partner', 'Multiple partners', 'Not sure yet'],
    applies_to: ['business_setup_advisory'],
    applies_to_subtrack: ['solo_setup', 'partner_setup', 'unknown'],
    tier: 'core',
    question_group: 'advisory',
    resolves: 'co_owner_count',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: true,
    priority: 11,
    evidence_patterns: {
      'Just me': [
        'just me', 'by myself', 'on my own', 'alone', 'solo', 'just myself',
        'incorporate by myself', 'start it alone', 'only me',
      ],
      'One partner': [
        'with a friend', 'with a partner', 'my friend and i', 'my partner and i',
        'one partner', 'a friend', 'one other person', 'with one person',
        'cofounder', 'co-founder', 'two of us',
        'company together', 'business together', 'opening a company together',
        'starting a company together', 'do it together',
      ],
      'Multiple partners': [
        'multiple partners', 'a few of us', 'three of us', 'four of us',
        'several partners', 'group of us',
      ],
      'Not sure yet': [
        'might bring someone in', 'might bring in', 'thinking about bringing',
        'maybe a partner', 'not sure yet', 'possibly',
      ],
    },
  },
  {
    id: 'advisory_concern',
    question: 'What are you most concerned about right now?',
    input_type: 'single_select',
    options: [
      'Knowing what kind of company to set up',
      'Deciding who owns what',
      'Avoiding problems with a partner later',
      'Reviewing documents before signing',
      'Not sure',
    ],
    applies_to: ['business_setup_advisory'],
    applies_to_subtrack: ['partner_setup', 'buy_in_or_joining', 'unknown'],
    tier: 'core',
    question_group: 'advisory',
    resolves: 'advisory_concern',
    decision_value: 8,
    abstraction_level: 'medium',
    required: false,
    priority: 12,
    evidence_patterns: {
      'Knowing what kind of company to set up': [
        'what kind of company', 'what type of company', 'what structure', 'how to structure',
        'best structure', 'do it properly', 'set it up properly', 'structure it properly',
        'properly', 'right way',
      ],
      'Deciding who owns what': [
        'who owns what', 'split ownership', 'ownership split', 'decide ownership',
        'share split', 'equity split',
      ],
      'Avoiding problems with a partner later': [
        'protect myself', 'avoid problems', 'protect myself from', 'protection',
        'problems later', 'issues later', 'disputes later', 'fallout',
      ],
      'Reviewing documents before signing': [
        'review the documents', 'check the documents', 'documents before signing',
        'review before signing', 'look over', 'review agreement',
      ],
    },
  },
  {
    id: 'signed_anything',
    question: 'Have you already signed or agreed to anything?',
    input_type: 'single_select',
    options: ['Yes', 'No', 'Not sure'],
    applies_to: ['business_setup_advisory'],
    tier: 'proof',
    question_group: 'agreement_proof',
    resolves: 'agreement_proof',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: false,
    priority: 13,
    evidence_patterns: {
      'Yes': [
        'i signed', 'we signed', 'already signed', 'signed something',
        'signed an agreement', 'signed documents', 'signed a contract',
      ],
      'No': [
        "haven't signed", 'have not signed', 'nothing signed', 'no documents signed',
        "didn't sign", 'did not sign', 'not signed', 'no signature',
      ],
    },
  },
  {
    id: 'documents_exist',
    question: 'Do you already have documents you want a lawyer to review?',
    input_type: 'single_select',
    options: ['Yes', 'No', 'Not sure'],
    applies_to: ['business_setup_advisory'],
    applies_to_subtrack: ['buy_in_or_joining'],
    tier: 'proof',
    question_group: 'agreement_proof',
    resolves: 'agreement_proof',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: false,
    priority: 14,
    evidence_patterns: {
      'Yes': [
        'have documents', 'have the documents', 'documents to review', 'sent me documents',
        'received documents', 'got documents', 'they sent', 'review the documents',
        'check the documents',
      ],
      'No': [
        'no documents', 'no papers', 'nothing yet', 'not received anything',
      ],
    },
  },
  {
    id: 'advisory_actionability',
    question: 'Are you planning to move forward soon, or just exploring at this stage?',
    input_type: 'single_select',
    options: [
      'Just exploring',
      'Planning soon',
      'Ready to move forward',
      'Need review now',
      'Not sure',
    ],
    applies_to: ['business_setup_advisory'],
    tier: 'qualification',
    question_group: 'advisory',
    resolves: 'advisory_actionability',
    decision_value: 6,
    abstraction_level: 'medium',
    required: false,
    priority: 22,
    evidence_patterns: {
      'Just exploring': [
        'just exploring', 'just looking', 'just thinking', 'thinking about it',
        'early stage', 'early days', 'not ready yet', 'just an idea', 'research',
      ],
      'Planning soon': [
        'planning soon', 'in the next few months', 'next few months', 'planning to',
        'want to start', 'thinking of starting',
      ],
      'Ready to move forward': [
        'ready to move', 'want to move forward', 'ready to start', 'want to start now',
        'asap', 'as soon as possible',
      ],
      'Need review now': [
        'need review now', 'need it reviewed', 'urgent review', 'review this week',
        'review asap', 'review now',
      ],
    },
  },
  {
    id: 'advisory_specific_task',
    question: 'What would you want a lawyer to help with first?',
    input_type: 'single_select',
    options: [
      'Choosing the right structure',
      'Reviewing documents',
      'Splitting ownership',
      'Protecting against future problems',
      'Not sure',
    ],
    applies_to: ['business_setup_advisory'],
    tier: 'qualification',
    question_group: 'advisory',
    resolves: 'advisory_specific_task',
    decision_value: 5,
    abstraction_level: 'medium',
    required: false,
    priority: 25,
  },
  {
    id: 'advisory_timing',
    question: 'When do you need help?',
    input_type: 'single_select',
    options: [
      'No rush',
      'In the next 1-3 months',
      'This month',
      'This week',
      'Urgent',
      'Not sure',
    ],
    applies_to: ['business_setup_advisory'],
    applies_to_subtrack: ['buy_in_or_joining'],
    tier: 'qualification',
    question_group: 'advisory',
    resolves: 'advisory_timing',
    decision_value: 7,
    abstraction_level: 'medium',
    required: false,
    priority: 16,
    evidence_patterns: {
      'Urgent': [
        'this week', 'urgent', 'urgently', 'asap', 'as soon as possible',
        'right away', 'immediately', 'right now', 'today',
      ],
      'This month': [
        'this month', 'end of month', 'before the end of the month',
      ],
      'In the next 1-3 months': [
        'next few months', 'in a few months', '1-3 months', 'couple of months',
      ],
      'No rush': [
        'no rush', 'no hurry', 'whenever', 'not urgent', 'at my convenience',
      ],
    },
  },
  {
    id: 'business_activity_type',
    question: 'What kind of business are you planning to start?',
    input_type: 'single_select',
    options: [
      'Professional services',
      'Online business',
      'Retail or storefront',
      'Trades or construction',
      'Holding company or investment',
      'Not sure',
    ],
    applies_to: ['business_setup_advisory'],
    applies_to_subtrack: ['solo_setup', 'partner_setup'],
    tier: 'qualification',
    question_group: 'advisory',
    resolves: 'business_activity_type',
    decision_value: 4,
    abstraction_level: 'concrete',
    required: false,
    priority: 17,
  },
  {
    id: 'business_stage',
    question: 'How far along are you?',
    input_type: 'single_select',
    options: [
      'Just researching',
      'Planning to start soon',
      'Already operating',
      'Need to incorporate before launching',
      'Not sure',
    ],
    applies_to: ['business_setup_advisory'],
    applies_to_subtrack: ['solo_setup', 'partner_setup'],
    tier: 'qualification',
    question_group: 'advisory',
    resolves: 'business_stage',
    decision_value: 5,
    abstraction_level: 'medium',
    required: false,
    priority: 18,
    evidence_patterns: {
      'Just researching': [
        'just researching', 'just looking into', 'exploring', 'early research', 'not decided yet',
      ],
      'Already operating': [
        'already operating', 'already running', 'already started', 'currently running',
        'already in business',
      ],
      'Need to incorporate before launching': [
        'need to incorporate', 'incorporate before', 'before i launch', 'before launching',
        'need to register before',
      ],
    },
  },
  {
    id: 'setup_needs',
    question: 'What do you need help with most?',
    input_type: 'single_select',
    options: [
      'Incorporating the company',
      'Choosing the right business structure',
      'Reviewing documents',
      'Taxes or accounting setup',
      'Not sure',
    ],
    applies_to: ['business_setup_advisory'],
    applies_to_subtrack: ['solo_setup'],
    tier: 'qualification',
    question_group: 'advisory',
    resolves: 'setup_needs',
    decision_value: 5,
    abstraction_level: 'medium',
    required: false,
    priority: 19,
    evidence_patterns: {
      'Incorporating the company': [
        'incorporate', 'incorporation', 'register the company', 'registration',
        'basic guidance', 'just need guidance',
      ],
      'Reviewing documents': [
        'review documents', 'review the documents', 'check documents',
      ],
    },
  },
  {
    id: 'ownership_split_discussed',
    question: 'Have you discussed how ownership, responsibilities, or profits would be split?',
    input_type: 'single_select',
    options: ['Yes', 'No', 'Not sure'],
    applies_to: ['business_setup_advisory'],
    applies_to_subtrack: ['partner_setup'],
    tier: 'qualification',
    question_group: 'advisory',
    resolves: 'ownership',
    decision_value: 6,
    abstraction_level: 'medium',
    required: false,
    priority: 20,
    evidence_patterns: {
      'Yes': [
        'discussed ownership', 'talked about ownership', 'agreed on split',
        'split ownership', 'ownership split', '50/50', '60/40',
      ],
      'No': [
        "haven't discussed", 'not discussed', 'not talked about', "haven't talked about",
      ],
    },
  },
  {
    id: 'business_location',
    question: 'Which city or region will the business be based in?',
    input_type: 'free_text',
    applies_to: ['business_setup_advisory'],
    tier: 'qualification',
    question_group: 'advisory',
    resolves: 'business_location',
    decision_value: 3,
    abstraction_level: 'concrete',
    required: false,
    priority: 23,
  },
  {
    id: 'revenue_expectation',
    question: 'What kind of revenue do you expect in the first year?',
    input_type: 'single_select',
    options: [
      'Under $30,000 (small or part-time)',
      '$30,000–$100,000 (full-time, sole operator)',
      '$100,000–$500,000 (small team or busy practice)',
      'Over $500,000 (early-stage business with momentum)',
      'Not sure yet',
    ],
    applies_to: ['business_setup_advisory'],
    tier: 'core',
    question_group: 'advisory',
    resolves: 'revenue_expectation',
    decision_value: 8,
    abstraction_level: 'concrete',
    required: true,
    priority: 24,
  },
  {
    id: 'employees_planned',
    question: 'Are you planning to hire anyone in the first year?',
    input_type: 'single_select',
    options: [
      'No, just me',
      'Maybe one or two contractors',
      'Yes, one or two employees',
      'Yes, three or more employees',
      'Not sure yet',
    ],
    applies_to: ['business_setup_advisory'],
    tier: 'core',
    question_group: 'advisory',
    resolves: 'employees_planned',
    decision_value: 7,
    abstraction_level: 'concrete',
    required: true,
    priority: 25,
  },
  {
    id: 'regulated_industry',
    question: 'Is your industry regulated?',
    input_type: 'single_select',
    options: [
      'No, general services or products',
      'Yes, health or medical',
      'Yes, financial or investment',
      'Yes, food or alcohol',
      'Yes, legal or professional licensing',
      'Yes, other regulated area',
      'Not sure',
    ],
    applies_to: ['business_setup_advisory'],
    tier: 'core',
    question_group: 'advisory',
    resolves: 'regulated_industry',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: true,
    priority: 26,
  },
  {
    id: 'cross_border_work',
    question: 'Will you sell to or work with clients outside Canada?',
    input_type: 'single_select',
    options: [
      'No, Canada only',
      'Mostly US clients',
      'Mostly other international',
      'Mixed Canadian and foreign',
      'Not sure yet',
    ],
    applies_to: ['business_setup_advisory'],
    tier: 'core',
    question_group: 'advisory',
    resolves: 'cross_border_work',
    decision_value: 8,
    abstraction_level: 'concrete',
    required: true,
    priority: 27,
  },
  {
    id: 'ip_planned',
    question: 'Do you have brand, software, or other intellectual property to protect?',
    input_type: 'single_select',
    options: [
      'No, services only',
      'Yes, a brand name or logo to protect',
      'Yes, software, code, or formulas',
      'Yes, multiple types of IP',
      'Not sure',
    ],
    applies_to: ['business_setup_advisory'],
    tier: 'core',
    question_group: 'advisory',
    resolves: 'ip_planned',
    decision_value: 6,
    abstraction_level: 'concrete',
    required: false,
    priority: 28,
  },
  // ─── SHAREHOLDER DISPUTE ──────────────────────────────────────────────────

  {
    id: 'client_role',
    question: 'Which best describes you in this situation?',
    input_type: 'single_select',
    options: ['Shareholder', 'Director/officer', 'Business partner', 'Employee', 'Not sure'],
    applies_to: ['shareholder_dispute'],
    tier: 'core',
    question_group: 'standing',
    resolves: 'ownership',
    decision_value: 5,
    abstraction_level: 'concrete',
    required: false,
    priority: 30,
    evidence_patterns: {
      'Shareholder': ['shareholder', 'share holder', 'own shares', 'owns shares', 'have shares'],
      'Business partner': ['business partner', 'partner', 'cofounder', 'co-founder', 'co owner', 'co-owner'],
      'Director/officer': ['director', 'officer', 'president', 'secretary', 'treasurer'],
    },
  },
  {
    id: 'counterparty_type',
    question: 'Who is the issue with?',
    input_type: 'single_select',
    options: ['Business partner', 'Cofounder', 'Other shareholder', 'Company management', 'Not sure'],
    applies_to: ['shareholder_dispute'],
    tier: 'core',
    question_group: 'standing',
    resolves: 'ownership',
    decision_value: 4,
    abstraction_level: 'concrete',
    required: false,
    priority: 31,
  },
  {
    id: 'ownership_percentage',
    question: 'What percentage of the company do you own, if you know?',
    input_type: 'free_text',
    applies_to: ['shareholder_dispute'],
    tier: 'core',
    question_group: 'standing',
    resolves: 'ownership',
    decision_value: 8,
    abstraction_level: 'concrete',
    required: false,
    priority: 32,
    evidence_patterns: {
      'known': ['%', 'percent', 'half', '50', '33', '25', '40', '60', 'equal shares'],
    },
  },
  {
    id: 'proof_of_ownership',
    question: 'Do you have any documents, emails, or messages showing your ownership or decision-making role in the company?',
    input_type: 'single_select',
    options: ['Yes', 'No', 'Not sure'],
    applies_to: ['shareholder_dispute'],
    tier: 'proof',
    question_group: 'ownership_proof',
    resolves: 'ownership_proof',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: false,
    priority: 33,
    evidence_patterns: {
      'Yes': [
        'have documents', 'have emails', 'have messages', 'have records',
        'shareholder agreement', 'share certificate', 'ownership documents',
        'i have proof', 'i have evidence',
      ],
      'No': ['no documents', 'nothing in writing', 'no proof', 'no evidence', 'no records'],
    },
  },
  {
    id: 'shareholder_agreement',
    question: 'Do you have a shareholder agreement or any ownership documents?',
    input_type: 'single_select',
    options: ['Yes', 'No', 'Not sure'],
    applies_to: ['shareholder_dispute'],
    tier: 'proof',
    question_group: 'ownership_proof',
    resolves: 'ownership_proof',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: false,
    priority: 34,
    evidence_patterns: {
      'Yes': [
        'shareholder agreement', 'shareholders agreement', 'share certificate',
        'certificate of shares', 'ownership agreement', 'ownership documents',
        'have an agreement', 'signed agreement',
      ],
      'No': ['no agreement', 'no shareholder agreement', 'no documents', 'nothing signed', 'handshake deal', 'verbal agreement'],
    },
  },
  {
    id: 'corporate_records_available',
    question: "Do you have access to the company's financial records or bank accounts?",
    input_type: 'single_select',
    options: ['Yes', 'No', 'Partial access', 'Not sure'],
    applies_to: ['shareholder_dispute'],
    tier: 'core',
    question_group: 'access_proof',
    resolves: 'access',
    decision_value: 10,
    abstraction_level: 'concrete',
    required: false,
    priority: 28,
    evidence_patterns: {
      'No': [
        "can't access", 'cannot access', 'locked out', 'no access', 'blocked',
        "can't see", 'cannot see', "won't show me", 'not showing me',
        "can't access the bank", 'locked out of the bank', 'changed bank access',
        'bank account access', 'removed from bank', 'taken off',
        "won't show records", "won't show me anything",
      ],
      'Partial access': ['partial access', 'some access', 'limited access'],
      'Yes': ['have access', 'can access', 'can see the records', 'access to records'],
    },
  },
  {
    id: 'management_exclusion',
    question: 'Has your partner restricted your access to company decisions, records, or accounts?',
    input_type: 'single_select',
    options: ['Yes', 'No', 'Not sure'],
    applies_to: ['shareholder_dispute'],
    tier: 'core',
    question_group: 'control',
    resolves: 'access',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: false,
    priority: 29,
    evidence_patterns: {
      'Yes': [
        'making decisions without me', 'left out', 'excluding me', 'excluded',
        'without telling me', 'not telling me', 'keeping me out', 'being pushed out',
        'locked out', 'restricted access', 'changed passwords',
      ],
    },
  },
  {
    id: 'dividend_or_money_issue',
    question: "Is company money being taken or used in a way you don't agree with?",
    input_type: 'single_select',
    options: ['Yes', 'No', 'Not sure'],
    applies_to: ['shareholder_dispute'],
    tier: 'core',
    question_group: 'control',
    resolves: 'money_misuse',
    decision_value: 10,
    abstraction_level: 'concrete',
    required: false,
    priority: 27,
    evidence_patterns: {
      'Yes': [
        'taking money', 'took money', 'hiding money', 'money missing', 'company money',
        'siphoning', 'draining the company', 'unauthorized withdrawals',
        'money being taken', 'misusing funds', 'personal use',
        'i think money is being taken', 'money is being taken out',
      ],
    },
  },
  {
    id: 'company_profitable',
    question: 'Is the company profitable or holding meaningful assets?',
    input_type: 'single_select',
    options: ['Yes', 'No', 'Not sure'],
    applies_to: ['shareholder_dispute'],
    tier: 'strategic',
    question_group: 'value',
    resolves: 'value',
    decision_value: 8,
    abstraction_level: 'medium',
    required: false,
    priority: 35,
    evidence_patterns: {
      'Yes': ['profitable', 'making money', 'generating revenue', 'has assets', 'has value', 'real business', 'active business', 'significant assets'],
      'No': ['not profitable', 'losing money', 'no revenue', 'no assets', 'broke', 'not making money'],
    },
  },
  {
    id: 'deadlock_status',
    question: 'Is the business deadlocked or unable to make decisions?',
    input_type: 'single_select',
    options: ['Yes', 'No', 'Not sure'],
    applies_to: ['shareholder_dispute'],
    tier: 'strategic',
    question_group: 'risk',
    resolves: 'risk',
    decision_value: 7,
    abstraction_level: 'medium',
    required: false,
    priority: 36,
  },
  {
    id: 'desired_outcome_shareholder_dispute',
    question: 'What would be the best outcome for you?',
    input_type: 'single_select',
    options: [
      'Recover money taken from the company',
      'Regain access to records or accounts',
      'Stop unauthorized decisions',
      'Negotiate a buyout or exit',
      'Resolve ownership/control dispute',
      'Not sure',
    ],
    applies_to: ['shareholder_dispute'],
    tier: 'qualification',
    question_group: 'status',
    resolves: 'none',
    decision_value: 3,
    abstraction_level: 'medium',
    required: false,
    priority: 40,
  },

  // ─── UNPAID INVOICE ───────────────────────────────────────────────────────

  {
    id: 'amount_at_stake',
    question: 'About how much money is involved?',
    input_type: 'single_select',
    options: ['Under $5,000', '$5,000–$25,000', '$25,000–$100,000', 'Over $100,000', 'Not sure'],
    applies_to: ['unpaid_invoice', 'contract_dispute', 'vendor_supplier_dispute'],
    tier: 'core',
    question_group: 'value',
    resolves: 'value',
    decision_value: 10,
    abstraction_level: 'concrete',
    required: false,
    priority: 50,
    evidence_patterns: {
      'Under $5,000': ['under $5,000', 'under 5000', 'less than $5,000', 'small amount', 'a few hundred', 'under five thousand'],
      '$5,000–$25,000': ['$10,000', '$15,000', '$20,000', 'ten thousand', 'fifteen thousand', 'twenty thousand', '5000', '10000', '15000', '20000'],
      '$25,000–$100,000': ['$50,000', '$75,000', '$30,000', 'fifty thousand', 'thirty thousand'],
      'Over $100,000': ['over $100,000', 'over 100,000', 'six figures', 'hundred thousand', '$200,000', '$500,000'],
    },
  },
  {
    id: 'invoice_exists',
    question: 'Do you have an invoice, bill, or statement showing what is owed?',
    input_type: 'single_select',
    options: ['Yes', 'No', 'Not sure'],
    applies_to: ['unpaid_invoice'],
    tier: 'proof',
    question_group: 'payment_proof',
    resolves: 'payment',
    decision_value: 8,
    abstraction_level: 'concrete',
    required: false,
    priority: 51,
    evidence_patterns: {
      'Yes': ['invoice', 'sent an invoice', 'have an invoice', 'bill', 'statement', 'billing statement'],
      'No': ['no invoice', 'no bill', 'verbal', 'no documentation'],
    },
  },
  {
    id: 'payment_status',
    question: 'Has any of the amount been paid?',
    input_type: 'single_select',
    options: ['Nothing paid', 'Partially paid', 'Disputed — claims they paid', 'Not sure'],
    applies_to: ['unpaid_invoice'],
    tier: 'proof',
    question_group: 'payment_proof',
    resolves: 'payment',
    decision_value: 7,
    abstraction_level: 'concrete',
    required: false,
    priority: 52,
    evidence_patterns: {
      'Nothing paid': [
        'not paying', "hasn't paid", "haven't paid", 'not paid', 'owes me',
        'owes us', 'outstanding', 'unpaid', 'zero payment', 'no payment',
      ],
      'Partially paid': ['partially paid', 'partial payment', 'some payment', 'paid some', 'paid part', 'partial'],
      'Disputed — claims they paid': ['says they paid', 'claims they paid', 'says it was paid', 'disputes the amount', 'denies the debt'],
    },
  },
  {
    id: 'proof_of_performance',
    question: 'Do you have anything showing the work, goods, or services were delivered?',
    input_type: 'single_select',
    options: ['Yes', 'No', 'Not sure'],
    applies_to: ['unpaid_invoice'],
    tier: 'proof',
    question_group: 'delivery_proof',
    resolves: 'delivery_proof',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: false,
    priority: 53,
    evidence_patterns: {
      'Yes': [
        'delivery confirmation', 'signed off', 'proof of delivery', 'receipt',
        'completion certificate', 'they accepted', 'they approved', 'evidence of delivery',
        'can show the work was done', 'have records',
      ],
      'No': ['no proof', 'no delivery confirmation', 'no receipt', 'no records'],
    },
  },
  {
    id: 'dispute_reason',
    question: 'What is the other side saying about why they are not paying?',
    input_type: 'single_select',
    options: [
      'Says work was not done properly',
      'Says there was no agreement',
      'Says they already paid',
      'No clear reason',
      'Not sure',
    ],
    applies_to: ['unpaid_invoice', 'contract_dispute'],
    tier: 'core',
    question_group: 'risk',
    resolves: 'risk',
    decision_value: 8,
    abstraction_level: 'concrete',
    required: false,
    priority: 54,
    evidence_patterns: {
      'Says work was not done properly': [
        'says the work was bad', 'quality issue', 'not done properly', 'bad work',
        'defective', 'incomplete work', 'work was not done right', "wasn't done right",
        'work not done', "claims it wasn't done",
      ],
      'Says there was no agreement': [
        'says there was no agreement', 'denies the agreement', 'denies everything',
        'deny everything', 'denying everything', 'no agreement', 'says no contract',
      ],
      'Says they already paid': ['says they already paid', 'claims they paid', 'insists they paid'],
      'No clear reason': ['no reason', 'not explaining', 'silent', 'just delaying', 'ignoring', 'giving excuses', 'keeps delaying'],
    },
  },
  {
    id: 'desired_outcome_unpaid_invoice',
    question: 'What would be the best outcome for you?',
    input_type: 'single_select',
    options: ['Get paid', 'Negotiate payment', 'Send demand letter', 'Start claim', 'Not sure'],
    applies_to: ['unpaid_invoice'],
    tier: 'qualification',
    question_group: 'status',
    resolves: 'none',
    decision_value: 3,
    abstraction_level: 'medium',
    required: false,
    priority: 60,
  },

  // ─── CONTRACT DISPUTE ─────────────────────────────────────────────────────

  {
    id: 'written_terms',
    question: 'Do you have anything in writing that shows what was agreed — like emails or messages?',
    input_type: 'single_select',
    options: ['Yes', 'No', 'Not sure'],
    applies_to: ['contract_dispute'],
    tier: 'proof',
    question_group: 'agreement_proof',
    resolves: 'agreement_proof',
    decision_value: 10,
    abstraction_level: 'concrete',
    required: false,
    priority: 70,
    evidence_patterns: {
      'Yes': [
        'over email', 'by email', 'email agreement', 'agreed by email', 'by text',
        'by message', 'messages', 'in writing', 'written agreement', 'contract',
        'signed', 'have emails', 'have messages', 'have a contract',
        'we agreed over email', 'agreed via email',
      ],
      'No': ['verbal', 'handshake', 'word of mouth', 'nothing in writing', 'no contract', 'no written agreement', 'oral agreement'],
    },
  },
  {
    id: 'contract_exists',
    question: 'Is there a signed contract or written agreement?',
    input_type: 'single_select',
    options: ['Yes', 'No', 'Not sure'],
    applies_to: ['contract_dispute'],
    tier: 'proof',
    question_group: 'agreement_proof',
    resolves: 'agreement_proof',
    decision_value: 10,
    abstraction_level: 'concrete',
    required: false,
    priority: 71,
    evidence_patterns: {
      'Yes': ['signed contract', 'formal contract', 'have a contract', 'agreement in place', 'we have a contract', 'signed agreement'],
      'No': ['no contract', 'no formal contract', 'nothing signed', 'just emails'],
    },
  },
  {
    id: 'communications_exist',
    question: 'Do you have any written communication about what was agreed?',
    input_type: 'single_select',
    options: ['Yes', 'No', 'Not sure'],
    applies_to: ['contract_dispute'],
    tier: 'proof',
    question_group: 'agreement_proof',
    resolves: 'agreement_proof',
    decision_value: 4,
    abstraction_level: 'abstract',
    required: false,
    priority: 90,
  },
  {
    id: 'desired_outcome_contract',
    question: 'What would be the best outcome for you?',
    input_type: 'single_select',
    options: ['Enforce agreement', 'Recover damages', 'Stop the other side from breaching', 'Negotiate settlement', 'Not sure'],
    applies_to: ['contract_dispute'],
    tier: 'qualification',
    question_group: 'status',
    resolves: 'none',
    decision_value: 3,
    abstraction_level: 'medium',
    required: false,
    priority: 80,
  },

  // ─── VENDOR / SUPPLIER DISPUTE ────────────────────────────────────────────

  {
    id: 'vendor_type',
    question: 'Who is the billing dispute with?',
    input_type: 'single_select',
    options: [
      'A supplier of goods',
      'A service provider',
      'A software or subscription vendor',
      'A contractor or subcontractor',
      'Another type of vendor',
      'Not sure',
    ],
    applies_to: ['vendor_supplier_dispute'],
    tier: 'core',
    question_group: 'vendor',
    resolves: 'vendor_billing',
    decision_value: 8,
    abstraction_level: 'concrete',
    required: false,
    priority: 55,
    evidence_patterns: {
      'A supplier of goods': ['supplier', 'supplier of goods', 'goods supplier', 'product supplier'],
      'A service provider': ['service provider', 'professional services'],
      'A software or subscription vendor': ['software', 'saas', 'subscription', 'software vendor', 'platform'],
      'A contractor or subcontractor': ['contractor', 'subcontractor', 'consultant'],
    },
  },
  {
    id: 'billing_dispute_reason',
    question: 'What is the billing dispute about?',
    input_type: 'single_select',
    options: [
      'Overcharged for services or goods received',
      'Charged for something we did not receive',
      'Dispute over contract terms or pricing',
      'Unauthorized or unexpected charges',
      'Subscription or renewal dispute',
      'Other',
    ],
    applies_to: ['vendor_supplier_dispute'],
    tier: 'core',
    question_group: 'risk',
    resolves: 'risk',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: false,
    priority: 56,
    evidence_patterns: {
      'Overcharged for services or goods received': ['overcharged', 'overbilled', 'charged too much', 'wrong amount', 'billed incorrectly', 'vendor billed wrong'],
      'Charged for something we did not receive': ['charged for something we didn\'t receive', 'not received', 'never delivered', 'did not receive', 'billed for undelivered'],
      'Unauthorized or unexpected charges': ['unauthorized charge', 'unexpected charge', 'charged without approval', 'charged without consent'],
      'Subscription or renewal dispute': ['subscription dispute', 'renewal dispute', 'auto-renewal', 'cancelled subscription', 'did not renew'],
    },
  },
  {
    id: 'vendor_contract_exists',
    question: 'Do you have a contract, agreement, or terms of service with this vendor?',
    input_type: 'single_select',
    options: ['Yes, a signed contract', 'Yes, terms of service or a purchase order', 'No formal agreement', 'Not sure'],
    applies_to: ['vendor_supplier_dispute'],
    tier: 'proof',
    question_group: 'agreement_proof',
    resolves: 'agreement_proof',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: false,
    priority: 57,
    evidence_patterns: {
      'Yes, a signed contract': ['signed contract with vendor', 'vendor contract', 'have a contract with them'],
      'Yes, terms of service or a purchase order': ['terms of service', 'purchase order', 'po', 'click-through agreement'],
      'No formal agreement': ['no contract', 'verbal agreement with vendor', 'no written agreement'],
    },
  },
  {
    id: 'vendor_services_received',
    question: 'Were the goods or services you are disputing actually delivered or performed?',
    input_type: 'single_select',
    options: ['Yes, fully delivered', 'Partially delivered', 'Not delivered', 'Disputed', 'Not sure'],
    applies_to: ['vendor_supplier_dispute'],
    tier: 'proof',
    question_group: 'delivery_proof',
    resolves: 'delivery_proof',
    decision_value: 8,
    abstraction_level: 'concrete',
    required: false,
    priority: 58,
    evidence_patterns: {
      'Not delivered': ['not delivered', 'never received', 'not received', 'did not deliver'],
      'Partially delivered': ['partially delivered', 'partial delivery', 'some delivered', 'incomplete delivery'],
      'Yes, fully delivered': ['fully delivered', 'was delivered', 'received everything', 'goods received'],
    },
  },
  {
    id: 'desired_outcome_vendor',
    question: 'What would be the best outcome for you?',
    input_type: 'single_select',
    options: ['Refund or credit', 'Correct invoice and pay proper amount', 'Terminate the vendor relationship', 'Damages for losses caused', 'Not sure'],
    applies_to: ['vendor_supplier_dispute'],
    tier: 'qualification',
    question_group: 'status',
    resolves: 'none',
    decision_value: 3,
    abstraction_level: 'medium',
    required: false,
    priority: 65,
  },

  // ─── CORPORATE MONEY / CONTROL ────────────────────────────────────────────

  {
    id: 'reporter_role_money',
    question: 'What is your role in the company?',
    input_type: 'single_select',
    options: [
      'Owner or shareholder',
      'Director or officer',
      'Employee or manager',
      'Accountant or bookkeeper',
      'Other',
    ],
    applies_to: ['corporate_money_control'],
    tier: 'core',
    question_group: 'company_role_group',
    resolves: 'company_role',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: false,
    priority: 41,
    evidence_patterns: {
      'Owner or shareholder': ['owner', 'shareholder', 'co-owner', 'partner'],
      'Director or officer': ['director', 'officer', 'president'],
      'Employee or manager': ['employee', 'i work for', 'staff member', 'manager'],
      'Accountant or bookkeeper': ['accountant', 'bookkeeper', 'cpa', 'comptroller', 'as the accountant', 'as a bookkeeper'],
    },
  },
  {
    id: 'irregularity_type',
    question: 'What type of financial concern do you have?',
    input_type: 'single_select',
    options: [
      'Money appears to be missing or unaccounted for',
      'Unauthorized payments or transfers',
      'Fraudulent or inflated invoices',
      'Someone is misusing company accounts or cards',
      'Other',
    ],
    applies_to: ['corporate_money_control'],
    tier: 'core',
    question_group: 'irregularity',
    resolves: 'financial_irregularity',
    decision_value: 10,
    abstraction_level: 'concrete',
    required: false,
    priority: 42,
    evidence_patterns: {
      'Money appears to be missing or unaccounted for': ['money missing', 'unaccounted', 'funds missing', 'missing from accounts', 'cannot account for'],
      'Unauthorized payments or transfers': ['unauthorized payment', 'unauthorized transfer', 'unauthorized wire', 'transfer without approval'],
      'Fraudulent or inflated invoices': ['fraudulent invoice', 'fake invoice', 'inflated invoice', 'embezzlement', 'embezzled'],
      'Someone is misusing company accounts or cards': ['misusing company card', 'personal use of company', 'using company money personally'],
    },
  },
  {
    id: 'irregularity_amount',
    question: 'Do you have an estimate of how much money may be involved?',
    input_type: 'single_select',
    options: ['Under $10,000', '$10,000–$50,000', '$50,000–$200,000', 'Over $200,000', 'Unknown'],
    applies_to: ['corporate_money_control'],
    tier: 'core',
    question_group: 'value',
    resolves: 'value',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: false,
    priority: 43,
  },
  {
    id: 'evidence_of_irregularity',
    question: 'Do you have any records, statements, or documents showing the irregularity?',
    input_type: 'single_select',
    options: ['Yes', 'No', 'Not sure'],
    applies_to: ['corporate_money_control'],
    tier: 'proof',
    question_group: 'irregularity',
    resolves: 'irregularity_evidence',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: false,
    priority: 44,
    evidence_patterns: {
      'Yes': ['have records', 'have statements', 'bank statements', 'have evidence', 'have documents', 'have proof'],
      'No': ['no records', 'no evidence', 'nothing documented'],
    },
  },
  {
    id: 'reported_to_anyone',
    question: 'Has this been reported to anyone — police, accountant, other directors, or your board?',
    input_type: 'single_select',
    options: ['Yes, reported', 'No, not yet', 'In progress', 'Not sure'],
    applies_to: ['corporate_money_control'],
    tier: 'strategic',
    question_group: 'risk',
    resolves: 'risk',
    decision_value: 7,
    abstraction_level: 'medium',
    required: false,
    priority: 45,
  },
  {
    id: 'desired_outcome_money_control',
    question: 'What outcome are you looking for?',
    input_type: 'single_select',
    options: ['Recover the missing money', 'Stop the misuse', 'Internal investigation', 'Report to authorities', 'Not sure'],
    applies_to: ['corporate_money_control'],
    tier: 'qualification',
    question_group: 'status',
    resolves: 'none',
    decision_value: 3,
    abstraction_level: 'medium',
    required: false,
    priority: 49,
  },

  // ─── REAL ESTATE GENERAL (intermediate routing lane) ─────────────────────

  {
    id: 'real_estate_problem_type',
    question: 'What best describes what you need help with?',
    input_type: 'single_select',
    options: [
      'Buying or selling commercial property',
      'Buying or selling a home or condo',
      'A real estate deal that has gone wrong (deposit, closing, misrepresentation)',
      'A landlord or tenant dispute',
      'Unpaid construction or renovation work',
      'A pre-construction condo or new build issue',
      'A mortgage or power-of-sale issue',
      'Something else',
    ],
    applies_to: ['real_estate_general'],
    tier: 'core',
    question_group: 'routing',
    resolves: 'real_estate_subtype',
    decision_value: 15,
    abstraction_level: 'concrete',
    required: true,
    priority: 1,
  },

  // ─── COMMERCIAL REAL ESTATE ──────────────────────────────────────────────

  {
    id: 'commercial_re_role',
    question: 'Are you the buyer, seller, landlord, or tenant?',
    input_type: 'single_select',
    options: ['Buyer', 'Seller', 'Landlord', 'Tenant', 'Investor', 'Not sure'],
    applies_to: ['commercial_real_estate'],
    tier: 'core',
    question_group: 'parties',
    resolves: 'party_role',
    decision_value: 12,
    abstraction_level: 'concrete',
    required: true,
    priority: 2,
    evidence_patterns: {
      'Buyer': ['buying', 'we are buying', 'i am buying', 'on the buying side'],
      'Seller': ['selling', 'we are selling', 'i am selling', 'on the selling side'],
      'Landlord': ['as landlord', 'leasing out', 'leasing to'],
      'Tenant': ['leasing from', 'as tenant', 'taking a lease'],
      'Investor': ['investment property', 'investor'],
    },
  },
  {
    id: 'commercial_property_type',
    question: 'What type of commercial property is involved?',
    input_type: 'single_select',
    options: ['Office', 'Retail / storefront', 'Industrial / warehouse', 'Mixed-use', 'Multi-residential / apartment building', 'Land / development site', 'Not sure'],
    applies_to: ['commercial_real_estate'],
    tier: 'core',
    question_group: 'property',
    resolves: 'property_type',
    decision_value: 10,
    abstraction_level: 'concrete',
    required: true,
    priority: 4,
    evidence_patterns: {
      'Office': ['office space', 'office building'],
      'Retail / storefront': ['retail space', 'storefront', 'plaza unit', 'shop space'],
      'Industrial / warehouse': ['industrial', 'warehouse'],
      'Mixed-use': ['mixed use', 'mixed-use'],
      'Multi-residential / apartment building': ['apartment building', 'multi residential', 'multi-residential'],
      'Land / development site': ['vacant land', 'development site', 'land for development'],
    },
  },
  {
    id: 'commercial_re_amount',
    question: 'What is the approximate transaction or lease value?',
    input_type: 'single_select',
    options: ['Under $500,000', '$500,000–$2M', '$2M–$10M', 'Over $10M', 'Not sure'],
    applies_to: ['commercial_real_estate'],
    tier: 'core',
    question_group: 'value',
    resolves: 'value',
    decision_value: 14,
    abstraction_level: 'concrete',
    required: true,
    priority: 3,
  },
  {
    id: 'commercial_re_stage',
    question: 'Where are you in the deal?',
    input_type: 'single_select',
    options: ['Just exploring', 'Talking with the other side', 'Signed an offer or letter of intent', 'Conditions still to clear', 'Closing date set', 'Already closed', 'Not sure'],
    applies_to: ['commercial_real_estate'],
    tier: 'core',
    question_group: 'transaction_stage',
    resolves: 'transaction_stage',
    decision_value: 11,
    abstraction_level: 'concrete',
    required: true,
    priority: 5,
    evidence_patterns: {
      'Signed an offer or letter of intent': ['signed an aps', 'signed the aps', 'loi signed', 'letter of intent', 'signed an offer'],
      'Closing date set': ['closing date', 'set to close', 'closing in', 'closing next'],
      'Already closed': ['already closed', 'we closed', 'closing completed'],
    },
  },
  {
    id: 'commercial_re_concerns',
    question: 'What concern brought you to a lawyer?',
    input_type: 'single_select',
    options: ['Reviewing the agreement', 'Title or zoning concern', 'Environmental concern', 'Financing or mortgage', 'Tenant or lease structure', 'Not sure yet'],
    applies_to: ['commercial_real_estate'],
    tier: 'strategic',
    question_group: 'risk',
    resolves: 'risk',
    decision_value: 7,
    abstraction_level: 'medium',
    required: false,
    priority: 18,
  },

  // ─── RESIDENTIAL PURCHASE / SALE ─────────────────────────────────────────

  {
    id: 'residential_role',
    question: 'Are you buying or selling?',
    input_type: 'single_select',
    options: ['Buying', 'Selling', 'Both (buying and selling)', 'Not sure'],
    applies_to: ['residential_purchase_sale'],
    tier: 'core',
    question_group: 'parties',
    resolves: 'party_role',
    decision_value: 10,
    abstraction_level: 'concrete',
    required: true,
    priority: 2,
    evidence_patterns: {
      'Buying': ['buying a house', 'buying a home', 'buying a condo', 'buying my first', 'about to buy'],
      'Selling': ['selling my house', 'selling my home', 'selling my condo', 'about to sell', 'listing my'],
    },
  },
  {
    id: 'residential_property_type',
    question: 'What type of property?',
    input_type: 'single_select',
    options: ['Detached / semi-detached', 'Townhouse', 'Condo', 'Pre-construction unit', 'Vacant land', 'Not sure'],
    applies_to: ['residential_purchase_sale'],
    tier: 'core',
    question_group: 'property',
    resolves: 'property_type',
    decision_value: 8,
    abstraction_level: 'concrete',
    required: true,
    priority: 5,
  },
  {
    id: 'residential_re_amount',
    question: 'What is the approximate property value?',
    input_type: 'single_select',
    options: ['Under $500,000', '$500,000–$1M', '$1M–$2M', 'Over $2M', 'Not sure'],
    applies_to: ['residential_purchase_sale'],
    tier: 'core',
    question_group: 'value',
    resolves: 'value',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: true,
    priority: 3,
  },
  {
    id: 'residential_re_stage',
    question: 'Where are you in the process?',
    input_type: 'single_select',
    options: ['Just exploring', 'Offer not yet made', 'Offer accepted, still working through conditions', 'Deal is locked, closing soon', 'Closing this week, urgent', 'Already closed', 'Not sure'],
    applies_to: ['residential_purchase_sale'],
    tier: 'core',
    question_group: 'transaction_stage',
    resolves: 'transaction_stage',
    decision_value: 10,
    abstraction_level: 'concrete',
    required: true,
    priority: 4,
  },
  {
    id: 'residential_re_concern',
    question: 'What do you need help with most?',
    input_type: 'single_select',
    options: ['Reviewing the contract before signing', 'Title and closing paperwork', 'Mortgage and financing', 'Conditions or guarantees', 'Something has gone wrong at closing', 'Not sure yet'],
    applies_to: ['residential_purchase_sale'],
    tier: 'core',
    question_group: 'risk',
    resolves: 'risk',
    decision_value: 5,
    abstraction_level: 'medium',
    required: true,
    priority: 20,
  },
  {
    id: 'residential_closing_timeline',
    question: 'When is the closing?',
    input_type: 'single_select',
    options: [
      'No firm date yet',
      'More than 60 days away',
      '30 to 60 days away',
      'Less than 30 days away',
      'This week',
      'Already passed (closing was missed)',
      'Not sure',
    ],
    applies_to: ['residential_purchase_sale'],
    tier: 'core',
    question_group: 'transaction_stage',
    resolves: 'closing_timeline',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: true,
    priority: 21,
  },
  {
    id: 'residential_mortgage_situation',
    question: 'Where are you with financing?',
    input_type: 'single_select',
    options: [
      'Pre-approved',
      'Approved with conditions still open',
      'Application submitted, no answer yet',
      'Cash purchase, no financing',
      'Private or alternative lender',
      'Not started',
    ],
    applies_to: ['residential_purchase_sale'],
    tier: 'core',
    question_group: 'transaction_stage',
    resolves: 'mortgage_situation',
    decision_value: 8,
    abstraction_level: 'concrete',
    required: true,
    priority: 22,
  },
  {
    id: 'residential_representation',
    question: 'Do you have a real estate agent involved?',
    input_type: 'single_select',
    options: ['Yes, I have an agent', 'No, dealing with the other side directly', 'No, the seller has an agent and I do not', 'Not sure'],
    applies_to: ['residential_purchase_sale'],
    tier: 'qualification',
    question_group: 'parties',
    resolves: 'representation_status',
    decision_value: 4,
    abstraction_level: 'concrete',
    required: false,
    priority: 23,
  },

  // ─── REAL ESTATE LITIGATION ──────────────────────────────────────────────

  {
    id: 'litigation_subject',
    question: 'What is the dispute about?',
    input_type: 'single_select',
    options: [
      'The other side did not close the deal',
      'Deposit was lost or is being kept',
      'Seller hid problems or misrepresented the property',
      'Title or boundary problem',
      'Disagreement over use of land (easement)',
      'Real estate fraud',
      'Not sure',
    ],
    applies_to: ['real_estate_litigation'],
    tier: 'core',
    question_group: 'status',
    resolves: 'litigation_subject',
    decision_value: 14,
    abstraction_level: 'concrete',
    required: true,
    priority: 2,
    evidence_patterns: {
      'The other side did not close the deal': ['failed to close', 'walked away', 'failed closing'],
      'Deposit was lost or is being kept': ['lost deposit', 'deposit dispute', 'deposit refund'],
      'Seller hid problems or misrepresented the property': ['misrepresentation', 'undisclosed defect', 'hidden defect', 'latent defect'],
      'Title or boundary problem': ['title dispute', 'boundary dispute', 'title problem'],
      'Disagreement over use of land (easement)': ['easement dispute', 'easement issue'],
      'Real estate fraud': ['real estate fraud', 'title fraud'],
    },
  },
  {
    id: 'litigation_role',
    question: 'What is your role in the dispute?',
    input_type: 'single_select',
    options: ['Buyer', 'Seller', 'Property owner', 'Neighbour', 'Investor', 'Not sure'],
    applies_to: ['real_estate_litigation'],
    tier: 'core',
    question_group: 'parties',
    resolves: 'party_role',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: true,
    priority: 4,
  },
  {
    id: 'litigation_amount',
    question: 'What is roughly at stake?',
    input_type: 'single_select',
    options: ['Under $25,000', '$25,000–$100,000', '$100,000–$500,000', 'Over $500,000', 'Not sure'],
    applies_to: ['real_estate_litigation'],
    tier: 'core',
    question_group: 'value',
    resolves: 'value',
    decision_value: 13,
    abstraction_level: 'concrete',
    required: true,
    priority: 3,
  },
  {
    id: 'litigation_documents',
    question: 'Do you have the agreement of purchase and sale or other written contract?',
    input_type: 'single_select',
    options: ['Yes', 'No', 'Some, but only drafts or partial', 'Not sure'],
    applies_to: ['real_estate_litigation'],
    tier: 'proof',
    question_group: 'agreement_proof',
    resolves: 'agreement_proof',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: true,
    priority: 6,
  },
  {
    id: 'litigation_stage',
    question: 'Has anything been filed in court yet?',
    input_type: 'single_select',
    options: ['No, not yet', "A lawyer's letter has been sent", 'Already in court (we filed)', 'Already in court (we were served)', 'Not sure'],
    applies_to: ['real_estate_litigation'],
    tier: 'core',
    question_group: 'status',
    resolves: 'risk',
    decision_value: 7,
    abstraction_level: 'concrete',
    required: true,
    priority: 16,
  },
  {
    id: 'litigation_when_event',
    question: 'When did the issue happen or come to light?',
    input_type: 'single_select',
    options: [
      'In the last 30 days',
      'Within the last 6 months',
      '6 months to 2 years ago',
      'Over 2 years ago',
      'Not sure',
    ],
    applies_to: ['real_estate_litigation'],
    tier: 'core',
    question_group: 'status',
    resolves: 'limitation_concern',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: true,
    priority: 17,
  },
  {
    id: 'litigation_settlement_attempted',
    question: 'Has there been any attempt to settle so far?',
    input_type: 'single_select',
    options: [
      'No contact yet',
      'Informal conversations only',
      'Demand letters exchanged',
      'Mediation attempted, did not resolve',
      'Settlement offer on the table',
      'Not sure',
    ],
    applies_to: ['real_estate_litigation'],
    tier: 'core',
    question_group: 'status',
    resolves: 'settlement_attempted',
    decision_value: 7,
    abstraction_level: 'concrete',
    required: true,
    priority: 18,
  },

  // ─── LANDLORD / TENANT ───────────────────────────────────────────────────

  {
    id: 'tenancy_party',
    question: 'Are you the landlord or the tenant?',
    input_type: 'single_select',
    options: ['Landlord', 'Tenant', 'Property manager', 'Not sure'],
    applies_to: ['landlord_tenant'],
    tier: 'core',
    question_group: 'parties',
    resolves: 'party_role',
    decision_value: 12,
    abstraction_level: 'concrete',
    required: true,
    priority: 2,
    evidence_patterns: {
      'Landlord': ['as landlord', 'i am the landlord', 'we are the landlord', 'my tenant'],
      'Tenant': ['as tenant', 'i am the tenant', 'my landlord'],
      'Property manager': ['property manager', 'managing the building'],
    },
  },
  {
    id: 'tenancy_type',
    question: 'Is this a residential or commercial tenancy?',
    input_type: 'single_select',
    options: ['Residential (house, condo, apartment)', 'Commercial (office, retail, industrial)', 'Mixed', 'Not sure'],
    applies_to: ['landlord_tenant'],
    tier: 'core',
    question_group: 'tenancy_terms',
    resolves: 'tenancy_type',
    decision_value: 12,
    abstraction_level: 'concrete',
    required: true,
    priority: 3,
    evidence_patterns: {
      'Residential (house, condo, apartment)': ['residential lease', 'residential tenant', 'apartment'],
      'Commercial (office, retail, industrial)': ['commercial lease', 'commercial tenant', 'office lease', 'retail lease'],
    },
  },
  {
    id: 'tenancy_issue',
    question: 'What is the dispute about?',
    input_type: 'single_select',
    options: [
      'Unpaid rent',
      'Eviction or possession',
      'Lease terms or breach',
      'Damage or repairs',
      'Illegal use / nuisance',
      'Other',
    ],
    applies_to: ['landlord_tenant'],
    tier: 'core',
    question_group: 'tenancy_dispute',
    resolves: 'tenancy_issue',
    decision_value: 10,
    abstraction_level: 'concrete',
    required: true,
    priority: 4,
    evidence_patterns: {
      'Unpaid rent': ['unpaid rent', 'tenant won\'t pay', 'tenant not paying', 'rent arrears'],
      'Eviction or possession': ['eviction', 'evict', 'evicted', 'won\'t leave', 'overhold'],
      'Lease terms or breach': ['breach of lease', 'lease dispute', 'breaking the lease'],
      'Damage or repairs': ['damage to the property', 'damage to my unit', 'repairs not done'],
    },
  },
  {
    id: 'tenancy_amount',
    question: 'How much rent or damages are involved?',
    input_type: 'single_select',
    options: ['Under $5,000', '$5,000–$25,000', '$25,000–$100,000', 'Over $100,000', 'Not sure'],
    applies_to: ['landlord_tenant'],
    tier: 'core',
    question_group: 'value',
    resolves: 'value',
    decision_value: 8,
    abstraction_level: 'concrete',
    required: true,
    priority: 5,
  },
  {
    id: 'tenancy_lease_exists',
    question: 'Is there a written lease?',
    input_type: 'single_select',
    options: ['Yes', 'No', 'Verbal only', 'Not sure'],
    applies_to: ['landlord_tenant'],
    tier: 'proof',
    question_group: 'agreement_proof',
    resolves: 'lease_proof',
    decision_value: 7,
    abstraction_level: 'concrete',
    required: true,
    priority: 7,
  },
  {
    id: 'tenancy_notice_status',
    question: 'Has formal notice been given or any application started?',
    input_type: 'single_select',
    options: ['No, nothing started', 'Formal notice given to the other side', 'Application filed at the Landlord and Tenant Board', 'Court action started (commercial)', 'Not sure'],
    applies_to: ['landlord_tenant'],
    tier: 'strategic',
    question_group: 'status',
    resolves: 'risk',
    decision_value: 6,
    abstraction_level: 'medium',
    required: false,
    priority: 14,
  },

  // ─── CONSTRUCTION LIEN ───────────────────────────────────────────────────

  {
    id: 'lien_role',
    question: 'What is your role on the project?',
    input_type: 'single_select',
    options: ['Property owner', 'General contractor', 'Subcontractor or trade', 'Supplier of materials', 'Architect or consultant', 'Not sure'],
    applies_to: ['construction_lien'],
    tier: 'core',
    question_group: 'parties',
    resolves: 'party_role',
    decision_value: 12,
    abstraction_level: 'concrete',
    required: true,
    priority: 2,
  },
  {
    id: 'lien_amount',
    question: 'How much is owed?',
    input_type: 'single_select',
    options: ['Under $25,000', '$25,000–$100,000', '$100,000–$500,000', 'Over $500,000', 'Not sure'],
    applies_to: ['construction_lien'],
    tier: 'core',
    question_group: 'value',
    resolves: 'value',
    decision_value: 14,
    abstraction_level: 'concrete',
    required: true,
    priority: 3,
  },
  {
    id: 'lien_last_supply',
    question: 'When did you last supply work or materials to the project?',
    input_type: 'single_select',
    options: ['Within the last 60 days', '60–90 days ago', 'More than 90 days ago', 'Not sure'],
    applies_to: ['construction_lien'],
    tier: 'core',
    question_group: 'lien',
    resolves: 'lien_timing',
    decision_value: 15,
    abstraction_level: 'concrete',
    required: true,
    priority: 4,
  },
  {
    id: 'lien_preserved',
    question: 'Has a claim against the property been registered yet?',
    input_type: 'single_select',
    options: ['Yes, a claim was registered', 'Yes, registered and a court action started', 'No, nothing registered yet', 'Not sure'],
    applies_to: ['construction_lien'],
    tier: 'proof',
    question_group: 'lien',
    resolves: 'lien_evidence',
    decision_value: 12,
    abstraction_level: 'concrete',
    required: true,
    priority: 6,
  },
  {
    id: 'lien_documents',
    question: 'Do you have the contract, invoices, and proof of work?',
    input_type: 'single_select',
    options: ['Yes, all three', 'Some paperwork, not all', 'It was a verbal agreement', 'Not sure'],
    applies_to: ['construction_lien'],
    tier: 'proof',
    question_group: 'agreement_proof',
    resolves: 'agreement_proof',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: true,
    priority: 8,
  },

  // ─── PRECONSTRUCTION CONDO ───────────────────────────────────────────────

  {
    id: 'precon_role',
    question: 'What is your role?',
    input_type: 'single_select',
    options: ['I am the original buyer', 'I am taking over a unit from someone else', 'I am selling my unit before closing', 'I bought multiple units (investor)', 'Not sure'],
    applies_to: ['preconstruction_condo'],
    tier: 'core',
    question_group: 'parties',
    resolves: 'party_role',
    decision_value: 10,
    abstraction_level: 'concrete',
    required: true,
    priority: 2,
    evidence_patterns: {
      'Assignee (taking over a unit)': ['taking over a unit', 'buying an assignment', 'assignee'],
      'Assignor (selling my unit)': ['assigning my unit', 'selling my preconstruction', 'assignor'],
    },
  },
  {
    id: 'precon_issue',
    question: 'What is the issue?',
    input_type: 'single_select',
    options: [
      'Builder keeps delaying closing',
      'Worried about my deposit',
      'Trouble selling my unit before closing',
      'New-home warranty issue (Tarion)',
      'Reviewing the contract before signing',
      'Builder hid problems or misrepresented the unit',
      'Other',
    ],
    applies_to: ['preconstruction_condo'],
    tier: 'core',
    question_group: 'preconstruction',
    resolves: 'litigation_subject',
    decision_value: 13,
    abstraction_level: 'concrete',
    required: true,
    priority: 3,
    evidence_patterns: {
      'Delayed closing or occupancy': ['delayed closing', 'occupancy delay', 'extended closing'],
      'Deposit at risk': ['condo deposit', 'deposit at risk', 'deposit dispute'],
      'Assignment dispute or fee': ['assignment fee', 'assignment dispute'],
      'Tarion warranty issue': ['tarion'],
    },
  },
  {
    id: 'precon_developer_status',
    question: 'How is the developer responding?',
    input_type: 'single_select',
    options: ['Refusing or stalling', 'Offering a settlement', 'No response', 'Not sure'],
    applies_to: ['preconstruction_condo'],
    tier: 'core',
    question_group: 'status',
    resolves: 'developer_status',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: true,
    priority: 6,
  },
  {
    id: 'precon_amount',
    question: 'How much is at stake?',
    input_type: 'single_select',
    options: ['Under $50,000', '$50,000–$200,000', 'Over $200,000', 'Not sure'],
    applies_to: ['preconstruction_condo'],
    tier: 'core',
    question_group: 'value',
    resolves: 'value',
    decision_value: 11,
    abstraction_level: 'concrete',
    required: true,
    priority: 5,
  },
  {
    id: 'precon_documents',
    question: 'Do you have the agreement of purchase and sale with the builder?',
    input_type: 'single_select',
    options: ['Yes', 'No', 'Partial', 'Not sure'],
    applies_to: ['preconstruction_condo'],
    tier: 'proof',
    question_group: 'agreement_proof',
    resolves: 'agreement_proof',
    decision_value: 9,
    abstraction_level: 'concrete',
    required: true,
    priority: 7,
  },

  // ─── MORTGAGE DISPUTE ────────────────────────────────────────────────────

  {
    id: 'mortgage_role',
    question: 'What is your position in this matter?',
    input_type: 'single_select',
    options: ['I am the borrower (property owner)', 'I am the lender', 'I co-signed or guaranteed the loan', 'I am another involved party', 'Not sure'],
    applies_to: ['mortgage_dispute'],
    tier: 'core',
    question_group: 'parties',
    resolves: 'party_role',
    decision_value: 11,
    abstraction_level: 'concrete',
    required: true,
    priority: 2,
  },
  {
    id: 'mortgage_status',
    question: 'What is happening right now?',
    input_type: 'single_select',
    options: [
      'Lender is threatening to call the mortgage',
      'I received a Notice of Sale',
      'The lender has started the power-of-sale process',
      'Disagreement over refinancing',
      'Issue with paying off or discharging the mortgage',
      'Other',
    ],
    applies_to: ['mortgage_dispute'],
    tier: 'core',
    question_group: 'status',
    resolves: 'mortgage_status',
    decision_value: 14,
    abstraction_level: 'concrete',
    required: true,
    priority: 3,
    evidence_patterns: {
      'Lender threatening default': ['lender threatening', 'mortgage arrears', 'default notice'],
      'Notice of Sale received': ['notice of sale'],
      'Power-of-sale process started': ['power of sale'],
    },
  },
  {
    id: 'mortgage_amount',
    question: 'What is the approximate mortgage balance or amount in dispute?',
    input_type: 'single_select',
    options: ['Under $250,000', '$250,000–$1M', '$1M–$5M', 'Over $5M', 'Not sure'],
    applies_to: ['mortgage_dispute'],
    tier: 'core',
    question_group: 'value',
    resolves: 'value',
    decision_value: 11,
    abstraction_level: 'concrete',
    required: true,
    priority: 4,
  },
  {
    id: 'mortgage_lender_type',
    question: 'What kind of lender?',
    input_type: 'single_select',
    options: ['A bank or major institution', 'A private lender', 'A credit union', 'A mortgage investment company', 'Not sure'],
    applies_to: ['mortgage_dispute'],
    tier: 'strategic',
    question_group: 'parties',
    resolves: 'risk',
    decision_value: 6,
    abstraction_level: 'medium',
    required: false,
    priority: 12,
  },
  {
    id: 'mortgage_documents',
    question: 'Do you have the mortgage documents and any notices received?',
    input_type: 'single_select',
    options: ['Yes', 'Some', 'No', 'Not sure'],
    applies_to: ['mortgage_dispute'],
    tier: 'proof',
    question_group: 'agreement_proof',
    resolves: 'agreement_proof',
    decision_value: 8,
    abstraction_level: 'concrete',
    required: true,
    priority: 8,
  },

  // ─── UNIVERSAL READINESS (asked at the end of every matter chain) ────────

  {
    id: 'hiring_timeline',
    question: 'When are you hoping to have a lawyer working on this?',
    input_type: 'single_select',
    options: [
      'Now (this week)',
      'Within the next 30 days',
      'Within the next few months',
      'Just exploring, no timeline yet',
      'Not sure',
    ],
    applies_to: [
      'business_setup_advisory',
      'shareholder_dispute',
      'unpaid_invoice',
      'contract_dispute',
      'vendor_supplier_dispute',
      'corporate_money_control',
      'corporate_general',
      'commercial_real_estate',
      'residential_purchase_sale',
      'real_estate_litigation',
      'landlord_tenant',
      'construction_lien',
      'preconstruction_condo',
      'mortgage_dispute',
      'real_estate_general',
    ],
    tier: 'core',
    question_group: 'readiness',
    resolves: 'hiring_timeline',
    decision_value: 8,
    abstraction_level: 'concrete',
    required: true,
    priority: 95,
  },
  {
    id: 'other_counsel',
    question: 'Have you spoken to another lawyer about this matter?',
    input_type: 'single_select',
    options: [
      'No, you are the first',
      'Yes, I am comparing options',
      'Yes, switching from a previous lawyer',
      'Not sure',
    ],
    applies_to: [
      'business_setup_advisory',
      'shareholder_dispute',
      'unpaid_invoice',
      'contract_dispute',
      'vendor_supplier_dispute',
      'corporate_money_control',
      'corporate_general',
      'commercial_real_estate',
      'residential_purchase_sale',
      'real_estate_litigation',
      'landlord_tenant',
      'construction_lien',
      'preconstruction_condo',
      'mortgage_dispute',
      'real_estate_general',
    ],
    tier: 'core',
    question_group: 'readiness',
    resolves: 'other_counsel',
    decision_value: 6,
    abstraction_level: 'concrete',
    required: true,
    priority: 96,
  },
  {
    id: 'decision_authority',
    question: 'Who decides whether to hire a lawyer for this?',
    input_type: 'single_select',
    options: [
      'Just me',
      'Me with a partner or family member',
      'Multiple owners or directors',
      'Someone else decides',
      'Not sure',
    ],
    applies_to: [
      'business_setup_advisory',
      'shareholder_dispute',
      'unpaid_invoice',
      'contract_dispute',
      'vendor_supplier_dispute',
      'corporate_money_control',
      'corporate_general',
      'commercial_real_estate',
      'residential_purchase_sale',
      'real_estate_litigation',
      'landlord_tenant',
      'construction_lien',
      'preconstruction_condo',
      'mortgage_dispute',
      'real_estate_general',
    ],
    tier: 'core',
    question_group: 'readiness',
    resolves: 'decision_authority',
    decision_value: 5,
    abstraction_level: 'concrete',
    required: true,
    priority: 97,
  },
];

export function getSlotById(id: string): SlotDefinition | undefined {
  return SLOT_REGISTRY.find(s => s.id === id);
}

export function getSlotsForMatter(matterType: string): SlotDefinition[] {
  return SLOT_REGISTRY.filter(s => s.applies_to.includes(matterType as never));
}
