/** Synthetic-only fixtures. No production IDs, source paths, contacts or database operations. */
import type { JsonValue, ProspectEnrichmentAssessment, ProspectEnrichmentEnvelope, ProspectEnrichmentObservation, ProspectEnrichmentSource } from "../prospect-enrichment-contract";
import { prospectEnrichmentProtocolHash } from "../prospect-enrichment-hash";
export const ENRICHMENT_FIXTURE_OBSERVED_ON = "2026-09-23";
export const ENRICHMENT_FIXTURE_OBSERVED_AT = "2026-09-23T12:00:00.000Z";
export function prospectEnrichmentFixtureUuid(number: number) { return "00000000-0000-4000-8000-" + String(number).padStart(12, "0"); }
export type ProspectEnrichmentFixture = Readonly<{ number: number; scenario: string; canonicalFirmId: string; stableFirmId: string; envelope: ProspectEnrichmentEnvelope; variants: readonly { name: string; envelope: ProspectEnrichmentEnvelope; expectation: string }[]; expectations: readonly string[] }>;
function original(content: JsonValue): ProspectEnrichmentEnvelope["originalResearch"] { return { sourcePath: "synthetic/fixture.json", sourcePointer: "/candidate", sourceSha256: prospectEnrichmentProtocolHash({ syntheticFile: content }), contentSha256: prospectEnrichmentProtocolHash(content), content, unmappedPaths: ["/contacts", "/ownerVerified", "/unknown"] }; }
function source(number: number): ProspectEnrichmentSource { const host = "https://enrichment-fixture-" + String(number).padStart(3, "0") + ".example"; return { sourceId: "official", url: host, requestedUrl: host, finalUrl: host, policyState: "public-source", publicationLabel: null, publicationPrecision: "unknown", publisher: "Synthetic Legal " + number, observedAt: null, observedOn: ENRICHMENT_FIXTURE_OBSERVED_ON, retrievedAt: ENRICHMENT_FIXTURE_OBSERVED_AT, retrievalMethod: "synthetic-fixture", retrievalOutcome: "success", httpStatus: 200, bodySha256: prospectEnrichmentProtocolHash({ synthetic: number }), excerpt: "Synthetic Legal " + number + " is an independent Toronto law firm. Its official team, services and contact facts are synthetic evidence.", missingProvenanceReason: null }; }
function observation(kind: ProspectEnrichmentObservation["kind"], data: unknown, observationId = kind): ProspectEnrichmentObservation { return { observationId, kind, evidenceState: "asserted", retractionReason: null, retractionSourceIds: [], missingProvenanceReason: null, observedAt: null, observedOn: ENRICHMENT_FIXTURE_OBSERVED_ON, sourceIds: ["official"], data, existingRecord: null } as ProspectEnrichmentObservation; }
function assessment(number: number): ProspectEnrichmentAssessment { return { assessmentId: "synthetic-assessment-" + number, cohortId: "synthetic-1-through-10-lawyers", ruleVersion: "synthetic-v1", assessedAt: ENRICHMENT_FIXTURE_OBSERVED_AT, assessedOn: null, missingProvenanceReason: null, researchOutcome: "complete", advertisingStatus: "recent-ad-verified", advertisingStatusState: "current", fitDecision: "pass", commercialRelevance: "strong-match", decisionMakerAccess: "pass", opportunityDecision: "pass", selectionDisposition: "selected", missingGates: [], researchFailures: [], rationale: "Synthetic fixture passes only the named synthetic cohort rules.", sourceIds: ["official"], legacyCriteria: {}, existingRecord: null }; }
function base(number: number): ProspectEnrichmentEnvelope {
  const name = "Synthetic Legal " + number, domain = "enrichment-fixture-" + String(number).padStart(3, "0") + ".example";
  return { schemaVersion: "prospect-enrichment/v1", runId: "synthetic-fixture-run", packageId: "synthetic-package-" + String(number).padStart(3, "0"), supersedesPackageId: null, sourceSystem: "synthetic-fixture", sourceName: "synthetic-fixture-inventory", generatedAt: ENRICHMENT_FIXTURE_OBSERVED_AT, mode: "propose", subject: { researchKey: "enrichment-fixture-" + String(number).padStart(3, "0"), databaseFirmId: null, stableFirmId: null, sourceRecordKey: "synthetic-" + number, canonicalDomain: null, displayName: name, identityState: "unresolved" }, sources: [source(number)], observations: [
    observation("firm_fit", { practiceAreas: ["Corporate law"], office: { city: "Toronto", province: "ON", address: "Synthetic office" }, lawyerCount: 3, countQualifier: "exact", independence: "independent", fit: "pass" }),
    observation("service", { name: "Corporate law", matterFit: "strong-match" }),
    observation("roster", { lawyerCount: 3, countQualifier: "exact", display: "3 lawyers", includedNames: ["Synthetic One", "Synthetic Two", "Synthetic Three"], excludedPeople: [{ name: "Synthetic Assistant", reason: "Non-lawyer staff" }] }),
    observation("contact", { personName: "Synthetic One", roleLabel: "Managing partner", roleVerification: "first-party", contactType: "public-named-email", contactValue: "owner@" + domain, contactQuality: "published-direct-unverified", deliverability: "not-tested", roleSourceIds: ["official"] }),
    observation("advertising", { evidenceType: "direct-ad", vendor: "Synthetic ads", signalType: "advertisement", signalId: "synthetic-ad-" + number, advertiserIdentity: name, advertisedService: "Corporate law", destinationUrl: "https://" + domain, effectiveDate: ENRICHMENT_FIXTURE_OBSERVED_ON, lastShownDate: ENRICHMENT_FIXTURE_OBSERVED_ON, recencyBasis: "Synthetic observed advertisement", identityState: "confirmed", attributable: true, configured: null, fired: null }),
    observation("opportunity", { type: "intake-context-gap", observation: "Synthetic intake page offers a general form.", interpretation: "Matter context may require a follow-up.", recommendation: "Review a matter-specific context field.", strengths: ["Public contact path is visible"], unknowns: ["No form was submitted"], confidence: "medium" }),
  ], assessment: assessment(number), originalResearch: original({ candidate: name, ownerVerified: true, unknown: null, contacts: [] }), controls: { contactFormsSubmitted: false, chatSessionsStarted: false, outreachSent: false } };
}
const scenarios = ["New firm with complete core evidence", "Existing firm phone and failed direct-email lookup", "Held owner-role evidence", "Disqualified eleven-lawyer candidate", "Incomplete unknown source-less research", "Shared-domain professional corporations", "Contradiction and retracted intake finding", "Rich historical criteria and failed retrieval", "Exact duplicate and lost response", "Changed content under the same package key"];
export function createProspectEnrichmentFixtures(): readonly ProspectEnrichmentFixture[] {
  return Array.from({ length: 10 }, (_, index) => {
    const number = index + 1, canonicalFirmId = prospectEnrichmentFixtureUuid(number), stableFirmId = "FIRM-" + String(number).padStart(26, "0");
    let envelope = base(number); const variants: { name: string; envelope: ProspectEnrichmentEnvelope; expectation: string }[] = [];
    const expectations = ["Original research retained", "No contact form, chat, outreach or database call"];
    if ([2, 7, 8, 9, 10].includes(number)) envelope = { ...envelope, subject: { ...envelope.subject, databaseFirmId: canonicalFirmId, stableFirmId, canonicalDomain: "enrichment-fixture-" + String(number).padStart(3, "0") + ".example", identityState: "resolved" } };
    if (number === 1) expectations.push("One core and stable identity only after exact operator approval", "No guessed minimum core fields");
    if (number === 2) { envelope = { ...envelope, observations: [observation("contact", { personName: null, roleLabel: null, roleVerification: "not-observed", contactType: "phone", contactValue: "+1-416-555-0102", contactQuality: "general-route", deliverability: "not-applicable", roleSourceIds: [] }), observation("research_attempt", { provider: "Synthetic official-site lookup", queryOrUrl: envelope.sources[0].url, outcome: "failed", coverage: "failed", failureReason: "Synthetic direct-email lookup did not complete" })] }; expectations.push("Existing reviewed email remains unchanged", "Failed lookup is not evidence of email absence"); }
    if (number === 3) { envelope = { ...envelope, assessment: { ...assessment(number), researchOutcome: "partial", decisionMakerAccess: "unknown", selectionDisposition: "verification-required", missingGates: ["owner_role"] } }; expectations.push("No qualified or outreach promotion"); }
    if (number === 4) { envelope = { ...envelope, observations: envelope.observations.map((item) => item.kind === "roster" ? { ...item, data: { ...item.data, lawyerCount: 11, display: "11 lawyers" } } : item.kind === "firm_fit" ? { ...item, data: { ...item.data, lawyerCount: 11, fit: "fail" } } : item), assessment: { ...assessment(number), fitDecision: "fail", selectionDisposition: "disqualified", rationale: "11 observed lawyers is outside this synthetic cohort limit of 1 through 10." } }; expectations.push("Disqualification belongs only to this cohort"); }
    if (number === 5) { envelope = { ...envelope, sources: [], observations: [], assessment: { ...assessment(number), sourceIds: [], assessedAt: null, assessedOn: null, missingProvenanceReason: "Synthetic research was not performed", researchOutcome: "not_run", advertisingStatus: null, advertisingStatusState: "unknown", fitDecision: "unknown", commercialRelevance: "unknown", decisionMakerAccess: "unknown", opportunityDecision: "unknown", selectionDisposition: "verification-required", missingGates: ["roster", "owner_role", "advertising"] }, originalResearch: original({ candidate: "Synthetic Legal 5", ownerVerified: false, unknown: null, contacts: [], roster: null }) }; variants.push({ name: "source-less-original-only", envelope: { ...envelope, assessment: null }, expectation: "Zero structured items remains a valid held package" }); expectations.push("Null, absent, false and empty arrays stay distinct", "Package-only visibility does not require canonical identity"); }
    if (number === 6) { envelope = { ...envelope, subject: { ...envelope.subject, identityState: "conflict", canonicalDomain: "enrichment-fixture-006.example" } }; variants.push({ name: "second-professional-corporation", envelope: { ...envelope, packageId: envelope.packageId + "-second", subject: { ...envelope.subject, researchKey: envelope.subject.researchKey + "-second", displayName: "Synthetic Second Professional Corporation" } }, expectation: "Shared domain never implies merge" }); variants.push({ name: "foreign-domain-conflict", envelope: { ...envelope, packageId: envelope.packageId + "-foreign", sources: [{ ...source(6), url: "https://foreign.enrichment-fixture-006.example", requestedUrl: "https://foreign.enrichment-fixture-006.example", finalUrl: "https://foreign.enrichment-fixture-006.example" }] }, expectation: "Foreign evidence cannot reach an unrelated domestic UUID" }); expectations.push("Identity model conflict stays held"); }
    if (number === 7) { envelope = { ...envelope, observations: envelope.observations.map((item) => item.kind === "opportunity" ? { ...item, evidenceState: "retracted", retractionReason: "Synthetic replacement source corrected the prior intake claim", retractionSourceIds: ["official"] } : item.kind === "contact" ? { ...item, data: { ...item.data, contactValue: "changed@enrichment-fixture-007.example", roleVerification: "unverified" } } : item), assessment: { ...assessment(number), selectionDisposition: "verification-required", missingGates: ["owner_role"] } }; expectations.push("Contradictory history does not replace profile", "Retraction and replacement source stay visible"); }
    if (number === 8) { envelope = { ...envelope, sources: [{ ...source(8), publicationLabel: "2023", publicationPrecision: "year", retrievalOutcome: "failed", httpStatus: 403, excerpt: null }], observations: [observation("research_attempt", { provider: "Synthetic document", queryOrUrl: source(8).url, outcome: "http-403", coverage: "failed", failureReason: "Synthetic document retrieval denied" })], assessment: { ...assessment(number), researchOutcome: "partial", selectionDisposition: "verification-required", missingGates: ["owner_role", "advertising"], legacyCriteria: { lawyerCount: true, ownerVerified: false, status: "needs_evidence", observedLawyers: 3, unknown: null, missingGates: ["owner_role", "advertising"], evidence: { sourceUrl: "https://enrichment-fixture-008.example/team", observedOn: ENRICHMENT_FIXTURE_OBSERVED_ON } } } }; expectations.push("Published 2023 is not an observed timestamp", "Historic criteria remain parent-linked without fabricated rows"); }
    if (number === 9) { variants.push({ name: "exact-retry-lost-response", envelope: structuredClone(envelope), expectation: "Same receipt and one effective write" }, { name: "same-event-new-package", envelope: { ...envelope, packageId: envelope.packageId + "-replay" }, expectation: "Same source event links the existing target" }); expectations.push("No source-event duplicates"); }
    if (number === 10) { const changed = { ...envelope, originalResearch: original({ candidate: "Synthetic Legal 10", ownerVerified: false, unknown: null, contacts: [], revision: 2 }) }; variants.push({ name: "changed-same-package-key", envelope: changed, expectation: "409 without a mutation" }, { name: "changed-new-package-key", envelope: { ...changed, packageId: envelope.packageId + "-changed" }, expectation: "Distinct update retained for review" }, { name: "changed-source-event-content", envelope: { ...envelope, packageId: envelope.packageId + "-source-conflict", sources: [{ ...envelope.sources[0], excerpt: "Changed source content under the same source ID" }] }, expectation: "Same source event key with changed semantic hash is held" }); }
    return { number, scenario: scenarios[index], canonicalFirmId, stableFirmId, envelope, variants, expectations };
  });
}
export function createProspectEnrichmentLegacyCriteriaFixtures(): readonly Record<string, JsonValue>[] {
  return Array.from({ length: 39 }, (_, index): Record<string, JsonValue> => ({ id: prospectEnrichmentFixtureUuid(800 + index), firm_id: prospectEnrichmentFixtureUuid(8), evidence_import_batch_id: prospectEnrichmentFixtureUuid(899), assessment_id: "synthetic-legacy-" + index, qualification_state: "needs_evidence", qualification_cohort: "synthetic-v1", assessed_on: ENRICHMENT_FIXTURE_OBSERVED_ON, criteria: index < 5 ? { lawyerCount: true, ownerVerified: false } : { lawyerCount: true, ownerVerified: false, status: "needs_evidence", observedLawyers: 3, unknown: null, missingGates: ["owner_role", "advertising"], evidence: { sourceUrl: "https://enrichment-fixture-008.example/team", observedOn: ENRICHMENT_FIXTURE_OBSERVED_ON } } }));
}
