"use client";
import { useMemo, useRef, useState } from "react";
import { buildBlueprintViewModel } from "@/lib/desired-client/blueprint";
import { createMarkdownDownload, createProfileDownload } from "@/lib/desired-client/export";
import type { ClarificationCode, DesiredClientAnswers, SavedBrief } from "@/lib/desired-client/types";
import { ConfirmationDialog } from "./ConfirmationDialog";

export function BriefView({saved,answers,dismissedCode,reviewed,onReview,onEdit,onAnother,onClear,storageWarning}:{saved:SavedBrief;answers:DesiredClientAnswers;dismissedCode:ClarificationCode|null;reviewed:boolean;onReview:(v:boolean)=>void;onEdit:(stage:1|2|3|4|5|6)=>void;onAnother:()=>void;onClear:()=>void;storageWarning:boolean}){
 const [copied,setCopied]=useState(false),[copyFailed,setCopyFailed]=useState(false),[pdfFailed,setPdfFailed]=useState(false),[confirm,setConfirm]=useState<"another"|"clear"|null>(null),[busy,setBusy]=useState(false); const fallback=useRef<HTMLTextAreaElement>(null);
 const model=useMemo(()=>buildBlueprintViewModel(saved.brief,answers,{mode:saved.mode,generatedAt:saved.generatedAt,wordingReviewed:reviewed,openClarificationCode:dismissedCode??saved.openClarificationCode}),[saved,answers,reviewed,dismissedCode]);
 const text=createProfileDownload(saved,answers).content, markdown=createMarkdownDownload(saved,answers);
 async function copy(){setCopied(false);setCopyFailed(false);try{await navigator.clipboard.writeText(text);setCopied(true);}catch{setCopyFailed(true);setTimeout(()=>{fallback.current?.focus();fallback.current?.select();},0);}}
 function downloadSupporting(){const url=URL.createObjectURL(new Blob([markdown.content],{type:markdown.mimeType}));const link=document.createElement("a");link.href=url;link.download=markdown.filename;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function downloadPdf(){setPdfFailed(false);setBusy(true);try{const {downloadBlueprintPdf}=await import("@/lib/desired-client/pdf-export");await downloadBlueprintPdf(model,saved,answers);}catch{setPdfFailed(true);}finally{setBusy(false);}}
 const b=saved.brief;
 return <article className="dc-brief" data-ui-component-content="desired-client-brief">
  <header className="dc-brief__header"><h1 data-ui-copy="heading">Desired Client Blueprint</h1><p data-ui-copy="supporting">{model.status}{model.provisional?" · Provisional direction":""} · AI-assisted working draft · {model.date}</p></header>
  {storageWarning&&<p className="dc-alert" data-ui-copy="supporting">This browser could not save your progress. You can still finish and download your blueprint.</p>}
  <section className="dc-profile" data-ui-component-content="desired-client-profile"><h2 data-ui-copy="heading">Desired client portrait</h2><p className="dc-profile__definition" data-ui-copy="body">{b.portrait.text}</p><div className="dc-blueprint-context">{[["CLIENT CONTEXT",model.context.client],["STARTING POINT",model.context.startingPoint],["WORK TO ATTRACT",model.context.work]].map(([label,value])=><section key={label}><h3 data-ui-copy="supporting">{label}</h3><p data-ui-copy="body">{value}</p></section>)}</div></section>
  <div className="dc-blueprint-columns"><section className="dc-brief__section"><h2 data-ui-copy="heading">Client need</h2><p data-ui-copy="body">{b.client_need.text}</p></section><section className="dc-brief__section"><h2 data-ui-copy="heading">Firm value</h2><p data-ui-copy="body">{b.firm_value.text}</p></section></div>
  <section className="dc-brief__section"><h2 data-ui-copy="heading">Marketing direction</h2><dl className="dc-fact-row"><dt data-ui-copy="supporting">Message</dt><dd data-ui-copy="body">{b.marketing.message.text}</dd></dl><dl className="dc-fact-row"><dt data-ui-copy="supporting">Content idea</dt><dd data-ui-copy="body">{b.marketing.content.text}</dd></dl><dl className="dc-fact-row"><dt data-ui-copy="supporting">Next step</dt><dd data-ui-copy="body">{b.marketing.next_step.text}</dd></dl></section>
  <section className="dc-brief__section"><h2 data-ui-copy="heading">Proposed Screen questions</h2><div className="dc-screen-table"><div className="dc-screen-table__head"><span>Signal</span><span>Ask or establish</span><span>Use</span></div>{model.screens.rows.map(row=><div className="dc-screen-table__row" key={row.id}><h3 data-ui-copy="heading">{row.label}</h3><div data-ui-copy="body"><p>{row.ask_summary}</p><details><summary>Questions and desired conditions</summary><ul>{row.questions.map(q=><li key={q.id}>{q.question}{q.desired_condition?` Desired: ${q.desired_condition}`:""}</li>)}</ul></details></div><p data-ui-copy="supporting">{row.use_summary}</p></div>)}</div><p data-ui-copy="supporting">Missing information calls for clarification. These proposed checks do not activate scoring or decide whether to accept a matter.</p></section>
  <section className="dc-brief__section"><h2 data-ui-copy="heading">Still to confirm</h2>{model.stillToConfirm.length?model.stillToConfirm.map(n=><p key={n} data-ui-copy="body">{n}</p>):<p data-ui-copy="body">No unresolved questions identified. Test this profile against actual client and delivery evidence.</p>}{model.allNotes.length>2&&<details open><summary>Further notes</summary><ul>{model.allNotes.slice(2).map(n=><li key={n}>{n}</li>)}</ul></details>}</section>
  <details className="dc-brief__section" open><summary data-ui-copy="heading">Answers and sources</summary><p>Evidence: {model.evidence.length?model.evidence.join("; "):"No client evidence selected"}. Based on information supplied by the firm.</p>{model.sourceDetails.map(slot=><section key={slot.slot}><h3>{slot.slot}</h3><p>{slot.statement.text} <span className="dc-kind">{slot.statement.kind}</span></p><ul>{slot.answers.map(source=><li key={source.path}>{source.question}: {source.answer??"Not supplied"}</li>)}</ul></section>)}<h3>All selected answers</h3><ul>{model.allAnswers.map((answer,i)=><li key={`${i}-${answer.question}`}>{answer.question}: {answer.answer}</li>)}</ul></details>
  <p className="dc-footnote" data-ui-copy="body">Based on your answers. Marketing direction and proposed inquiry checks; a lawyer decides whether to accept an individual matter.</p>
  <p data-ui-copy="body">Does this describe the client and work you want more of?</p><label className="dc-reviewed"><input type="checkbox" disabled={busy} checked={reviewed} onChange={e=>onReview(e.currentTarget.checked)}/><span>I have reviewed this wording and the proposed inquiry checks.</span></label><p data-ui-copy="supporting">This confirms your review of the profile. Screen settings are not changed.</p>
  {copied&&<p role="status">Profile copied.</p>}{copyFailed&&<><p role="status">The profile could not be copied automatically. Select and copy the profile text below.</p><textarea ref={fallback} aria-label="Select and copy profile" readOnly value={text}/></>}
  {pdfFailed&&<p className="dc-alert" role="status">The PDF could not be prepared. Your answers are still saved. Use the supporting detail download or try again.</p>}
  <div className="dc-actions dc-brief__actions"><button className="dc-button dc-button--primary" disabled={busy} onClick={downloadPdf}>{busy?"Preparing PDF…":"Download one-page PDF"}</button><button className="dc-button dc-button--secondary" disabled={busy} onClick={copy}>Copy profile</button><button className="dc-button dc-button--secondary" disabled={busy} onClick={downloadSupporting}>Download supporting detail</button><button className="dc-button dc-button--secondary" disabled={busy} onClick={()=>window.print()}>Print profile</button></div>
  <div className="dc-actions" aria-label="Edit profile answers">{([[1,"Focus"],[2,"Situation"],[3,"Client goal"],[4,"Value"],[5,"Delivery"],[6,"Direction"]] as const).map(([stage,label])=><button key={stage} className="dc-button dc-button--secondary" disabled={busy} onClick={()=>onEdit(stage)}>Edit {label}</button>)}</div>
  <div className="dc-actions"><button className="dc-button dc-button--secondary" disabled={busy} onClick={()=>setConfirm("another")}>Start another</button><button className="dc-button dc-button--secondary" disabled={busy} onClick={()=>setConfirm("clear")}>Clear draft</button></div>
  {confirm&&<ConfirmationDialog open onClose={()=>setConfirm(null)} labelledBy="dc-confirm-title"><h2 id="dc-confirm-title">{confirm==="another"?"Replace the draft saved in this browser?":"Clear the draft and brief saved in this browser?"}</h2>{confirm==="another"&&<p>Download your profile first if you want to keep a copy.</p>}<button className="dc-button dc-button--primary" onClick={()=>{confirm==="another"?onAnother():onClear();setConfirm(null);}}>{confirm==="another"?"Replace draft":"Clear draft"}</button><button className="dc-button dc-button--secondary" onClick={()=>setConfirm(null)}>Keep draft</button></ConfirmationDialog>}
 </article>;
}
