import { Document, Font, Page, StyleSheet, Text, View } from "@react-pdf/renderer";
import type { BlueprintViewModel } from "@/lib/desired-client/blueprint";

Font.register({family:"Manrope",src:"/fonts/Manrope-VF.ttf"});
Font.register({family:"Oxanium",src:"/fonts/Oxanium-VF.ttf"});
const s=StyleSheet.create({page:{padding:36,fontFamily:"Manrope",fontSize:10.3,lineHeight:1.28,color:"#172033",backgroundColor:"#FFFFFF"},header:{borderBottomWidth:1,borderBottomColor:"#C4B49A",paddingBottom:8,marginBottom:9},title:{fontSize:18,fontWeight:700,color:"#1E2F58"},meta:{fontSize:10,marginTop:3,color:"#49536A"},label:{fontFamily:"Oxanium",fontSize:10,color:"#1E2F58",letterSpacing:.4,marginBottom:4},heading:{fontSize:11.5,fontWeight:700,color:"#1E2F58",marginBottom:4},section:{marginBottom:9},portrait:{fontSize:11,lineHeight:1.3},band:{flexDirection:"row",backgroundColor:"#F4F3EF",padding:8,marginBottom:9},bandCol:{width:"33.33%",paddingRight:7},value:{fontSize:10.2,lineHeight:1.25},twoCol:{flexDirection:"row",gap:12,marginBottom:8},half:{width:"50%"},marketing:{borderTopWidth:1,borderTopColor:"#D3D5DA",paddingTop:5},marketingRow:{marginBottom:4},table:{borderWidth:.5,borderColor:"#B8BDC7",marginTop:4},tableHead:{flexDirection:"row",backgroundColor:"#1E2F58",color:"#FFFFFF",padding:5},tableRow:{flexDirection:"row",borderTopWidth:.5,borderColor:"#D4D6DC",padding:5},cell1:{width:"20%",paddingRight:4},cell2:{width:"50%",paddingRight:5},cell3:{width:"30%"},cellText:{fontSize:10,lineHeight:1.22},note:{fontSize:10,lineHeight:1.2,marginTop:4},footer:{marginTop:6,paddingTop:6,borderTopWidth:1,borderTopColor:"#C4B49A",fontSize:10,lineHeight:1.2},badge:{backgroundColor:"#F4F3EF",padding:6,marginTop:5}});
export function DesiredClientBlueprintPdf({model}:{model:BlueprintViewModel}){const b=model.brief;return <Document><Page size="LETTER" style={s.page} wrap>
 <View style={s.header}><Text style={s.title}>{model.title}</Text><Text style={s.meta}>{model.status}{model.provisional?" · Provisional direction":""} · {model.modeLabel} · {model.date}</Text></View>
 <View style={s.section}><Text style={s.label}>DESIRED CLIENT PORTRAIT</Text><Text style={s.portrait}>{b.portrait.text}</Text></View>
 <View style={s.band}>{([["CLIENT CONTEXT",model.context.client],["STARTING POINT",model.context.startingPoint],["WORK TO ATTRACT",model.context.work]] as const).map(([label,value])=><View style={s.bandCol} key={label}><Text style={s.label}>{label}</Text><Text style={s.value}>{value}</Text></View>)}</View>
 <View style={s.twoCol}><View style={[s.half,s.section]}><Text style={s.heading}>Client need</Text><Text>{b.client_need.text}</Text></View><View style={[s.half,s.section]}><Text style={s.heading}>Firm value</Text><Text>{b.firm_value.text}</Text></View></View>
 <View style={s.section}><Text style={s.heading}>Marketing direction</Text>{[["Message",b.marketing.message.text],["Content idea",b.marketing.content.text],["Next step",b.marketing.next_step.text]].map(([label,text])=><View style={s.marketingRow} key={label}><Text style={s.label}>{label.toUpperCase()}</Text><Text>{text}</Text></View>)}</View>
 <View style={s.section}><Text style={s.heading}>Proposed Screen questions</Text><View style={s.table}><View style={s.tableHead}><Text style={[s.cell1,s.cellText]}>Signal</Text><Text style={[s.cell2,s.cellText]}>Ask or establish</Text><Text style={[s.cell3,s.cellText]}>Use</Text></View>{model.screens.rows.map(row=><View style={s.tableRow} key={row.id}><Text style={[s.cell1,s.cellText]}>{row.label}</Text><Text style={[s.cell2,s.cellText]}>{row.ask_summary}</Text><Text style={[s.cell3,s.cellText]}>{row.use_summary}</Text></View>)}</View><Text style={s.note}>Missing information calls for clarification. These proposed checks do not activate scoring or decide whether to accept a matter.</Text></View>
 <View style={s.section}><Text style={s.heading}>Still to confirm</Text>{(model.stillToConfirm.length?model.stillToConfirm:["No unresolved questions identified. Test this profile against actual client and delivery evidence."]).map((n,i)=><Text key={i} style={s.note}>• {n}</Text>)}{model.allNotes.length>2&&<Text style={s.note}>Further notes are in the supporting detail.</Text>}</View>
 <View style={s.badge}><Text style={s.meta}>Evidence: {model.evidence.length?model.evidence.join("; "):"No client evidence selected"}. Based on information supplied by the firm.</Text><Text style={s.meta}>{model.status}</Text></View>
 <Text style={s.footer}>Based on your answers. Marketing direction and proposed inquiry checks; a lawyer decides whether to accept an individual matter.</Text>
 </Page></Document>}
