/**
 * GET   /api/portal/[firmId]/matters/[matterId]/embed
 *   → returns the matter's embed_url (or null) for client rendering.
 *
 * PATCH /api/portal/[firmId]/matters/[matterId]/embed
 *   body { embed_url: string | null }
 *   → lawyer sets the embed URL for this matter. Validated against
 *     the firm's embed_origins allow-list (CSP).
 *
 * S8 Phase 1 Story 16: minimal per-matter iframe embed slot. No
 * auth bridge — the firm provides a pre-authenticated URL (signed
 * token, time-limited, generated by their own system). Phase 2
 * extends this to a guided picker; Phase 1 ships the data model
 * and the validation rules so embeds can land without a follow-up
 * migration.
 */

import { NextRequest, NextResponse } from 'next/server';
import {
  getFirmSession,
  getClientMatterSession,
} from '@/lib/portal-auth';
import { supabaseAdmin as supabase } from '@/lib/supabase-admin';
import { getMatterById } from '@/lib/matter-stage';

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ firmId: string; matterId: string }> },
) {
  const { firmId, matterId } = await params;
  // Either the lawyer OR the client can read the embed_url (the
  // client renders it inside their matter home; the lawyer can
  // inspect it to verify what the client sees).
  const lawyerSession = await getFirmSession(firmId);
  const clientSession = lawyerSession
    ? null
    : await getClientMatterSession(firmId, matterId);

  if (!lawyerSession && !clientSession) {
    return NextResponse.json({ error: 'unauthenticated' }, { status: 401 });
  }

  const matter = await getMatterById(matterId);
  if (!matter || matter.firm_id !== firmId) {
    return NextResponse.json({ error: 'matter not found' }, { status: 404 });
  }

  return NextResponse.json({
    ok: true,
    matter_id: matterId,
    embed_url: matter.embed_url,
  });
}

export async function PATCH(
  req: NextRequest,
  { params }: { params: Promise<{ firmId: string; matterId: string }> },
) {
  const { firmId, matterId } = await params;
  const session = await getFirmSession(firmId);
  if (!session) {
    return NextResponse.json({ error: 'unauthenticated' }, { status: 401 });
  }

  let body: { embed_url?: unknown };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: 'invalid JSON body' }, { status: 400 });
  }

  // null is permitted (clears the embed)
  if (body.embed_url !== null && typeof body.embed_url !== 'string') {
    return NextResponse.json(
      { error: 'body.embed_url must be a string URL or null' },
      { status: 400 },
    );
  }

  const matter = await getMatterById(matterId);
  if (!matter || matter.firm_id !== firmId) {
    return NextResponse.json({ error: 'matter not found' }, { status: 404 });
  }

  // Validate the URL against the firm's embed_origins allow-list.
  // The allow-list stores origin prefixes (e.g.
  // "https://app.somefirm.com"). The URL must START with one of
  // them. Empty allow-list means embeds are not configured for the
  // firm and the PATCH is rejected. null URL (clear) bypasses
  // validation.
  if (body.embed_url !== null) {
    const url = body.embed_url as string;
    const parsed = safeParseUrl(url);
    if (!parsed || (parsed.protocol !== 'https:' && parsed.protocol !== 'http:')) {
      return NextResponse.json(
        { error: 'embed_url must be a valid http(s) URL' },
        { status: 400 },
      );
    }

    const { data: firm } = await supabase
      .from('intake_firms')
      .select('embed_origins')
      .eq('id', firmId)
      .maybeSingle();

    const allowedOrigins = Array.isArray(firm?.embed_origins) ? (firm!.embed_origins as string[]) : [];
    if (allowedOrigins.length === 0) {
      return NextResponse.json(
        {
          error: 'embed_origins is not configured for this firm; add allowed origins before setting embed URLs',
        },
        { status: 422 },
      );
    }

    const origin = `${parsed.protocol}//${parsed.host}`;
    const allowed = allowedOrigins.some(
      (allowedOrigin) => origin === allowedOrigin || url.startsWith(allowedOrigin),
    );
    if (!allowed) {
      return NextResponse.json(
        {
          error: `embed_url origin "${origin}" is not in the firm's embed_origins allow-list`,
          allowed_origins: allowedOrigins,
        },
        { status: 422 },
      );
    }
  }

  const { error: updateErr } = await supabase
    .from('client_matters')
    .update({ embed_url: body.embed_url })
    .eq('id', matterId);

  if (updateErr) {
    return NextResponse.json({ error: updateErr.message }, { status: 500 });
  }

  return NextResponse.json({
    ok: true,
    matter_id: matterId,
    embed_url: body.embed_url,
  });
}

function safeParseUrl(s: string): URL | null {
  try {
    return new URL(s);
  } catch {
    return null;
  }
}
