-- Publication Readiness, Workstream 2 + foundation of Workstream 7/8.
--
-- publication_artifacts is the version-bound ledger of real, verified
-- publication evidence: an image, a PDF, a deployed webpage, a sent email,
-- a thank-you page, a form, or a record of an external post (LinkedIn/GBP).
-- It is ADDITIVE to, not a replacement for, the single-asset-per-version
-- columns already on deliverable_versions (storage_path, asset_mime,
-- asset_size_bytes, asset_name, asset_sha256, asset_validation, added by
-- 20260713185808_pdf_artifact_integrity.sql, already live in production).
-- Those columns remain the canonical binding for a deliverable's OWN
-- single lead-magnet PDF; publication_artifacts exists because a single
-- deliverable version can need SEVERAL artifacts at once (a Counsel Note
-- needs a hero image AND a deployed webpage; a GBP post needs a campaign
-- image AND a record of the actual external post), which the flat
-- deliverable_versions columns cannot represent.
--
-- Trigger and RLS pattern copied deliberately from the most recent
-- precedent in this schema, deliverable_suggestions
-- (production migration versions 20260713234759_deliverable_suggestions /
-- 20260714011950_deliverable_suggestion_release_hardening, tracked pending
-- rename on origin/feat/deliverable-suggestions-release): a
-- before-insert scope-validation trigger, a before-update-or-delete
-- unconditional-raise append-only trigger, RLS enabled + forced with zero
-- policies (service-role-only access, matching the Database Access
-- Invariant), SECURITY INVOKER on any RPC, explicit REVOKE ALL / GRANT
-- EXECUTE TO service_role, NOTIFY pgrst reload at the end.
--
-- superseded_at is deliberately NOT how staleness is determined. Staleness
-- is a DERIVED property computed by the readiness evaluator (Workstream 4)
-- by comparing an artifact's version_id against the deliverable's current
-- approved version. The column exists only for an administrative,
-- insert-time-only note (e.g. "this artifact was manually pulled down");
-- it is never updated on an existing row, and nothing in this system reads
-- it to decide readiness. DR-094 ("never overwrite an approved artifact,
-- preserve the prior file, hash and approval history when replacing it")
-- is honored by inserting a new row for a new version, never mutating an
-- old one.

create table if not exists public.publication_artifacts (
  id uuid primary key default gen_random_uuid(),
  firm_id uuid not null,
  deliverable_id uuid not null references public.content_deliverables(id) on delete restrict,
  version_id uuid not null references public.deliverable_versions(id) on delete restrict,
  artifact_type text not null check (artifact_type in (
    'hero_image', 'social_image', 'pdf', 'webpage', 'email',
    'thank_you_page', 'form', 'external_post'
  )),
  locale text,
  destination text check (
    destination is null or destination in ('firm_website', 'linkedin', 'google_business_profile')
  ),
  storage_bucket text,
  storage_path text,
  public_url text,
  repository text,
  repository_path text,
  deployment_commit text,
  deployment_url text,
  mime_type text,
  size_bytes integer,
  sha256 text,
  validation_result jsonb,
  created_by_role text not null check (created_by_role in ('operator', 'lawyer', 'system')),
  created_by_id uuid,
  created_at timestamptz not null default now(),
  superseded_at timestamptz,
  constraint publication_artifacts_locale_format_check
    check (locale is null or locale ~ '^[a-z]{2,3}-[A-Z]{2}$'),
  constraint publication_artifacts_sha256_format_check
    check (sha256 is null or sha256 ~ '^[0-9a-f]{64}$'),
  constraint publication_artifacts_validation_object_check
    check (validation_result is null or jsonb_typeof(validation_result) = 'object'),
  -- A durable storage-backed artifact never stores an expiring signed URL as
  -- its identity: public_url, when set for a storage-backed artifact, must
  -- be a stable public path. storage_bucket + storage_path are the durable
  -- identity; signed URLs are generated on demand at read time, never
  -- persisted here.
  constraint publication_artifacts_storage_pair_check
    check (
      (storage_bucket is null) = (storage_path is null)
    )
);

comment on table public.publication_artifacts is
  'Version-bound ledger of real publication evidence (images, PDFs, deployed webpages, emails, external posts). Never generated by this system; only registered against evidence that already exists.';
comment on column public.publication_artifacts.superseded_at is
  'Insert-time-only administrative note, never updated after insert. Readiness staleness is derived from version_id vs. the deliverable''s current approved version, not from this column.';

create index if not exists publication_artifacts_deliverable_idx
  on public.publication_artifacts (deliverable_id, version_id, artifact_type);
create index if not exists publication_artifacts_firm_idx
  on public.publication_artifacts (firm_id, created_at desc);
create index if not exists publication_artifacts_type_idx
  on public.publication_artifacts (artifact_type, locale);

create or replace function public.validate_publication_artifact_scope()
returns trigger
language plpgsql
set search_path = public
as $function$
declare
  v_deliverable_firm uuid;
  v_version_deliverable uuid;
  v_version_firm uuid;
begin
  select d.firm_id, v.deliverable_id, v.firm_id
    into v_deliverable_firm, v_version_deliverable, v_version_firm
  from public.content_deliverables d
  join public.deliverable_versions v on v.deliverable_id = d.id
  where d.id = new.deliverable_id and v.id = new.version_id;

  if not found
     or v_deliverable_firm is distinct from new.firm_id
     or v_version_deliverable is distinct from new.deliverable_id
     or v_version_firm is distinct from new.firm_id then
    raise exception 'publication artifact must reference a version from the same firm and deliverable';
  end if;
  return new;
end;
$function$;

drop trigger if exists trg_validate_publication_artifact_scope on public.publication_artifacts;
create trigger trg_validate_publication_artifact_scope
before insert on public.publication_artifacts
for each row execute function public.validate_publication_artifact_scope();

create or replace function public.block_publication_artifact_mutation()
returns trigger
language plpgsql
set search_path = public
as $function$
begin
  raise exception 'publication artifacts are append-only';
end;
$function$;

drop trigger if exists trg_block_publication_artifact_mutation on public.publication_artifacts;
create trigger trg_block_publication_artifact_mutation
before update or delete on public.publication_artifacts
for each row execute function public.block_publication_artifact_mutation();

alter table public.publication_artifacts enable row level security;
alter table public.publication_artifacts force row level security;
revoke all on public.publication_artifacts from anon, authenticated, public;

-- ---------------------------------------------------------------------------
-- publication_artifact_validations (Workstream 7 foundation): append-only
-- record of a reconciliation check run against a registered artifact
-- (storage object exists + hash/size/mime match, route responds, deployment
-- evidence resolves). Kept separate from publication_artifacts itself so
-- validation history stays auditable across repeated reconciliation runs
-- without ever mutating the artifact row it validates.
-- ---------------------------------------------------------------------------

create table if not exists public.publication_artifact_validations (
  id uuid primary key default gen_random_uuid(),
  artifact_id uuid not null references public.publication_artifacts(id) on delete restrict,
  firm_id uuid not null,
  validator text not null check (validator in (
    'storage_object_check', 'sha256_check', 'route_check', 'deployment_check'
  )),
  result text not null check (result in ('pass', 'fail', 'error')),
  details jsonb,
  validated_by_role text not null check (validated_by_role in ('operator', 'system')),
  validated_by_id uuid,
  created_at timestamptz not null default now(),
  constraint publication_artifact_validations_details_object_check
    check (details is null or jsonb_typeof(details) = 'object')
);

comment on table public.publication_artifact_validations is
  'Append-only reconciliation history for a publication artifact. Never mutates the artifact it validates.';

create index if not exists publication_artifact_validations_artifact_idx
  on public.publication_artifact_validations (artifact_id, created_at desc);
create index if not exists publication_artifact_validations_firm_idx
  on public.publication_artifact_validations (firm_id, created_at desc);

create or replace function public.validate_publication_artifact_validation_scope()
returns trigger
language plpgsql
set search_path = public
as $function$
declare
  v_artifact_firm uuid;
begin
  select firm_id into v_artifact_firm
    from public.publication_artifacts
   where id = new.artifact_id;

  if not found or v_artifact_firm is distinct from new.firm_id then
    raise exception 'artifact validation must reference an artifact from the same firm';
  end if;
  return new;
end;
$function$;

drop trigger if exists trg_validate_publication_artifact_validation_scope on public.publication_artifact_validations;
create trigger trg_validate_publication_artifact_validation_scope
before insert on public.publication_artifact_validations
for each row execute function public.validate_publication_artifact_validation_scope();

drop trigger if exists trg_block_publication_artifact_validation_mutation on public.publication_artifact_validations;
create trigger trg_block_publication_artifact_validation_mutation
before update or delete on public.publication_artifact_validations
for each row execute function public.block_publication_artifact_mutation();

alter table public.publication_artifact_validations enable row level security;
alter table public.publication_artifact_validations force row level security;
revoke all on public.publication_artifact_validations from anon, authenticated, public;

-- ---------------------------------------------------------------------------
-- Workstream 8 foundation: publication_releases / publication_release_items.
-- Data foundation only. No publish connectors, no UI authorize action in
-- this phase. publication_releases carries a mutable status (like
-- content_deliverables.status) because a release genuinely has a
-- lifecycle; its IDENTITY fields (firm_id, period_id, created_at) are
-- protected from mutation by trigger. publication_release_items is fully
-- immutable once inserted, matching "adding a newer deliverable version
-- must not rewrite an existing release snapshot": each item freezes the
-- exact version and artifact set it was created against.
-- ---------------------------------------------------------------------------

create table if not exists public.publication_releases (
  id uuid primary key default gen_random_uuid(),
  firm_id uuid not null,
  period_id uuid not null references public.content_periods(id) on delete restrict,
  status text not null default 'draft' check (status in (
    'draft', 'blocked', 'ready', 'authorized', 'publishing', 'published', 'failed', 'rolled_back'
  )),
  manifest_snapshot jsonb not null default '{}'::jsonb,
  authorized_by_role text check (authorized_by_role is null or authorized_by_role in ('operator', 'lawyer')),
  authorized_by_id uuid,
  authorized_at timestamptz,
  created_at timestamptz not null default now(),
  constraint publication_releases_manifest_object_check
    check (jsonb_typeof(manifest_snapshot) = 'object'),
  constraint publication_releases_authorization_pair_check
    check ((authorized_at is null) = (authorized_by_role is null))
);

comment on table public.publication_releases is
  'A named, period-scoped release candidate. No publish action exists yet in this phase; this is the data foundation only.';

create index if not exists publication_releases_period_idx
  on public.publication_releases (period_id, created_at desc);
create index if not exists publication_releases_firm_status_idx
  on public.publication_releases (firm_id, status);

create table if not exists public.publication_release_items (
  id uuid primary key default gen_random_uuid(),
  release_id uuid not null references public.publication_releases(id) on delete restrict,
  firm_id uuid not null,
  deliverable_id uuid not null references public.content_deliverables(id) on delete restrict,
  version_id uuid not null references public.deliverable_versions(id) on delete restrict,
  artifact_snapshot jsonb not null default '[]'::jsonb,
  readiness_snapshot jsonb not null,
  included boolean not null default true,
  exclusion_reason text,
  created_at timestamptz not null default now(),
  constraint publication_release_items_artifact_array_check
    check (jsonb_typeof(artifact_snapshot) = 'array'),
  constraint publication_release_items_readiness_object_check
    check (jsonb_typeof(readiness_snapshot) = 'object'),
  constraint publication_release_items_exclusion_pair_check
    check (included or exclusion_reason is not null)
);

comment on table public.publication_release_items is
  'Immutable per-deliverable snapshot inside a release: the exact version and artifact set as of release creation. Never rewritten by a later deliverable version.';

create index if not exists publication_release_items_release_idx
  on public.publication_release_items (release_id);
create index if not exists publication_release_items_deliverable_idx
  on public.publication_release_items (deliverable_id, version_id);

create or replace function public.validate_publication_release_item_scope()
returns trigger
language plpgsql
set search_path = public
as $function$
declare
  v_release_firm uuid;
  v_deliverable_firm uuid;
  v_version_deliverable uuid;
  v_version_firm uuid;
begin
  select firm_id into v_release_firm
    from public.publication_releases
   where id = new.release_id;
  if not found or v_release_firm is distinct from new.firm_id then
    raise exception 'release item must reference a release from the same firm';
  end if;

  select d.firm_id, v.deliverable_id, v.firm_id
    into v_deliverable_firm, v_version_deliverable, v_version_firm
  from public.content_deliverables d
  join public.deliverable_versions v on v.deliverable_id = d.id
  where d.id = new.deliverable_id and v.id = new.version_id;

  if not found
     or v_deliverable_firm is distinct from new.firm_id
     or v_version_deliverable is distinct from new.deliverable_id
     or v_version_firm is distinct from new.firm_id then
    raise exception 'release item must reference a version from the same firm and deliverable';
  end if;
  return new;
end;
$function$;

drop trigger if exists trg_validate_publication_release_item_scope on public.publication_release_items;
create trigger trg_validate_publication_release_item_scope
before insert on public.publication_release_items
for each row execute function public.validate_publication_release_item_scope();

drop trigger if exists trg_block_publication_release_item_mutation on public.publication_release_items;
create trigger trg_block_publication_release_item_mutation
before update or delete on public.publication_release_items
for each row execute function public.block_publication_artifact_mutation();

create or replace function public.block_publication_release_identity_mutation()
returns trigger
language plpgsql
set search_path = public
as $function$
begin
  if tg_op = 'DELETE' then
    raise exception 'publication releases cannot be deleted';
  end if;
  if new.firm_id is distinct from old.firm_id
     or new.period_id is distinct from old.period_id
     or new.created_at is distinct from old.created_at
     or new.id is distinct from old.id then
    raise exception 'publication release identity fields (firm_id, period_id, created_at, id) cannot change; status, manifest_snapshot, and authorization fields may';
  end if;
  return new;
end;
$function$;

drop trigger if exists trg_block_publication_release_identity_mutation on public.publication_releases;
create trigger trg_block_publication_release_identity_mutation
before update or delete on public.publication_releases
for each row execute function public.block_publication_release_identity_mutation();

alter table public.publication_releases enable row level security;
alter table public.publication_releases force row level security;
revoke all on public.publication_releases from anon, authenticated, public;

alter table public.publication_release_items enable row level security;
alter table public.publication_release_items force row level security;
revoke all on public.publication_release_items from anon, authenticated, public;

notify pgrst, 'reload schema';
