"use client";

import { useMemo, useState } from "react";
import { BRAZILIAN_LAWYER_PROSPECTS, BUCKET_LABELS, filterBrazilianProspects, type ProspectBucket } from "@/lib/prospect-intelligence";

const buckets: Array<ProspectBucket | "all"> = ["all", "explicit", "portuguese", "affiliation_review", "dnc"];
const empty = "—";
const Links = ({ urls }: { urls: readonly string[] }) => <>{urls.length ? urls.map((url) => <a key={url} className="mr-1 inline-block break-all text-blue-700 underline" href={url} target="_blank" rel="noreferrer">{url}</a>) : empty}</>;

export default function BrazilianProspects() {
  const [query, setQuery] = useState("");
  const [bucket, setBucket] = useState<ProspectBucket | "all">("explicit");
  const rows = useMemo(() => bucket === "all" ? filterBrazilianProspects(query) : filterBrazilianProspects(query, bucket), [bucket, query]);
  const reset = () => { setQuery(""); setBucket("explicit"); };
  return <div className="space-y-4">
    <div className="rounded-xl border border-gold/30 bg-white p-4"><p className="text-sm text-black/60">Research overlay only. It has no CRM import, send action, or contact enrichment. B1–B4 describe public evidence, not identity inference. Pagination is intentionally unnecessary for this 25-record reviewed set.</p><p className="mt-2 text-xs text-black/55"><span className="font-semibold">Evidence legend:</span> B1 self-identified Brazilian/Brazilian-Canadian; B2 Brazil-qualified or professionally connected; B3 firm explicitly serves Brazilian clients; B4 Portuguese-speaking only, Brazil link unconfirmed.</p><div className="mt-3 flex flex-wrap gap-2" role="tablist" aria-label="Prospect categories">{buckets.map((item) => <button key={item} type="button" aria-pressed={bucket === item} onClick={() => setBucket(item)} className={`rounded-full px-3 py-1.5 text-xs font-semibold ${bucket === item ? "bg-navy text-white" : "bg-parchment text-navy"}`}>{item === "all" ? `All (${BRAZILIAN_LAWYER_PROSPECTS.length})` : `${BUCKET_LABELS[item]} (${BRAZILIAN_LAWYER_PROSPECTS.filter((row) => row.bucket === item).length})`}</button>)}</div><div className="mt-4 flex flex-wrap items-end gap-3"><div className="min-w-60 flex-1"><label className="block text-xs font-semibold text-navy" htmlFor="prospect-search">Search person, firm, or mapped domain</label><input id="prospect-search" className="mt-1 w-full rounded-md border border-black/15 px-3 py-2 text-sm" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="e.g. Sakuraba or faurilaw" /></div><button type="button" onClick={reset} className="rounded-md border border-navy px-3 py-2 text-sm font-semibold text-navy">Reset filters</button></div></div>
    <p className="text-xs text-black/50">{rows.length} matching record{rows.length === 1 ? "" : "s"}</p>
    <div className="overflow-x-auto rounded-xl border border-black/10 bg-white" tabIndex={0} aria-label="Brazilian lawyer research results; scroll horizontally on small screens"><table className="min-w-[1080px] w-full text-left text-sm"><thead className="bg-parchment text-xs uppercase tracking-wide text-black/55"><tr><th className="p-3">Person / firm</th><th className="p-3">Evidence & review</th><th className="p-3">Public contact & provenance</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-t border-black/10 align-top"><td className="p-3"><p className="font-semibold text-navy">{row.name}</p><p className="text-black/60">{row.firm}</p><p className={`mt-2 inline-block rounded-full px-2 py-0.5 text-xs font-semibold ${row.bucket === "dnc" ? "bg-red-100 text-red-800" : row.bucket === "explicit" ? "bg-emerald-100 text-emerald-800" : "bg-amber-100 text-amber-800"}`}>{BUCKET_LABELS[row.bucket]}</p><dl className="mt-2 space-y-1 text-xs text-black/60"><div><dt className="inline font-semibold">Eligibility: </dt><dd className="inline">{row.outreachEligibility ?? empty}</dd></div><div><dt className="inline font-semibold">Source record: </dt><dd className="inline">{row.sourceRecordId ?? empty}</dd></div><div><dt className="inline font-semibold">Affiliation: </dt><dd className="inline">{row.publicContact?.status ?? row.currentPrimaryFirm ?? empty}</dd></div></dl></td><td className="p-3"><p className="font-semibold">{row.evidence}</p>{row.portugueseBrazilConnection && <p className="mt-1 text-xs text-black/60">{row.portugueseBrazilConnection.statement} <a className="text-blue-700 underline" href={row.portugueseBrazilConnection.evidenceSource} target="_blank" rel="noreferrer">evidence</a></p>}{row.unknowns.length > 0 && <p className="mt-2 text-xs text-black/55"><span className="font-semibold">Unknowns:</span> {row.unknowns.join(" ")}</p>}{row.publicContact?.practiceAreas.length ? <p className="mt-2 text-xs text-black/55"><span className="font-semibold">Practice areas:</span> {row.publicContact.practiceAreas.join(" · ")}</p> : null}</td><td className="p-3 text-xs"><p>Website: {row.website ? <a className="break-all text-blue-700 underline" href={row.website} target="_blank" rel="noreferrer">{row.website}</a> : empty}</p><p>Email: {row.email ?? empty}</p><p>Phone: {row.phone ?? empty}</p><p>LSO: {row.publicContact?.lsoNumber ?? empty} {row.publicContact?.lsoSourceUrl && <a className="text-blue-700 underline" href={row.publicContact.lsoSourceUrl} target="_blank" rel="noreferrer">source</a>}</p><p className="mt-2"><span className="font-semibold">Provenance:</span> <Links urls={row.sources} /></p>{row.domains && <p className="mt-2"><span className="font-semibold">Mapped domains:</span> <Links urls={row.domains} /></p>}</td></tr>)}</tbody></table></div>
  </div>;
}
