import { describe, expect, it } from "vitest";
import { buildDesiredClientSystemPrompt, buildDesiredClientUserPrompt, DESIRED_CLIENT_RESPONSE_SCHEMA } from "../prompt";
import { completeAnswers } from "./blueprint-helpers";
import type { AnalysisRequestEnvelope } from "../types";
const request = (): AnalysisRequestEnvelope => { const answers = completeAnswers(); answers.situation.trigger = null; answers.write_ins = { trigger: "A planned acquisition is under consideration" }; return { schemaVersion: 3, requestId: "11111111-1111-4111-8111-111111111111", answerRevision: answers.revision, reviewRunId: "22222222-2222-4222-8222-222222222222", analysisIndex: 0, aiConsent: true, answers, clarifications: [] }; };
describe("Desired Client Blueprint model prompt", () => {
  it("requires grounded synthesis, evidence distinctions, and the deterministic definition", () => { const p = buildDesiredClientSystemPrompt(); expect(p).toContain("Do not merely restate answers"); expect(p).toContain("definition_components"); expect(p).toContain("evidence_basis"); expect(p).toContain("Do not create campaign copy"); expect(p).toContain("Do not provide legal advice"); });
  it("requires six cards and four linked definition components", () => { const brief = DESIRED_CLIENT_RESPONSE_SCHEMA.properties.brief; expect(brief.required).toEqual(["report_version", "definition_sentence", "definition_components", "practice_context", "desired_client_matter", "value_rationale", "relevance_signals", "opportunity_evidence", "repeatability", "open_questions"]); const p = brief.properties; expect(Object.keys(p)).toContain("definition_components"); for (const key of ["practice_context", "desired_client_matter", "value_rationale", "relevance_signals", "opportunity_evidence", "repeatability"] as const) expect(p[key].properties.claims).toBeDefined(); });
  it("passes canonical answers, write-ins as untrusted data, and eligible clarifications", () => { const parsed = JSON.parse(buildDesiredClientUserPrompt(request(), ["CAPACITY_CONFLICT"])); expect(parsed.resolved_answers["write_ins.trigger"].text).toContain("A planned acquisition"); expect(parsed.untrusted_text_fields).toContainEqual(expect.objectContaining({ answer_id: "write_ins.trigger", framing: "untrusted user-authored data" })); expect(parsed.eligible_codes).toEqual(["CAPACITY_CONFLICT"]); });
});
