import {describe,expect,it} from "vitest";
import {completeAnswers} from "./blueprint-helpers";
import {buildStructuredBrief} from "../brief";
import {editAnswers,initialToolState} from "../state";
import {DRAFT_STORAGE_KEY,loadDraft,saveDraft} from "../storage";
function memory(){const values=new Map<string,string>();return {values,storage:{getItem:(k:string)=>values.get(k)??null,setItem:(k:string,v:string)=>{values.set(k,v);},removeItem:(k:string)=>{values.delete(k);}} as unknown as Storage};}
describe("draft lifecycle and migration",()=>{
 it("resets dependent situation, decision and fit responses when focus changes",()=>{const a=completeAnswers();a.write_ins={trigger:"Offer received",fit_signals:"Can share information"};const state={...initialToolState(),view:"brief" as const,answers:a,savedBrief:{brief:buildStructuredBrief(a),sourceBriefRevision:a.revision,generatedAt:new Date().toISOString(),wordingReviewed:true,mode:"structured" as const},reviewed:true};const next=editAnswers(state,d=>({...d,focus:{...d.focus,area:"employment"}}));expect(next.answers.situation.trigger).toBeNull();expect(next.answers.client.decision_needs).toEqual([]);expect(next.answers.delivery.fit_signals).toEqual([]);expect(next.answers.write_ins?.trigger).toBeUndefined();expect(next.savedBrief).toBeNull();expect(next.reviewed).toBe(false);});
 it("migrates a strict v2.1 draft, preserves its TTL, and invalidates the old report",()=>{const {storage}=memory(),a=completeAnswers();const legacy={...a,schema_version:"dcm-v2.1",situation:{timing:a.situation.timing,role:a.situation.role,role_other:a.situation.role_other,contact:a.situation.contact},client:{goals:a.client.goals,concerns:a.client.concerns},delivery:{conditions:a.delivery.conditions,capacity:a.delivery.capacity,limit:a.delivery.limit}} as Record<string,unknown>;delete legacy.write_ins;const now=Date.now(),record={schemaVersion:2,answers:legacy,currentStage:6,lastEditedAt:new Date(now-1000).toISOString(),expiresAt:new Date(now+100000).toISOString(),savedBrief:{discard:true}};storage.setItem(DRAFT_STORAGE_KEY,JSON.stringify(record));const loaded=loadDraft(storage,now);expect(loaded.status).toBe("ready");if(loaded.status==="ready"){expect(loaded.migrated).toBe(true);expect(loaded.draft.answers.schema_version).toBe("dcm-v2.2");expect(loaded.draft.currentStage).toBe(2);expect(loaded.draft.savedBrief).toBeUndefined();expect(Date.parse(loaded.draft.expiresAt)).toBe(now+100000);} });
 it("saves and restores a validated v2.2 structured blueprint",()=>{const {storage}=memory(),a=completeAnswers();const saved=saveDraft(storage,a,7);expect(saved).not.toBeNull();expect(loadDraft(storage).status).toBe("ready");});
});
